/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { DeleteOrgInvitesByIdOptions, DeleteOrgInvitesByIdStatus204, DeleteOrgInvitesByIdStatus401, DeleteOrgInvitesByIdStatus403 } from '../types/DeleteOrgInvitesById'
import type { MutationObserverOptions, QueryClient } from '@tanstack/vue-query'
import { deleteOrgInvitesById } from '../clients/deleteOrgInvitesById'
import { useMutation } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const deleteOrgInvitesByIdMutationKey = () => [{ url: '/t/:slug/Invites/:id' }] as const

/**
 * {@link /t/:slug/Invites/:id}
 */
export function useDeleteOrgInvitesById<TContext>(options: {
  mutation?: MutationObserverOptions<DeleteOrgInvitesByIdStatus204, ResponseErrorConfig<DeleteOrgInvitesByIdStatus401 | DeleteOrgInvitesByIdStatus403>, DeleteOrgInvitesByIdOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions?.mutationKey ?? deleteOrgInvitesByIdMutationKey()

  return useMutation<DeleteOrgInvitesByIdStatus204, ResponseErrorConfig<DeleteOrgInvitesByIdStatus401 | DeleteOrgInvitesByIdStatus403>, DeleteOrgInvitesByIdOptions, TContext>({
    mutationFn: async({ path }) => {
      return deleteOrgInvitesById({ ...config, path: toValue<DeleteOrgInvitesByIdOptions['path']>(path), throwOnError: true }).unwrap()
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}
