/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { DeleteOrgBookingsByIdOptions, DeleteOrgBookingsByIdStatus204, DeleteOrgBookingsByIdStatus401, DeleteOrgBookingsByIdStatus403 } from '../types/DeleteOrgBookingsById'
import type { MutationObserverOptions, QueryClient } from '@tanstack/vue-query'
import { deleteOrgBookingsById } from '../clients/deleteOrgBookingsById'
import { useMutation } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const deleteOrgBookingsByIdMutationKey = () => [{ url: '/t/:slug/Bookings/:id' }] as const

/**
 * {@link /t/:slug/Bookings/:id}
 */
export function useDeleteOrgBookingsById<TContext>(options: {
  mutation?: MutationObserverOptions<DeleteOrgBookingsByIdStatus204, ResponseErrorConfig<DeleteOrgBookingsByIdStatus401 | DeleteOrgBookingsByIdStatus403>, DeleteOrgBookingsByIdOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions?.mutationKey ?? deleteOrgBookingsByIdMutationKey()

  return useMutation<DeleteOrgBookingsByIdStatus204, ResponseErrorConfig<DeleteOrgBookingsByIdStatus401 | DeleteOrgBookingsByIdStatus403>, DeleteOrgBookingsByIdOptions, TContext>({
    mutationFn: async({ path }) => {
      return deleteOrgBookingsById({ ...config, path: toValue<DeleteOrgBookingsByIdOptions['path']>(path), throwOnError: true }).unwrap()
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}
