/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { DeleteAdminBookingsOptions, DeleteAdminBookingsStatus204 } from '../types/DeleteAdminBookings'
import type { MutationObserverOptions, QueryClient } from '@tanstack/vue-query'
import { deleteAdminBookings } from '../clients/deleteAdminBookings'
import { useMutation } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const deleteAdminBookingsMutationKey = () => [{ url: '/Admin/Bookings/:id' }] as const

/**
 * {@link /Admin/Bookings/:id}
 */
export function useDeleteAdminBookings<TContext>(options: {
  mutation?: MutationObserverOptions<DeleteAdminBookingsStatus204, ResponseErrorConfig<Error>, DeleteAdminBookingsOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions?.mutationKey ?? deleteAdminBookingsMutationKey()

  return useMutation<DeleteAdminBookingsStatus204, ResponseErrorConfig<Error>, DeleteAdminBookingsOptions, TContext>({
    mutationFn: async({ path }) => {
      return deleteAdminBookings({ ...config, path: toValue<DeleteAdminBookingsOptions['path']>(path), throwOnError: true }).unwrap()
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}
