/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { DeleteOrgFacilitiesByIdOptions, DeleteOrgFacilitiesByIdStatus204, DeleteOrgFacilitiesByIdStatus401, DeleteOrgFacilitiesByIdStatus403 } from '../types/DeleteOrgFacilitiesById'
import type { MutationObserverOptions, QueryClient } from '@tanstack/vue-query'
import { deleteOrgFacilitiesById } from '../clients/deleteOrgFacilitiesById'
import { useMutation } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const deleteOrgFacilitiesByIdMutationKey = () => [{ url: '/t/:slug/Facilities/:id' }] as const

/**
 * {@link /t/:slug/Facilities/:id}
 */
export function useDeleteOrgFacilitiesById<TContext>(options: {
  mutation?: MutationObserverOptions<DeleteOrgFacilitiesByIdStatus204, ResponseErrorConfig<DeleteOrgFacilitiesByIdStatus401 | DeleteOrgFacilitiesByIdStatus403>, DeleteOrgFacilitiesByIdOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions?.mutationKey ?? deleteOrgFacilitiesByIdMutationKey()

  return useMutation<DeleteOrgFacilitiesByIdStatus204, ResponseErrorConfig<DeleteOrgFacilitiesByIdStatus401 | DeleteOrgFacilitiesByIdStatus403>, DeleteOrgFacilitiesByIdOptions, TContext>({
    mutationFn: async({ path }) => {
      return deleteOrgFacilitiesById({ ...config, path: toValue<DeleteOrgFacilitiesByIdOptions['path']>(path), throwOnError: true }).unwrap()
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}
