/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { DeleteMeTelegramStatus204, DeleteMeTelegramStatus401, DeleteMeTelegramStatus403 } from '../types/DeleteMeTelegram'
import type { MutationObserverOptions, QueryClient } from '@tanstack/vue-query'
import { deleteMeTelegram } from '../clients/deleteMeTelegram'
import { useMutation } from '@tanstack/vue-query'

export const deleteMeTelegramMutationKey = () => [{ url: '/Me/Telegram' }] as const

/**
 * {@link /Me/Telegram}
 */
export function useDeleteMeTelegram<TContext>(options: {
  mutation?: MutationObserverOptions<DeleteMeTelegramStatus204, ResponseErrorConfig<DeleteMeTelegramStatus401 | DeleteMeTelegramStatus403>, undefined, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions?.mutationKey ?? deleteMeTelegramMutationKey()

  return useMutation<DeleteMeTelegramStatus204, ResponseErrorConfig<DeleteMeTelegramStatus401 | DeleteMeTelegramStatus403>, undefined, TContext>({
    mutationFn: async() => {
      return deleteMeTelegram({ ...config, throwOnError: true }).unwrap()
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}
