/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { DeleteOrgUnitsByIdOptions, DeleteOrgUnitsByIdStatus204, DeleteOrgUnitsByIdStatus401, DeleteOrgUnitsByIdStatus403 } from '../types/DeleteOrgUnitsById'
import type { MutationObserverOptions, QueryClient } from '@tanstack/vue-query'
import { deleteOrgUnitsById } from '../clients/deleteOrgUnitsById'
import { useMutation } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const deleteOrgUnitsByIdMutationKey = () => [{ url: '/t/:slug/Units/:id' }] as const

/**
 * {@link /t/:slug/Units/:id}
 */
export function useDeleteOrgUnitsById<TContext>(options: {
  mutation?: MutationObserverOptions<DeleteOrgUnitsByIdStatus204, ResponseErrorConfig<DeleteOrgUnitsByIdStatus401 | DeleteOrgUnitsByIdStatus403>, DeleteOrgUnitsByIdOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions?.mutationKey ?? deleteOrgUnitsByIdMutationKey()

  return useMutation<DeleteOrgUnitsByIdStatus204, ResponseErrorConfig<DeleteOrgUnitsByIdStatus401 | DeleteOrgUnitsByIdStatus403>, DeleteOrgUnitsByIdOptions, TContext>({
    mutationFn: async({ path }) => {
      return deleteOrgUnitsById({ ...config, path: toValue<DeleteOrgUnitsByIdOptions['path']>(path), throwOnError: true }).unwrap()
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}
