/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { DeleteTenantsDeletionOptions, DeleteTenantsDeletionStatus204, DeleteTenantsDeletionStatus401, DeleteTenantsDeletionStatus403 } from '../types/DeleteTenantsDeletion'
import type { MutationObserverOptions, QueryClient } from '@tanstack/vue-query'
import { deleteTenantsDeletion } from '../clients/deleteTenantsDeletion'
import { useMutation } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const deleteTenantsDeletionMutationKey = () => [{ url: '/Tenants/:slug/Deletion' }] as const

/**
 * {@link /Tenants/:slug/Deletion}
 */
export function useDeleteTenantsDeletion<TContext>(options: {
  mutation?: MutationObserverOptions<DeleteTenantsDeletionStatus204, ResponseErrorConfig<DeleteTenantsDeletionStatus401 | DeleteTenantsDeletionStatus403>, DeleteTenantsDeletionOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions?.mutationKey ?? deleteTenantsDeletionMutationKey()

  return useMutation<DeleteTenantsDeletionStatus204, ResponseErrorConfig<DeleteTenantsDeletionStatus401 | DeleteTenantsDeletionStatus403>, DeleteTenantsDeletionOptions, TContext>({
    mutationFn: async({ path }) => {
      return deleteTenantsDeletion({ ...config, path: toValue<DeleteTenantsDeletionOptions['path']>(path), throwOnError: true }).unwrap()
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}
