/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { DeleteBookingByIdOptions, DeleteBookingByIdStatus204, DeleteBookingByIdStatus401, DeleteBookingByIdStatus403 } from '../types/DeleteBookingById'
import type { MutationObserverOptions, QueryClient } from '@tanstack/vue-query'
import { deleteBookingById } from '../clients/deleteBookingById'
import { useMutation } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const deleteBookingByIdMutationKey = () => [{ url: '/Booking/:id' }] as const

/**
 * {@link /Booking/:id}
 */
export function useDeleteBookingById<TContext>(options: {
  mutation?: MutationObserverOptions<DeleteBookingByIdStatus204, ResponseErrorConfig<DeleteBookingByIdStatus401 | DeleteBookingByIdStatus403>, DeleteBookingByIdOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions?.mutationKey ?? deleteBookingByIdMutationKey()

  return useMutation<DeleteBookingByIdStatus204, ResponseErrorConfig<DeleteBookingByIdStatus401 | DeleteBookingByIdStatus403>, DeleteBookingByIdOptions, TContext>({
    mutationFn: async({ path }) => {
      return deleteBookingById({ ...config, path: toValue<DeleteBookingByIdOptions['path']>(path), throwOnError: true }).unwrap()
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}
