/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetBookingByIdOptions, GetBookingByIdStatus200, GetBookingByIdStatus401 } from '../types/GetBookingById'
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from '@tanstack/vue-query'
import type { MaybeRefOrGetter } from 'vue'
import { getBookingById } from '../clients/getBookingById'
import { queryOptions, useQuery } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const getBookingByIdQueryKey = ({ path }: { path: MaybeRefOrGetter<Omit<GetBookingByIdOptions, 'headers'>['path']> }) => [{ url: '/Booking/:id', params: path }] as const

export type GetBookingByIdQueryKey = ReturnType<typeof getBookingByIdQueryKey>

export function getBookingByIdQueryOptions({ path }: { path: MaybeRefOrGetter<GetBookingByIdOptions['path']> }, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getBookingByIdQueryKey({ path })
  return queryOptions<GetBookingByIdStatus200, ResponseErrorConfig<GetBookingByIdStatus401>, GetBookingByIdStatus200>({
   queryKey,
   queryFn: async ({ signal }) => {
      return getBookingById({ ...config, path: toValue(path), signal: config.signal ?? signal, throwOnError: true }).unwrap()
   },
  })
}

/**
 * {@link /Booking/:id}
 */
export function useGetBookingById<TData = GetBookingByIdStatus200, TQueryData = GetBookingByIdStatus200, TQueryKey extends QueryKey = GetBookingByIdQueryKey>({ path }: { path: MaybeRefOrGetter<GetBookingByIdOptions['path']> }, options: {
  query?: Partial<UseQueryOptions<GetBookingByIdStatus200, ResponseErrorConfig<GetBookingByIdStatus401>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? getBookingByIdQueryKey({ path })

  const queryResult = useQuery({
   ...getBookingByIdQueryOptions({ path }, config),
   ...resolvedOptions,
   queryKey
  } as unknown as UseQueryOptions<GetBookingByIdStatus200, ResponseErrorConfig<GetBookingByIdStatus401>, TData, GetBookingByIdStatus200, TQueryKey>, toValue(queryClient)) as UseQueryReturnType<TData, ResponseErrorConfig<GetBookingByIdStatus401>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}
