/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetInvitesByTokenOptions, GetInvitesByTokenStatus200, GetInvitesByTokenStatus401, GetInvitesByTokenStatus403 } from '../types/GetInvitesByToken'
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from '@tanstack/vue-query'
import type { MaybeRefOrGetter } from 'vue'
import { getInvitesByToken } from '../clients/getInvitesByToken'
import { queryOptions, useQuery } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const getInvitesByTokenQueryKey = ({ path }: { path: MaybeRefOrGetter<Omit<GetInvitesByTokenOptions, 'headers'>['path']> }) => [{ url: '/Invites/:token', params: path }] as const

export type GetInvitesByTokenQueryKey = ReturnType<typeof getInvitesByTokenQueryKey>

export function getInvitesByTokenQueryOptions({ path }: { path: MaybeRefOrGetter<GetInvitesByTokenOptions['path']> }, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getInvitesByTokenQueryKey({ path })
  return queryOptions<GetInvitesByTokenStatus200, ResponseErrorConfig<GetInvitesByTokenStatus401 | GetInvitesByTokenStatus403>, GetInvitesByTokenStatus200>({
   queryKey,
   queryFn: async ({ signal }) => {
      return getInvitesByToken({ ...config, path: toValue(path), signal: config.signal ?? signal, throwOnError: true }).unwrap()
   },
  })
}

/**
 * {@link /Invites/:token}
 */
export function useGetInvitesByToken<TData = GetInvitesByTokenStatus200, TQueryData = GetInvitesByTokenStatus200, TQueryKey extends QueryKey = GetInvitesByTokenQueryKey>({ path }: { path: MaybeRefOrGetter<GetInvitesByTokenOptions['path']> }, options: {
  query?: Partial<UseQueryOptions<GetInvitesByTokenStatus200, ResponseErrorConfig<GetInvitesByTokenStatus401 | GetInvitesByTokenStatus403>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? getInvitesByTokenQueryKey({ path })

  const queryResult = useQuery({
   ...getInvitesByTokenQueryOptions({ path }, config),
   ...resolvedOptions,
   queryKey
  } as unknown as UseQueryOptions<GetInvitesByTokenStatus200, ResponseErrorConfig<GetInvitesByTokenStatus401 | GetInvitesByTokenStatus403>, TData, GetInvitesByTokenStatus200, TQueryKey>, toValue(queryClient)) as UseQueryReturnType<TData, ResponseErrorConfig<GetInvitesByTokenStatus401 | GetInvitesByTokenStatus403>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}
