/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetBookingStatus200, GetBookingStatus401 } from '../types/GetBooking'
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from '@tanstack/vue-query'
import { getBooking } from '../clients/getBooking'
import { queryOptions, useQuery } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const getBookingQueryKey = () => [{ url: '/Booking' }] as const

export type GetBookingQueryKey = ReturnType<typeof getBookingQueryKey>

export function getBookingQueryOptions(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getBookingQueryKey()
  return queryOptions<GetBookingStatus200, ResponseErrorConfig<GetBookingStatus401>, GetBookingStatus200>({
   queryKey,
   queryFn: async ({ signal }) => {
      return getBooking({ ...config, signal: config.signal ?? signal, throwOnError: true }).unwrap()
   },
  })
}

/**
 * {@link /Booking}
 */
export function useGetBooking<TData = GetBookingStatus200, TQueryData = GetBookingStatus200, TQueryKey extends QueryKey = GetBookingQueryKey>(options: {
  query?: Partial<UseQueryOptions<GetBookingStatus200, ResponseErrorConfig<GetBookingStatus401>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? getBookingQueryKey()

  const queryResult = useQuery({
   ...getBookingQueryOptions(config),
   ...resolvedOptions,
   queryKey
  } as unknown as UseQueryOptions<GetBookingStatus200, ResponseErrorConfig<GetBookingStatus401>, TData, GetBookingStatus200, TQueryKey>, toValue(queryClient)) as UseQueryReturnType<TData, ResponseErrorConfig<GetBookingStatus401>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}
