/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetOrgFacilitiesOptions, GetOrgFacilitiesStatus200, GetOrgFacilitiesStatus401, GetOrgFacilitiesStatus403 } from '../types/GetOrgFacilities'
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from '@tanstack/vue-query'
import type { MaybeRefOrGetter } from 'vue'
import { getOrgFacilities } from '../clients/getOrgFacilities'
import { queryOptions, useQuery } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const getOrgFacilitiesQueryKey = ({ path }: { path: MaybeRefOrGetter<Omit<GetOrgFacilitiesOptions, 'headers'>['path']> }) => [{ url: '/t/:slug/Facilities', params: path }] as const

export type GetOrgFacilitiesQueryKey = ReturnType<typeof getOrgFacilitiesQueryKey>

export function getOrgFacilitiesQueryOptions({ path }: { path: MaybeRefOrGetter<GetOrgFacilitiesOptions['path']> }, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getOrgFacilitiesQueryKey({ path })
  return queryOptions<GetOrgFacilitiesStatus200, ResponseErrorConfig<GetOrgFacilitiesStatus401 | GetOrgFacilitiesStatus403>, GetOrgFacilitiesStatus200>({
   queryKey,
   queryFn: async ({ signal }) => {
      return getOrgFacilities({ ...config, path: toValue(path), signal: config.signal ?? signal, throwOnError: true }).unwrap()
   },
  })
}

/**
 * {@link /t/:slug/Facilities}
 */
export function useGetOrgFacilities<TData = GetOrgFacilitiesStatus200, TQueryData = GetOrgFacilitiesStatus200, TQueryKey extends QueryKey = GetOrgFacilitiesQueryKey>({ path }: { path: MaybeRefOrGetter<GetOrgFacilitiesOptions['path']> }, options: {
  query?: Partial<UseQueryOptions<GetOrgFacilitiesStatus200, ResponseErrorConfig<GetOrgFacilitiesStatus401 | GetOrgFacilitiesStatus403>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? getOrgFacilitiesQueryKey({ path })

  const queryResult = useQuery({
   ...getOrgFacilitiesQueryOptions({ path }, config),
   ...resolvedOptions,
   queryKey
  } as unknown as UseQueryOptions<GetOrgFacilitiesStatus200, ResponseErrorConfig<GetOrgFacilitiesStatus401 | GetOrgFacilitiesStatus403>, TData, GetOrgFacilitiesStatus200, TQueryKey>, toValue(queryClient)) as UseQueryReturnType<TData, ResponseErrorConfig<GetOrgFacilitiesStatus401 | GetOrgFacilitiesStatus403>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}
