/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetOrgSettingsOptions, GetOrgSettingsStatus200, GetOrgSettingsStatus401, GetOrgSettingsStatus403 } from '../types/GetOrgSettings'
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from '@tanstack/vue-query'
import type { MaybeRefOrGetter } from 'vue'
import { getOrgSettings } from '../clients/getOrgSettings'
import { queryOptions, useQuery } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const getOrgSettingsQueryKey = ({ path }: { path: MaybeRefOrGetter<Omit<GetOrgSettingsOptions, 'headers'>['path']> }) => [{ url: '/t/:slug/Settings', params: path }] as const

export type GetOrgSettingsQueryKey = ReturnType<typeof getOrgSettingsQueryKey>

export function getOrgSettingsQueryOptions({ path }: { path: MaybeRefOrGetter<GetOrgSettingsOptions['path']> }, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getOrgSettingsQueryKey({ path })
  return queryOptions<GetOrgSettingsStatus200, ResponseErrorConfig<GetOrgSettingsStatus401 | GetOrgSettingsStatus403>, GetOrgSettingsStatus200>({
   queryKey,
   queryFn: async ({ signal }) => {
      return getOrgSettings({ ...config, path: toValue(path), signal: config.signal ?? signal, throwOnError: true }).unwrap()
   },
  })
}

/**
 * {@link /t/:slug/Settings}
 */
export function useGetOrgSettings<TData = GetOrgSettingsStatus200, TQueryData = GetOrgSettingsStatus200, TQueryKey extends QueryKey = GetOrgSettingsQueryKey>({ path }: { path: MaybeRefOrGetter<GetOrgSettingsOptions['path']> }, options: {
  query?: Partial<UseQueryOptions<GetOrgSettingsStatus200, ResponseErrorConfig<GetOrgSettingsStatus401 | GetOrgSettingsStatus403>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? getOrgSettingsQueryKey({ path })

  const queryResult = useQuery({
   ...getOrgSettingsQueryOptions({ path }, config),
   ...resolvedOptions,
   queryKey
  } as unknown as UseQueryOptions<GetOrgSettingsStatus200, ResponseErrorConfig<GetOrgSettingsStatus401 | GetOrgSettingsStatus403>, TData, GetOrgSettingsStatus200, TQueryKey>, toValue(queryClient)) as UseQueryReturnType<TData, ResponseErrorConfig<GetOrgSettingsStatus401 | GetOrgSettingsStatus403>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}
