/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetAdminBookingsStatus200 } from '../types/GetAdminBookings'
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from '@tanstack/vue-query'
import { getAdminBookings } from '../clients/getAdminBookings'
import { queryOptions, useQuery } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const getAdminBookingsQueryKey = () => [{ url: '/Admin/Bookings' }] as const

export type GetAdminBookingsQueryKey = ReturnType<typeof getAdminBookingsQueryKey>

export function getAdminBookingsQueryOptions(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getAdminBookingsQueryKey()
  return queryOptions<GetAdminBookingsStatus200, ResponseErrorConfig<Error>, GetAdminBookingsStatus200>({
   queryKey,
   queryFn: async ({ signal }) => {
      return getAdminBookings({ ...config, signal: config.signal ?? signal, throwOnError: true }).unwrap()
   },
  })
}

/**
 * {@link /Admin/Bookings}
 */
export function useGetAdminBookings<TData = GetAdminBookingsStatus200, TQueryData = GetAdminBookingsStatus200, TQueryKey extends QueryKey = GetAdminBookingsQueryKey>(options: {
  query?: Partial<UseQueryOptions<GetAdminBookingsStatus200, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? getAdminBookingsQueryKey()

  const queryResult = useQuery({
   ...getAdminBookingsQueryOptions(config),
   ...resolvedOptions,
   queryKey
  } as unknown as UseQueryOptions<GetAdminBookingsStatus200, ResponseErrorConfig<Error>, TData, GetAdminBookingsStatus200, TQueryKey>, toValue(queryClient)) as UseQueryReturnType<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}
