/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetCachePurgeStatus204 } from '../types/GetCachePurge'
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from '@tanstack/vue-query'
import { getCachePurge } from '../clients/getCachePurge'
import { queryOptions, useQuery } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const getCachePurgeQueryKey = () => [{ url: '/Cache/Purge' }] as const

export type GetCachePurgeQueryKey = ReturnType<typeof getCachePurgeQueryKey>

export function getCachePurgeQueryOptions(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getCachePurgeQueryKey()
  return queryOptions<GetCachePurgeStatus204, ResponseErrorConfig<Error>, GetCachePurgeStatus204>({
   queryKey,
   queryFn: async ({ signal }) => {
      return getCachePurge({ ...config, signal: config.signal ?? signal, throwOnError: true }).unwrap()
   },
  })
}

/**
 * {@link /Cache/Purge}
 */
export function useGetCachePurge<TData = GetCachePurgeStatus204, TQueryData = GetCachePurgeStatus204, TQueryKey extends QueryKey = GetCachePurgeQueryKey>(options: {
  query?: Partial<UseQueryOptions<GetCachePurgeStatus204, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? getCachePurgeQueryKey()

  const queryResult = useQuery({
   ...getCachePurgeQueryOptions(config),
   ...resolvedOptions,
   queryKey
  } as unknown as UseQueryOptions<GetCachePurgeStatus204, ResponseErrorConfig<Error>, TData, GetCachePurgeStatus204, TQueryKey>, toValue(queryClient)) as UseQueryReturnType<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}
