/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetOrgFacilitiesBookableOptions, GetOrgFacilitiesBookableStatus200, GetOrgFacilitiesBookableStatus401, GetOrgFacilitiesBookableStatus403 } from '../types/GetOrgFacilitiesBookable'
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from '@tanstack/vue-query'
import type { MaybeRefOrGetter } from 'vue'
import { getOrgFacilitiesBookable } from '../clients/getOrgFacilitiesBookable'
import { queryOptions, useQuery } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const getOrgFacilitiesBookableQueryKey = ({ path }: { path: MaybeRefOrGetter<Omit<GetOrgFacilitiesBookableOptions, 'headers'>['path']> }) => [{ url: '/t/:slug/Facilities/Bookable', params: path }] as const

export type GetOrgFacilitiesBookableQueryKey = ReturnType<typeof getOrgFacilitiesBookableQueryKey>

export function getOrgFacilitiesBookableQueryOptions({ path }: { path: MaybeRefOrGetter<GetOrgFacilitiesBookableOptions['path']> }, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getOrgFacilitiesBookableQueryKey({ path })
  return queryOptions<GetOrgFacilitiesBookableStatus200, ResponseErrorConfig<GetOrgFacilitiesBookableStatus401 | GetOrgFacilitiesBookableStatus403>, GetOrgFacilitiesBookableStatus200>({
   queryKey,
   queryFn: async ({ signal }) => {
      return getOrgFacilitiesBookable({ ...config, path: toValue(path), signal: config.signal ?? signal, throwOnError: true }).unwrap()
   },
  })
}

/**
 * {@link /t/:slug/Facilities/Bookable}
 */
export function useGetOrgFacilitiesBookable<TData = GetOrgFacilitiesBookableStatus200, TQueryData = GetOrgFacilitiesBookableStatus200, TQueryKey extends QueryKey = GetOrgFacilitiesBookableQueryKey>({ path }: { path: MaybeRefOrGetter<GetOrgFacilitiesBookableOptions['path']> }, options: {
  query?: Partial<UseQueryOptions<GetOrgFacilitiesBookableStatus200, ResponseErrorConfig<GetOrgFacilitiesBookableStatus401 | GetOrgFacilitiesBookableStatus403>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? getOrgFacilitiesBookableQueryKey({ path })

  const queryResult = useQuery({
   ...getOrgFacilitiesBookableQueryOptions({ path }, config),
   ...resolvedOptions,
   queryKey
  } as unknown as UseQueryOptions<GetOrgFacilitiesBookableStatus200, ResponseErrorConfig<GetOrgFacilitiesBookableStatus401 | GetOrgFacilitiesBookableStatus403>, TData, GetOrgFacilitiesBookableStatus200, TQueryKey>, toValue(queryClient)) as UseQueryReturnType<TData, ResponseErrorConfig<GetOrgFacilitiesBookableStatus401 | GetOrgFacilitiesBookableStatus403>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}
