/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetOrgBookingsByIdOptions, GetOrgBookingsByIdStatus200, GetOrgBookingsByIdStatus401, GetOrgBookingsByIdStatus403 } from '../types/GetOrgBookingsById'
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from '@tanstack/vue-query'
import type { MaybeRefOrGetter } from 'vue'
import { getOrgBookingsById } from '../clients/getOrgBookingsById'
import { queryOptions, useQuery } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const getOrgBookingsByIdQueryKey = ({ path }: { path: MaybeRefOrGetter<Omit<GetOrgBookingsByIdOptions, 'headers'>['path']> }) => [{ url: '/t/:slug/Bookings/:id', params: path }] as const

export type GetOrgBookingsByIdQueryKey = ReturnType<typeof getOrgBookingsByIdQueryKey>

export function getOrgBookingsByIdQueryOptions({ path }: { path: MaybeRefOrGetter<GetOrgBookingsByIdOptions['path']> }, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getOrgBookingsByIdQueryKey({ path })
  return queryOptions<GetOrgBookingsByIdStatus200, ResponseErrorConfig<GetOrgBookingsByIdStatus401 | GetOrgBookingsByIdStatus403>, GetOrgBookingsByIdStatus200>({
   queryKey,
   queryFn: async ({ signal }) => {
      return getOrgBookingsById({ ...config, path: toValue(path), signal: config.signal ?? signal, throwOnError: true }).unwrap()
   },
  })
}

/**
 * {@link /t/:slug/Bookings/:id}
 */
export function useGetOrgBookingsById<TData = GetOrgBookingsByIdStatus200, TQueryData = GetOrgBookingsByIdStatus200, TQueryKey extends QueryKey = GetOrgBookingsByIdQueryKey>({ path }: { path: MaybeRefOrGetter<GetOrgBookingsByIdOptions['path']> }, options: {
  query?: Partial<UseQueryOptions<GetOrgBookingsByIdStatus200, ResponseErrorConfig<GetOrgBookingsByIdStatus401 | GetOrgBookingsByIdStatus403>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? getOrgBookingsByIdQueryKey({ path })

  const queryResult = useQuery({
   ...getOrgBookingsByIdQueryOptions({ path }, config),
   ...resolvedOptions,
   queryKey
  } as unknown as UseQueryOptions<GetOrgBookingsByIdStatus200, ResponseErrorConfig<GetOrgBookingsByIdStatus401 | GetOrgBookingsByIdStatus403>, TData, GetOrgBookingsByIdStatus200, TQueryKey>, toValue(queryClient)) as UseQueryReturnType<TData, ResponseErrorConfig<GetOrgBookingsByIdStatus401 | GetOrgBookingsByIdStatus403>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}
