/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetFacilityTimeSlotsOptions, GetFacilityTimeSlotsStatus200, GetFacilityTimeSlotsStatus401 } from '../types/GetFacilityTimeSlots'
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from '@tanstack/vue-query'
import type { MaybeRefOrGetter } from 'vue'
import { getFacilityTimeSlots } from '../clients/getFacilityTimeSlots'
import { queryOptions, useQuery } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const getFacilityTimeSlotsQueryKey = ({ path, query }: { path: MaybeRefOrGetter<Omit<GetFacilityTimeSlotsOptions, 'headers'>['path']>; query: MaybeRefOrGetter<Omit<GetFacilityTimeSlotsOptions, 'headers'>['query']> }) => [{ url: '/Facility/:name/TimeSlots', params: path }, ...(query ? [query] : [])] as const

export type GetFacilityTimeSlotsQueryKey = ReturnType<typeof getFacilityTimeSlotsQueryKey>

export function getFacilityTimeSlotsQueryOptions({ path, query }: { path: MaybeRefOrGetter<GetFacilityTimeSlotsOptions['path']>; query: MaybeRefOrGetter<GetFacilityTimeSlotsOptions['query']> }, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getFacilityTimeSlotsQueryKey({ path, query })
  return queryOptions<GetFacilityTimeSlotsStatus200, ResponseErrorConfig<GetFacilityTimeSlotsStatus401>, GetFacilityTimeSlotsStatus200>({
   queryKey,
   queryFn: async ({ signal }) => {
      return getFacilityTimeSlots({ ...config, path: toValue(path), query: toValue(query), signal: config.signal ?? signal, throwOnError: true }).unwrap()
   },
  })
}

/**
 * {@link /Facility/:name/TimeSlots}
 */
export function useGetFacilityTimeSlots<TData = GetFacilityTimeSlotsStatus200, TQueryData = GetFacilityTimeSlotsStatus200, TQueryKey extends QueryKey = GetFacilityTimeSlotsQueryKey>({ path, query }: { path: MaybeRefOrGetter<GetFacilityTimeSlotsOptions['path']>; query: MaybeRefOrGetter<GetFacilityTimeSlotsOptions['query']> }, options: {
  query?: Partial<UseQueryOptions<GetFacilityTimeSlotsStatus200, ResponseErrorConfig<GetFacilityTimeSlotsStatus401>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? getFacilityTimeSlotsQueryKey({ path, query })

  const queryResult = useQuery({
   ...getFacilityTimeSlotsQueryOptions({ path, query }, config),
   ...resolvedOptions,
   queryKey
  } as unknown as UseQueryOptions<GetFacilityTimeSlotsStatus200, ResponseErrorConfig<GetFacilityTimeSlotsStatus401>, TData, GetFacilityTimeSlotsStatus200, TQueryKey>, toValue(queryClient)) as UseQueryReturnType<TData, ResponseErrorConfig<GetFacilityTimeSlotsStatus401>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}
