/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetMeStatus200, GetMeStatus401, GetMeStatus403 } from '../types/GetMe'
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from '@tanstack/vue-query'
import { getMe } from '../clients/getMe'
import { queryOptions, useQuery } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const getMeQueryKey = () => [{ url: '/Me' }] as const

export type GetMeQueryKey = ReturnType<typeof getMeQueryKey>

export function getMeQueryOptions(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getMeQueryKey()
  return queryOptions<GetMeStatus200, ResponseErrorConfig<GetMeStatus401 | GetMeStatus403>, GetMeStatus200>({
   queryKey,
   queryFn: async ({ signal }) => {
      return getMe({ ...config, signal: config.signal ?? signal, throwOnError: true }).unwrap()
   },
  })
}

/**
 * {@link /Me}
 */
export function useGetMe<TData = GetMeStatus200, TQueryData = GetMeStatus200, TQueryKey extends QueryKey = GetMeQueryKey>(options: {
  query?: Partial<UseQueryOptions<GetMeStatus200, ResponseErrorConfig<GetMeStatus401 | GetMeStatus403>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? getMeQueryKey()

  const queryResult = useQuery({
   ...getMeQueryOptions(config),
   ...resolvedOptions,
   queryKey
  } as unknown as UseQueryOptions<GetMeStatus200, ResponseErrorConfig<GetMeStatus401 | GetMeStatus403>, TData, GetMeStatus200, TQueryKey>, toValue(queryClient)) as UseQueryReturnType<TData, ResponseErrorConfig<GetMeStatus401 | GetMeStatus403>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}
