/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetOrgAuditOptions, GetOrgAuditStatus200, GetOrgAuditStatus401, GetOrgAuditStatus403 } from '../types/GetOrgAudit'
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from '@tanstack/vue-query'
import type { MaybeRefOrGetter } from 'vue'
import { getOrgAudit } from '../clients/getOrgAudit'
import { queryOptions, useQuery } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const getOrgAuditQueryKey = ({ path, query }: { path: MaybeRefOrGetter<Omit<GetOrgAuditOptions, 'headers'>['path']>; query?: MaybeRefOrGetter<Omit<GetOrgAuditOptions, 'headers'>['query']> }) => [{ url: '/t/:slug/Audit', params: path }, ...(query ? [query] : [])] as const

export type GetOrgAuditQueryKey = ReturnType<typeof getOrgAuditQueryKey>

export function getOrgAuditQueryOptions({ path, query }: { path: MaybeRefOrGetter<GetOrgAuditOptions['path']>; query?: MaybeRefOrGetter<GetOrgAuditOptions['query']> }, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getOrgAuditQueryKey({ path, query })
  return queryOptions<GetOrgAuditStatus200, ResponseErrorConfig<GetOrgAuditStatus401 | GetOrgAuditStatus403>, GetOrgAuditStatus200>({
   queryKey,
   queryFn: async ({ signal }) => {
      return getOrgAudit({ ...config, path: toValue(path), query: toValue(query), signal: config.signal ?? signal, throwOnError: true }).unwrap()
   },
  })
}

/**
 * {@link /t/:slug/Audit}
 */
export function useGetOrgAudit<TData = GetOrgAuditStatus200, TQueryData = GetOrgAuditStatus200, TQueryKey extends QueryKey = GetOrgAuditQueryKey>({ path, query }: { path: MaybeRefOrGetter<GetOrgAuditOptions['path']>; query?: MaybeRefOrGetter<GetOrgAuditOptions['query']> }, options: {
  query?: Partial<UseQueryOptions<GetOrgAuditStatus200, ResponseErrorConfig<GetOrgAuditStatus401 | GetOrgAuditStatus403>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? getOrgAuditQueryKey({ path, query })

  const queryResult = useQuery({
   ...getOrgAuditQueryOptions({ path, query }, config),
   ...resolvedOptions,
   queryKey
  } as unknown as UseQueryOptions<GetOrgAuditStatus200, ResponseErrorConfig<GetOrgAuditStatus401 | GetOrgAuditStatus403>, TData, GetOrgAuditStatus200, TQueryKey>, toValue(queryClient)) as UseQueryReturnType<TData, ResponseErrorConfig<GetOrgAuditStatus401 | GetOrgAuditStatus403>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}
