/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetMeExportStatus200, GetMeExportStatus401, GetMeExportStatus403 } from '../types/GetMeExport'
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from '@tanstack/vue-query'
import { getMeExport } from '../clients/getMeExport'
import { queryOptions, useQuery } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const getMeExportQueryKey = () => [{ url: '/Me/Export' }] as const

export type GetMeExportQueryKey = ReturnType<typeof getMeExportQueryKey>

export function getMeExportQueryOptions(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getMeExportQueryKey()
  return queryOptions<GetMeExportStatus200, ResponseErrorConfig<GetMeExportStatus401 | GetMeExportStatus403>, GetMeExportStatus200>({
   queryKey,
   queryFn: async ({ signal }) => {
      return getMeExport({ ...config, signal: config.signal ?? signal, throwOnError: true }).unwrap()
   },
  })
}

/**
 * {@link /Me/Export}
 */
export function useGetMeExport<TData = GetMeExportStatus200, TQueryData = GetMeExportStatus200, TQueryKey extends QueryKey = GetMeExportQueryKey>(options: {
  query?: Partial<UseQueryOptions<GetMeExportStatus200, ResponseErrorConfig<GetMeExportStatus401 | GetMeExportStatus403>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? getMeExportQueryKey()

  const queryResult = useQuery({
   ...getMeExportQueryOptions(config),
   ...resolvedOptions,
   queryKey
  } as unknown as UseQueryOptions<GetMeExportStatus200, ResponseErrorConfig<GetMeExportStatus401 | GetMeExportStatus403>, TData, GetMeExportStatus200, TQueryKey>, toValue(queryClient)) as UseQueryReturnType<TData, ResponseErrorConfig<GetMeExportStatus401 | GetMeExportStatus403>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}
