/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetOrgOptions, GetOrgStatus200, GetOrgStatus401, GetOrgStatus403 } from '../types/GetOrg'
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from '@tanstack/vue-query'
import type { MaybeRefOrGetter } from 'vue'
import { getOrg } from '../clients/getOrg'
import { queryOptions, useQuery } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const getOrgQueryKey = ({ path }: { path: MaybeRefOrGetter<Omit<GetOrgOptions, 'headers'>['path']> }) => [{ url: '/t/:slug', params: path }] as const

export type GetOrgQueryKey = ReturnType<typeof getOrgQueryKey>

export function getOrgQueryOptions({ path }: { path: MaybeRefOrGetter<GetOrgOptions['path']> }, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getOrgQueryKey({ path })
  return queryOptions<GetOrgStatus200, ResponseErrorConfig<GetOrgStatus401 | GetOrgStatus403>, GetOrgStatus200>({
   queryKey,
   queryFn: async ({ signal }) => {
      return getOrg({ ...config, path: toValue(path), signal: config.signal ?? signal, throwOnError: true }).unwrap()
   },
  })
}

/**
 * {@link /t/:slug}
 */
export function useGetOrg<TData = GetOrgStatus200, TQueryData = GetOrgStatus200, TQueryKey extends QueryKey = GetOrgQueryKey>({ path }: { path: MaybeRefOrGetter<GetOrgOptions['path']> }, options: {
  query?: Partial<UseQueryOptions<GetOrgStatus200, ResponseErrorConfig<GetOrgStatus401 | GetOrgStatus403>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? getOrgQueryKey({ path })

  const queryResult = useQuery({
   ...getOrgQueryOptions({ path }, config),
   ...resolvedOptions,
   queryKey
  } as unknown as UseQueryOptions<GetOrgStatus200, ResponseErrorConfig<GetOrgStatus401 | GetOrgStatus403>, TData, GetOrgStatus200, TQueryKey>, toValue(queryClient)) as UseQueryReturnType<TData, ResponseErrorConfig<GetOrgStatus401 | GetOrgStatus403>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}
