/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetClaimsBySlugOptions, GetClaimsBySlugStatus200, GetClaimsBySlugStatus401, GetClaimsBySlugStatus403 } from '../types/GetClaimsBySlug'
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from '@tanstack/vue-query'
import type { MaybeRefOrGetter } from 'vue'
import { getClaimsBySlug } from '../clients/getClaimsBySlug'
import { queryOptions, useQuery } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const getClaimsBySlugQueryKey = ({ path }: { path: MaybeRefOrGetter<Omit<GetClaimsBySlugOptions, 'headers'>['path']> }) => [{ url: '/Claims/:slug', params: path }] as const

export type GetClaimsBySlugQueryKey = ReturnType<typeof getClaimsBySlugQueryKey>

export function getClaimsBySlugQueryOptions({ path }: { path: MaybeRefOrGetter<GetClaimsBySlugOptions['path']> }, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getClaimsBySlugQueryKey({ path })
  return queryOptions<GetClaimsBySlugStatus200, ResponseErrorConfig<GetClaimsBySlugStatus401 | GetClaimsBySlugStatus403>, GetClaimsBySlugStatus200>({
   queryKey,
   queryFn: async ({ signal }) => {
      return getClaimsBySlug({ ...config, path: toValue(path), signal: config.signal ?? signal, throwOnError: true }).unwrap()
   },
  })
}

/**
 * {@link /Claims/:slug}
 */
export function useGetClaimsBySlug<TData = GetClaimsBySlugStatus200, TQueryData = GetClaimsBySlugStatus200, TQueryKey extends QueryKey = GetClaimsBySlugQueryKey>({ path }: { path: MaybeRefOrGetter<GetClaimsBySlugOptions['path']> }, options: {
  query?: Partial<UseQueryOptions<GetClaimsBySlugStatus200, ResponseErrorConfig<GetClaimsBySlugStatus401 | GetClaimsBySlugStatus403>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? getClaimsBySlugQueryKey({ path })

  const queryResult = useQuery({
   ...getClaimsBySlugQueryOptions({ path }, config),
   ...resolvedOptions,
   queryKey
  } as unknown as UseQueryOptions<GetClaimsBySlugStatus200, ResponseErrorConfig<GetClaimsBySlugStatus401 | GetClaimsBySlugStatus403>, TData, GetClaimsBySlugStatus200, TQueryKey>, toValue(queryClient)) as UseQueryReturnType<TData, ResponseErrorConfig<GetClaimsBySlugStatus401 | GetClaimsBySlugStatus403>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}
