/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetAdminBookingsByIdOptions, GetAdminBookingsByIdStatus200 } from '../types/GetAdminBookingsById'
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from '@tanstack/vue-query'
import type { MaybeRefOrGetter } from 'vue'
import { getAdminBookingsById } from '../clients/getAdminBookingsById'
import { queryOptions, useQuery } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const getAdminBookingsByIdQueryKey = ({ path }: { path: MaybeRefOrGetter<Omit<GetAdminBookingsByIdOptions, 'headers'>['path']> }) => [{ url: '/Admin/Bookings/:id', params: path }] as const

export type GetAdminBookingsByIdQueryKey = ReturnType<typeof getAdminBookingsByIdQueryKey>

export function getAdminBookingsByIdQueryOptions({ path }: { path: MaybeRefOrGetter<GetAdminBookingsByIdOptions['path']> }, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getAdminBookingsByIdQueryKey({ path })
  return queryOptions<GetAdminBookingsByIdStatus200, ResponseErrorConfig<Error>, GetAdminBookingsByIdStatus200>({
   queryKey,
   queryFn: async ({ signal }) => {
      return getAdminBookingsById({ ...config, path: toValue(path), signal: config.signal ?? signal, throwOnError: true }).unwrap()
   },
  })
}

/**
 * {@link /Admin/Bookings/:id}
 */
export function useGetAdminBookingsById<TData = GetAdminBookingsByIdStatus200, TQueryData = GetAdminBookingsByIdStatus200, TQueryKey extends QueryKey = GetAdminBookingsByIdQueryKey>({ path }: { path: MaybeRefOrGetter<GetAdminBookingsByIdOptions['path']> }, options: {
  query?: Partial<UseQueryOptions<GetAdminBookingsByIdStatus200, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? getAdminBookingsByIdQueryKey({ path })

  const queryResult = useQuery({
   ...getAdminBookingsByIdQueryOptions({ path }, config),
   ...resolvedOptions,
   queryKey
  } as unknown as UseQueryOptions<GetAdminBookingsByIdStatus200, ResponseErrorConfig<Error>, TData, GetAdminBookingsByIdStatus200, TQueryKey>, toValue(queryClient)) as UseQueryReturnType<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}
