/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetOrgBookingsOptions, GetOrgBookingsStatus200, GetOrgBookingsStatus401, GetOrgBookingsStatus403 } from '../types/GetOrgBookings'
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from '@tanstack/vue-query'
import type { MaybeRefOrGetter } from 'vue'
import { getOrgBookings } from '../clients/getOrgBookings'
import { queryOptions, useQuery } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const getOrgBookingsQueryKey = ({ path, query }: { path: MaybeRefOrGetter<Omit<GetOrgBookingsOptions, 'headers'>['path']>; query: MaybeRefOrGetter<Omit<GetOrgBookingsOptions, 'headers'>['query']> }) => [{ url: '/t/:slug/Bookings', params: path }, ...(query ? [query] : [])] as const

export type GetOrgBookingsQueryKey = ReturnType<typeof getOrgBookingsQueryKey>

export function getOrgBookingsQueryOptions({ path, query }: { path: MaybeRefOrGetter<GetOrgBookingsOptions['path']>; query: MaybeRefOrGetter<GetOrgBookingsOptions['query']> }, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getOrgBookingsQueryKey({ path, query })
  return queryOptions<GetOrgBookingsStatus200, ResponseErrorConfig<GetOrgBookingsStatus401 | GetOrgBookingsStatus403>, GetOrgBookingsStatus200>({
   queryKey,
   queryFn: async ({ signal }) => {
      return getOrgBookings({ ...config, path: toValue(path), query: toValue(query), signal: config.signal ?? signal, throwOnError: true }).unwrap()
   },
  })
}

/**
 * {@link /t/:slug/Bookings}
 */
export function useGetOrgBookings<TData = GetOrgBookingsStatus200, TQueryData = GetOrgBookingsStatus200, TQueryKey extends QueryKey = GetOrgBookingsQueryKey>({ path, query }: { path: MaybeRefOrGetter<GetOrgBookingsOptions['path']>; query: MaybeRefOrGetter<GetOrgBookingsOptions['query']> }, options: {
  query?: Partial<UseQueryOptions<GetOrgBookingsStatus200, ResponseErrorConfig<GetOrgBookingsStatus401 | GetOrgBookingsStatus403>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? getOrgBookingsQueryKey({ path, query })

  const queryResult = useQuery({
   ...getOrgBookingsQueryOptions({ path, query }, config),
   ...resolvedOptions,
   queryKey
  } as unknown as UseQueryOptions<GetOrgBookingsStatus200, ResponseErrorConfig<GetOrgBookingsStatus401 | GetOrgBookingsStatus403>, TData, GetOrgBookingsStatus200, TQueryKey>, toValue(queryClient)) as UseQueryReturnType<TData, ResponseErrorConfig<GetOrgBookingsStatus401 | GetOrgBookingsStatus403>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}
