/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetNominalRollStatus200, GetNominalRollStatus401 } from '../types/GetNominalRoll'
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from '@tanstack/vue-query'
import { getNominalRoll } from '../clients/getNominalRoll'
import { queryOptions, useQuery } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const getNominalRollQueryKey = () => [{ url: '/NominalRoll' }] as const

export type GetNominalRollQueryKey = ReturnType<typeof getNominalRollQueryKey>

export function getNominalRollQueryOptions(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getNominalRollQueryKey()
  return queryOptions<GetNominalRollStatus200, ResponseErrorConfig<GetNominalRollStatus401>, GetNominalRollStatus200>({
   queryKey,
   queryFn: async ({ signal }) => {
      return getNominalRoll({ ...config, signal: config.signal ?? signal, throwOnError: true }).unwrap()
   },
  })
}

/**
 * {@link /NominalRoll}
 */
export function useGetNominalRoll<TData = GetNominalRollStatus200, TQueryData = GetNominalRollStatus200, TQueryKey extends QueryKey = GetNominalRollQueryKey>(options: {
  query?: Partial<UseQueryOptions<GetNominalRollStatus200, ResponseErrorConfig<GetNominalRollStatus401>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? getNominalRollQueryKey()

  const queryResult = useQuery({
   ...getNominalRollQueryOptions(config),
   ...resolvedOptions,
   queryKey
  } as unknown as UseQueryOptions<GetNominalRollStatus200, ResponseErrorConfig<GetNominalRollStatus401>, TData, GetNominalRollStatus200, TQueryKey>, toValue(queryClient)) as UseQueryReturnType<TData, ResponseErrorConfig<GetNominalRollStatus401>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}
