/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetOrgExportOptions, GetOrgExportStatus200, GetOrgExportStatus401, GetOrgExportStatus403 } from '../types/GetOrgExport'
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from '@tanstack/vue-query'
import type { MaybeRefOrGetter } from 'vue'
import { getOrgExport } from '../clients/getOrgExport'
import { queryOptions, useQuery } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const getOrgExportQueryKey = ({ path }: { path: MaybeRefOrGetter<Omit<GetOrgExportOptions, 'headers'>['path']> }) => [{ url: '/t/:slug/Export', params: path }] as const

export type GetOrgExportQueryKey = ReturnType<typeof getOrgExportQueryKey>

export function getOrgExportQueryOptions({ path }: { path: MaybeRefOrGetter<GetOrgExportOptions['path']> }, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getOrgExportQueryKey({ path })
  return queryOptions<GetOrgExportStatus200, ResponseErrorConfig<GetOrgExportStatus401 | GetOrgExportStatus403>, GetOrgExportStatus200>({
   queryKey,
   queryFn: async ({ signal }) => {
      return getOrgExport({ ...config, path: toValue(path), signal: config.signal ?? signal, throwOnError: true }).unwrap()
   },
  })
}

/**
 * {@link /t/:slug/Export}
 */
export function useGetOrgExport<TData = GetOrgExportStatus200, TQueryData = GetOrgExportStatus200, TQueryKey extends QueryKey = GetOrgExportQueryKey>({ path }: { path: MaybeRefOrGetter<GetOrgExportOptions['path']> }, options: {
  query?: Partial<UseQueryOptions<GetOrgExportStatus200, ResponseErrorConfig<GetOrgExportStatus401 | GetOrgExportStatus403>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? getOrgExportQueryKey({ path })

  const queryResult = useQuery({
   ...getOrgExportQueryOptions({ path }, config),
   ...resolvedOptions,
   queryKey
  } as unknown as UseQueryOptions<GetOrgExportStatus200, ResponseErrorConfig<GetOrgExportStatus401 | GetOrgExportStatus403>, TData, GetOrgExportStatus200, TQueryKey>, toValue(queryClient)) as UseQueryReturnType<TData, ResponseErrorConfig<GetOrgExportStatus401 | GetOrgExportStatus403>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}
