/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetOrgInvitesOptions, GetOrgInvitesStatus200, GetOrgInvitesStatus401, GetOrgInvitesStatus403 } from '../types/GetOrgInvites'
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from '@tanstack/vue-query'
import type { MaybeRefOrGetter } from 'vue'
import { getOrgInvites } from '../clients/getOrgInvites'
import { queryOptions, useQuery } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const getOrgInvitesQueryKey = ({ path }: { path: MaybeRefOrGetter<Omit<GetOrgInvitesOptions, 'headers'>['path']> }) => [{ url: '/t/:slug/Invites', params: path }] as const

export type GetOrgInvitesQueryKey = ReturnType<typeof getOrgInvitesQueryKey>

export function getOrgInvitesQueryOptions({ path }: { path: MaybeRefOrGetter<GetOrgInvitesOptions['path']> }, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getOrgInvitesQueryKey({ path })
  return queryOptions<GetOrgInvitesStatus200, ResponseErrorConfig<GetOrgInvitesStatus401 | GetOrgInvitesStatus403>, GetOrgInvitesStatus200>({
   queryKey,
   queryFn: async ({ signal }) => {
      return getOrgInvites({ ...config, path: toValue(path), signal: config.signal ?? signal, throwOnError: true }).unwrap()
   },
  })
}

/**
 * {@link /t/:slug/Invites}
 */
export function useGetOrgInvites<TData = GetOrgInvitesStatus200, TQueryData = GetOrgInvitesStatus200, TQueryKey extends QueryKey = GetOrgInvitesQueryKey>({ path }: { path: MaybeRefOrGetter<GetOrgInvitesOptions['path']> }, options: {
  query?: Partial<UseQueryOptions<GetOrgInvitesStatus200, ResponseErrorConfig<GetOrgInvitesStatus401 | GetOrgInvitesStatus403>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? getOrgInvitesQueryKey({ path })

  const queryResult = useQuery({
   ...getOrgInvitesQueryOptions({ path }, config),
   ...resolvedOptions,
   queryKey
  } as unknown as UseQueryOptions<GetOrgInvitesStatus200, ResponseErrorConfig<GetOrgInvitesStatus401 | GetOrgInvitesStatus403>, TData, GetOrgInvitesStatus200, TQueryKey>, toValue(queryClient)) as UseQueryReturnType<TData, ResponseErrorConfig<GetOrgInvitesStatus401 | GetOrgInvitesStatus403>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}
