/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetAdminUsersStatus200 } from '../types/GetAdminUsers'
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from '@tanstack/vue-query'
import { getAdminUsers } from '../clients/getAdminUsers'
import { queryOptions, useQuery } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const getAdminUsersQueryKey = () => [{ url: '/Admin/Users' }] as const

export type GetAdminUsersQueryKey = ReturnType<typeof getAdminUsersQueryKey>

export function getAdminUsersQueryOptions(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getAdminUsersQueryKey()
  return queryOptions<GetAdminUsersStatus200, ResponseErrorConfig<Error>, GetAdminUsersStatus200>({
   queryKey,
   queryFn: async ({ signal }) => {
      return getAdminUsers({ ...config, signal: config.signal ?? signal, throwOnError: true }).unwrap()
   },
  })
}

/**
 * {@link /Admin/Users}
 */
export function useGetAdminUsers<TData = GetAdminUsersStatus200, TQueryData = GetAdminUsersStatus200, TQueryKey extends QueryKey = GetAdminUsersQueryKey>(options: {
  query?: Partial<UseQueryOptions<GetAdminUsersStatus200, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? getAdminUsersQueryKey()

  const queryResult = useQuery({
   ...getAdminUsersQueryOptions(config),
   ...resolvedOptions,
   queryKey
  } as unknown as UseQueryOptions<GetAdminUsersStatus200, ResponseErrorConfig<Error>, TData, GetAdminUsersStatus200, TQueryKey>, toValue(queryClient)) as UseQueryReturnType<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}
