/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetMeTelegramStatus200, GetMeTelegramStatus401, GetMeTelegramStatus403 } from '../types/GetMeTelegram'
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from '@tanstack/vue-query'
import { getMeTelegram } from '../clients/getMeTelegram'
import { queryOptions, useQuery } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const getMeTelegramQueryKey = () => [{ url: '/Me/Telegram' }] as const

export type GetMeTelegramQueryKey = ReturnType<typeof getMeTelegramQueryKey>

export function getMeTelegramQueryOptions(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getMeTelegramQueryKey()
  return queryOptions<GetMeTelegramStatus200, ResponseErrorConfig<GetMeTelegramStatus401 | GetMeTelegramStatus403>, GetMeTelegramStatus200>({
   queryKey,
   queryFn: async ({ signal }) => {
      return getMeTelegram({ ...config, signal: config.signal ?? signal, throwOnError: true }).unwrap()
   },
  })
}

/**
 * {@link /Me/Telegram}
 */
export function useGetMeTelegram<TData = GetMeTelegramStatus200, TQueryData = GetMeTelegramStatus200, TQueryKey extends QueryKey = GetMeTelegramQueryKey>(options: {
  query?: Partial<UseQueryOptions<GetMeTelegramStatus200, ResponseErrorConfig<GetMeTelegramStatus401 | GetMeTelegramStatus403>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? getMeTelegramQueryKey()

  const queryResult = useQuery({
   ...getMeTelegramQueryOptions(config),
   ...resolvedOptions,
   queryKey
  } as unknown as UseQueryOptions<GetMeTelegramStatus200, ResponseErrorConfig<GetMeTelegramStatus401 | GetMeTelegramStatus403>, TData, GetMeTelegramStatus200, TQueryKey>, toValue(queryClient)) as UseQueryReturnType<TData, ResponseErrorConfig<GetMeTelegramStatus401 | GetMeTelegramStatus403>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}
