/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetOrgUnitsOptions, GetOrgUnitsStatus200, GetOrgUnitsStatus401, GetOrgUnitsStatus403 } from '../types/GetOrgUnits'
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from '@tanstack/vue-query'
import type { MaybeRefOrGetter } from 'vue'
import { getOrgUnits } from '../clients/getOrgUnits'
import { queryOptions, useQuery } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const getOrgUnitsQueryKey = ({ path }: { path: MaybeRefOrGetter<Omit<GetOrgUnitsOptions, 'headers'>['path']> }) => [{ url: '/t/:slug/Units', params: path }] as const

export type GetOrgUnitsQueryKey = ReturnType<typeof getOrgUnitsQueryKey>

export function getOrgUnitsQueryOptions({ path }: { path: MaybeRefOrGetter<GetOrgUnitsOptions['path']> }, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getOrgUnitsQueryKey({ path })
  return queryOptions<GetOrgUnitsStatus200, ResponseErrorConfig<GetOrgUnitsStatus401 | GetOrgUnitsStatus403>, GetOrgUnitsStatus200>({
   queryKey,
   queryFn: async ({ signal }) => {
      return getOrgUnits({ ...config, path: toValue(path), signal: config.signal ?? signal, throwOnError: true }).unwrap()
   },
  })
}

/**
 * {@link /t/:slug/Units}
 */
export function useGetOrgUnits<TData = GetOrgUnitsStatus200, TQueryData = GetOrgUnitsStatus200, TQueryKey extends QueryKey = GetOrgUnitsQueryKey>({ path }: { path: MaybeRefOrGetter<GetOrgUnitsOptions['path']> }, options: {
  query?: Partial<UseQueryOptions<GetOrgUnitsStatus200, ResponseErrorConfig<GetOrgUnitsStatus401 | GetOrgUnitsStatus403>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? getOrgUnitsQueryKey({ path })

  const queryResult = useQuery({
   ...getOrgUnitsQueryOptions({ path }, config),
   ...resolvedOptions,
   queryKey
  } as unknown as UseQueryOptions<GetOrgUnitsStatus200, ResponseErrorConfig<GetOrgUnitsStatus401 | GetOrgUnitsStatus403>, TData, GetOrgUnitsStatus200, TQueryKey>, toValue(queryClient)) as UseQueryReturnType<TData, ResponseErrorConfig<GetOrgUnitsStatus401 | GetOrgUnitsStatus403>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}
