/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetFacilityStatus200, GetFacilityStatus401 } from '../types/GetFacility'
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from '@tanstack/vue-query'
import { getFacility } from '../clients/getFacility'
import { queryOptions, useQuery } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const getFacilityQueryKey = () => [{ url: '/Facility' }] as const

export type GetFacilityQueryKey = ReturnType<typeof getFacilityQueryKey>

export function getFacilityQueryOptions(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getFacilityQueryKey()
  return queryOptions<GetFacilityStatus200, ResponseErrorConfig<GetFacilityStatus401>, GetFacilityStatus200>({
   queryKey,
   queryFn: async ({ signal }) => {
      return getFacility({ ...config, signal: config.signal ?? signal, throwOnError: true }).unwrap()
   },
  })
}

/**
 * {@link /Facility}
 */
export function useGetFacility<TData = GetFacilityStatus200, TQueryData = GetFacilityStatus200, TQueryKey extends QueryKey = GetFacilityQueryKey>(options: {
  query?: Partial<UseQueryOptions<GetFacilityStatus200, ResponseErrorConfig<GetFacilityStatus401>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? getFacilityQueryKey()

  const queryResult = useQuery({
   ...getFacilityQueryOptions(config),
   ...resolvedOptions,
   queryKey
  } as unknown as UseQueryOptions<GetFacilityStatus200, ResponseErrorConfig<GetFacilityStatus401>, TData, GetFacilityStatus200, TQueryKey>, toValue(queryClient)) as UseQueryReturnType<TData, ResponseErrorConfig<GetFacilityStatus401>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}
