/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetAuthMeStatus200, GetAuthMeStatus401 } from '../types/GetAuthMe'
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from '@tanstack/vue-query'
import { getAuthMe } from '../clients/getAuthMe'
import { queryOptions, useQuery } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const getAuthMeQueryKey = () => [{ url: '/Auth/Me' }] as const

export type GetAuthMeQueryKey = ReturnType<typeof getAuthMeQueryKey>

export function getAuthMeQueryOptions(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getAuthMeQueryKey()
  return queryOptions<GetAuthMeStatus200, ResponseErrorConfig<GetAuthMeStatus401>, GetAuthMeStatus200>({
   queryKey,
   queryFn: async ({ signal }) => {
      return getAuthMe({ ...config, signal: config.signal ?? signal, throwOnError: true }).unwrap()
   },
  })
}

/**
 * {@link /Auth/Me}
 */
export function useGetAuthMe<TData = GetAuthMeStatus200, TQueryData = GetAuthMeStatus200, TQueryKey extends QueryKey = GetAuthMeQueryKey>(options: {
  query?: Partial<UseQueryOptions<GetAuthMeStatus200, ResponseErrorConfig<GetAuthMeStatus401>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? getAuthMeQueryKey()

  const queryResult = useQuery({
   ...getAuthMeQueryOptions(config),
   ...resolvedOptions,
   queryKey
  } as unknown as UseQueryOptions<GetAuthMeStatus200, ResponseErrorConfig<GetAuthMeStatus401>, TData, GetAuthMeStatus200, TQueryKey>, toValue(queryClient)) as UseQueryReturnType<TData, ResponseErrorConfig<GetAuthMeStatus401>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}
