/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { GetOrgMembersOptions, GetOrgMembersStatus200, GetOrgMembersStatus401, GetOrgMembersStatus403 } from '../types/GetOrgMembers'
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from '@tanstack/vue-query'
import type { MaybeRefOrGetter } from 'vue'
import { getOrgMembers } from '../clients/getOrgMembers'
import { queryOptions, useQuery } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const getOrgMembersQueryKey = ({ path, query }: { path: MaybeRefOrGetter<Omit<GetOrgMembersOptions, 'headers'>['path']>; query: MaybeRefOrGetter<Omit<GetOrgMembersOptions, 'headers'>['query']> }) => [{ url: '/t/:slug/Members', params: path }, ...(query ? [query] : [])] as const

export type GetOrgMembersQueryKey = ReturnType<typeof getOrgMembersQueryKey>

export function getOrgMembersQueryOptions({ path, query }: { path: MaybeRefOrGetter<GetOrgMembersOptions['path']>; query: MaybeRefOrGetter<GetOrgMembersOptions['query']> }, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  const queryKey = getOrgMembersQueryKey({ path, query })
  return queryOptions<GetOrgMembersStatus200, ResponseErrorConfig<GetOrgMembersStatus401 | GetOrgMembersStatus403>, GetOrgMembersStatus200>({
   queryKey,
   queryFn: async ({ signal }) => {
      return getOrgMembers({ ...config, path: toValue(path), query: toValue(query), signal: config.signal ?? signal, throwOnError: true }).unwrap()
   },
  })
}

/**
 * {@link /t/:slug/Members}
 */
export function useGetOrgMembers<TData = GetOrgMembersStatus200, TQueryData = GetOrgMembersStatus200, TQueryKey extends QueryKey = GetOrgMembersQueryKey>({ path, query }: { path: MaybeRefOrGetter<GetOrgMembersOptions['path']>; query: MaybeRefOrGetter<GetOrgMembersOptions['query']> }, options: {
  query?: Partial<UseQueryOptions<GetOrgMembersStatus200, ResponseErrorConfig<GetOrgMembersStatus401 | GetOrgMembersStatus403>, TData, TQueryData, TQueryKey>> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
} = {}) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? getOrgMembersQueryKey({ path, query })

  const queryResult = useQuery({
   ...getOrgMembersQueryOptions({ path, query }, config),
   ...resolvedOptions,
   queryKey
  } as unknown as UseQueryOptions<GetOrgMembersStatus200, ResponseErrorConfig<GetOrgMembersStatus401 | GetOrgMembersStatus403>, TData, GetOrgMembersStatus200, TQueryKey>, toValue(queryClient)) as UseQueryReturnType<TData, ResponseErrorConfig<GetOrgMembersStatus401 | GetOrgMembersStatus403>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}
