/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { PostClaimsBySlugStartOptions, PostClaimsBySlugStartStatus200, PostClaimsBySlugStartStatus401, PostClaimsBySlugStartStatus403 } from '../types/PostClaimsBySlugStart'
import type { MutationObserverOptions, QueryClient } from '@tanstack/vue-query'
import { postClaimsBySlugStart } from '../clients/postClaimsBySlugStart'
import { useMutation } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const postClaimsBySlugStartMutationKey = () => [{ url: '/Claims/:slug/Start' }] as const

/**
 * {@link /Claims/:slug/Start}
 */
export function usePostClaimsBySlugStart<TContext>(options: {
  mutation?: MutationObserverOptions<PostClaimsBySlugStartStatus200, ResponseErrorConfig<PostClaimsBySlugStartStatus401 | PostClaimsBySlugStartStatus403>, PostClaimsBySlugStartOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions?.mutationKey ?? postClaimsBySlugStartMutationKey()

  return useMutation<PostClaimsBySlugStartStatus200, ResponseErrorConfig<PostClaimsBySlugStartStatus401 | PostClaimsBySlugStartStatus403>, PostClaimsBySlugStartOptions, TContext>({
    mutationFn: async({ path }) => {
      return postClaimsBySlugStart({ ...config, path: toValue<PostClaimsBySlugStartOptions['path']>(path), throwOnError: true }).unwrap()
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}
