/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { PostAdminUsersOptions, PostAdminUsersStatus200 } from '../types/PostAdminUsers'
import type { MutationObserverOptions, QueryClient } from '@tanstack/vue-query'
import { postAdminUsers } from '../clients/postAdminUsers'
import { useMutation } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const postAdminUsersMutationKey = () => [{ url: '/Admin/Users/:phone/Admin' }] as const

/**
 * {@link /Admin/Users/:phone/Admin}
 */
export function usePostAdminUsers<TContext>(options: {
  mutation?: MutationObserverOptions<PostAdminUsersStatus200, ResponseErrorConfig<Error>, PostAdminUsersOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions?.mutationKey ?? postAdminUsersMutationKey()

  return useMutation<PostAdminUsersStatus200, ResponseErrorConfig<Error>, PostAdminUsersOptions, TContext>({
    mutationFn: async({ path }) => {
      return postAdminUsers({ ...config, path: toValue<PostAdminUsersOptions['path']>(path), throwOnError: true }).unwrap()
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}
