/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { PostBookingBatchOptions, PostBookingBatchStatus200, PostBookingBatchStatus400, PostBookingBatchStatus401, PostBookingBatchStatus403 } from '../types/PostBookingBatch'
import type { MutationObserverOptions, QueryClient } from '@tanstack/vue-query'
import { postBookingBatch } from '../clients/postBookingBatch'
import { useMutation } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const postBookingBatchMutationKey = () => [{ url: '/Booking/Batch' }] as const

/**
 * {@link /Booking/Batch}
 */
export function usePostBookingBatch<TContext>(options: {
  mutation?: MutationObserverOptions<PostBookingBatchStatus200, ResponseErrorConfig<PostBookingBatchStatus400 | PostBookingBatchStatus401 | PostBookingBatchStatus403>, PostBookingBatchOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions?.mutationKey ?? postBookingBatchMutationKey()

  return useMutation<PostBookingBatchStatus200, ResponseErrorConfig<PostBookingBatchStatus400 | PostBookingBatchStatus401 | PostBookingBatchStatus403>, PostBookingBatchOptions, TContext>({
    mutationFn: async({ body }) => {
      return postBookingBatch({ ...config, body: toValue<PostBookingBatchOptions['body']>(body), throwOnError: true }).unwrap()
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}
