/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { PutOrgSettingsOptions, PutOrgSettingsStatus200, PutOrgSettingsStatus400, PutOrgSettingsStatus401, PutOrgSettingsStatus403 } from '../types/PutOrgSettings'
import type { MutationObserverOptions, QueryClient } from '@tanstack/vue-query'
import { putOrgSettings } from '../clients/putOrgSettings'
import { useMutation } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const putOrgSettingsMutationKey = () => [{ url: '/t/:slug/Settings' }] as const

/**
 * {@link /t/:slug/Settings}
 */
export function usePutOrgSettings<TContext>(options: {
  mutation?: MutationObserverOptions<PutOrgSettingsStatus200, ResponseErrorConfig<PutOrgSettingsStatus400 | PutOrgSettingsStatus401 | PutOrgSettingsStatus403>, PutOrgSettingsOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions?.mutationKey ?? putOrgSettingsMutationKey()

  return useMutation<PutOrgSettingsStatus200, ResponseErrorConfig<PutOrgSettingsStatus400 | PutOrgSettingsStatus401 | PutOrgSettingsStatus403>, PutOrgSettingsOptions, TContext>({
    mutationFn: async({ path, body }) => {
      return putOrgSettings({ ...config, path: toValue<PutOrgSettingsOptions['path']>(path), body: toValue<PutOrgSettingsOptions['body']>(body), throwOnError: true }).unwrap()
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}
