/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { PostOrgUnitsOptions, PostOrgUnitsStatus200, PostOrgUnitsStatus400, PostOrgUnitsStatus401, PostOrgUnitsStatus403 } from '../types/PostOrgUnits'
import type { MutationObserverOptions, QueryClient } from '@tanstack/vue-query'
import { postOrgUnits } from '../clients/postOrgUnits'
import { useMutation } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const postOrgUnitsMutationKey = () => [{ url: '/t/:slug/Units' }] as const

/**
 * {@link /t/:slug/Units}
 */
export function usePostOrgUnits<TContext>(options: {
  mutation?: MutationObserverOptions<PostOrgUnitsStatus200, ResponseErrorConfig<PostOrgUnitsStatus400 | PostOrgUnitsStatus401 | PostOrgUnitsStatus403>, PostOrgUnitsOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions?.mutationKey ?? postOrgUnitsMutationKey()

  return useMutation<PostOrgUnitsStatus200, ResponseErrorConfig<PostOrgUnitsStatus400 | PostOrgUnitsStatus401 | PostOrgUnitsStatus403>, PostOrgUnitsOptions, TContext>({
    mutationFn: async({ path, body }) => {
      return postOrgUnits({ ...config, path: toValue<PostOrgUnitsOptions['path']>(path), body: toValue<PostOrgUnitsOptions['body']>(body), throwOnError: true }).unwrap()
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}
