/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { PutOrgUnitsByIdOptions, PutOrgUnitsByIdStatus200, PutOrgUnitsByIdStatus400, PutOrgUnitsByIdStatus401, PutOrgUnitsByIdStatus403 } from '../types/PutOrgUnitsById'
import type { MutationObserverOptions, QueryClient } from '@tanstack/vue-query'
import { putOrgUnitsById } from '../clients/putOrgUnitsById'
import { useMutation } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const putOrgUnitsByIdMutationKey = () => [{ url: '/t/:slug/Units/:id' }] as const

/**
 * {@link /t/:slug/Units/:id}
 */
export function usePutOrgUnitsById<TContext>(options: {
  mutation?: MutationObserverOptions<PutOrgUnitsByIdStatus200, ResponseErrorConfig<PutOrgUnitsByIdStatus400 | PutOrgUnitsByIdStatus401 | PutOrgUnitsByIdStatus403>, PutOrgUnitsByIdOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions?.mutationKey ?? putOrgUnitsByIdMutationKey()

  return useMutation<PutOrgUnitsByIdStatus200, ResponseErrorConfig<PutOrgUnitsByIdStatus400 | PutOrgUnitsByIdStatus401 | PutOrgUnitsByIdStatus403>, PutOrgUnitsByIdOptions, TContext>({
    mutationFn: async({ path, body }) => {
      return putOrgUnitsById({ ...config, path: toValue<PutOrgUnitsByIdOptions['path']>(path), body: toValue<PutOrgUnitsByIdOptions['body']>(body), throwOnError: true }).unwrap()
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}
