/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { PostOrgMembersOptions, PostOrgMembersStatus200, PostOrgMembersStatus400, PostOrgMembersStatus401, PostOrgMembersStatus403 } from '../types/PostOrgMembers'
import type { MutationObserverOptions, QueryClient } from '@tanstack/vue-query'
import { postOrgMembers } from '../clients/postOrgMembers'
import { useMutation } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const postOrgMembersMutationKey = () => [{ url: '/t/:slug/Members' }] as const

/**
 * {@link /t/:slug/Members}
 */
export function usePostOrgMembers<TContext>(options: {
  mutation?: MutationObserverOptions<PostOrgMembersStatus200, ResponseErrorConfig<PostOrgMembersStatus400 | PostOrgMembersStatus401 | PostOrgMembersStatus403>, PostOrgMembersOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions?.mutationKey ?? postOrgMembersMutationKey()

  return useMutation<PostOrgMembersStatus200, ResponseErrorConfig<PostOrgMembersStatus400 | PostOrgMembersStatus401 | PostOrgMembersStatus403>, PostOrgMembersOptions, TContext>({
    mutationFn: async({ path, body }) => {
      return postOrgMembers({ ...config, path: toValue<PostOrgMembersOptions['path']>(path), body: toValue<PostOrgMembersOptions['body']>(body), throwOnError: true }).unwrap()
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}
