/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { PostOrgFacilitiesOptions, PostOrgFacilitiesStatus200, PostOrgFacilitiesStatus400, PostOrgFacilitiesStatus401, PostOrgFacilitiesStatus403 } from '../types/PostOrgFacilities'
import type { MutationObserverOptions, QueryClient } from '@tanstack/vue-query'
import { postOrgFacilities } from '../clients/postOrgFacilities'
import { useMutation } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const postOrgFacilitiesMutationKey = () => [{ url: '/t/:slug/Facilities' }] as const

/**
 * {@link /t/:slug/Facilities}
 */
export function usePostOrgFacilities<TContext>(options: {
  mutation?: MutationObserverOptions<PostOrgFacilitiesStatus200, ResponseErrorConfig<PostOrgFacilitiesStatus400 | PostOrgFacilitiesStatus401 | PostOrgFacilitiesStatus403>, PostOrgFacilitiesOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions?.mutationKey ?? postOrgFacilitiesMutationKey()

  return useMutation<PostOrgFacilitiesStatus200, ResponseErrorConfig<PostOrgFacilitiesStatus400 | PostOrgFacilitiesStatus401 | PostOrgFacilitiesStatus403>, PostOrgFacilitiesOptions, TContext>({
    mutationFn: async({ path, body }) => {
      return postOrgFacilities({ ...config, path: toValue<PostOrgFacilitiesOptions['path']>(path), body: toValue<PostOrgFacilitiesOptions['body']>(body), throwOnError: true }).unwrap()
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}
