/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { PostTenantsOptions, PostTenantsStatus200, PostTenantsStatus400, PostTenantsStatus401, PostTenantsStatus403 } from '../types/PostTenants'
import type { MutationObserverOptions, QueryClient } from '@tanstack/vue-query'
import { postTenants } from '../clients/postTenants'
import { useMutation } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const postTenantsMutationKey = () => [{ url: '/Tenants' }] as const

/**
 * {@link /Tenants}
 */
export function usePostTenants<TContext>(options: {
  mutation?: MutationObserverOptions<PostTenantsStatus200, ResponseErrorConfig<PostTenantsStatus400 | PostTenantsStatus401 | PostTenantsStatus403>, PostTenantsOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions?.mutationKey ?? postTenantsMutationKey()

  return useMutation<PostTenantsStatus200, ResponseErrorConfig<PostTenantsStatus400 | PostTenantsStatus401 | PostTenantsStatus403>, PostTenantsOptions, TContext>({
    mutationFn: async({ body }) => {
      return postTenants({ ...config, body: toValue<PostTenantsOptions['body']>(body), throwOnError: true }).unwrap()
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}
