/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { PostOrgInvitesOptions, PostOrgInvitesStatus200, PostOrgInvitesStatus400, PostOrgInvitesStatus401, PostOrgInvitesStatus403 } from '../types/PostOrgInvites'
import type { MutationObserverOptions, QueryClient } from '@tanstack/vue-query'
import { postOrgInvites } from '../clients/postOrgInvites'
import { useMutation } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const postOrgInvitesMutationKey = () => [{ url: '/t/:slug/Invites' }] as const

/**
 * {@link /t/:slug/Invites}
 */
export function usePostOrgInvites<TContext>(options: {
  mutation?: MutationObserverOptions<PostOrgInvitesStatus200, ResponseErrorConfig<PostOrgInvitesStatus400 | PostOrgInvitesStatus401 | PostOrgInvitesStatus403>, PostOrgInvitesOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions?.mutationKey ?? postOrgInvitesMutationKey()

  return useMutation<PostOrgInvitesStatus200, ResponseErrorConfig<PostOrgInvitesStatus400 | PostOrgInvitesStatus401 | PostOrgInvitesStatus403>, PostOrgInvitesOptions, TContext>({
    mutationFn: async({ path, body }) => {
      return postOrgInvites({ ...config, path: toValue<PostOrgInvitesOptions['path']>(path), body: toValue<PostOrgInvitesOptions['body']>(body), throwOnError: true }).unwrap()
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}
