/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { PostAuthLoginOptions, PostAuthLoginStatus204, PostAuthLoginStatus400 } from '../types/PostAuthLogin'
import type { MutationObserverOptions, QueryClient } from '@tanstack/vue-query'
import { postAuthLogin } from '../clients/postAuthLogin'
import { useMutation } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const postAuthLoginMutationKey = () => [{ url: '/Auth/Login' }] as const

/**
 * {@link /Auth/Login}
 */
export function usePostAuthLogin<TContext>(options: {
  mutation?: MutationObserverOptions<PostAuthLoginStatus204, ResponseErrorConfig<PostAuthLoginStatus400>, PostAuthLoginOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions?.mutationKey ?? postAuthLoginMutationKey()

  return useMutation<PostAuthLoginStatus204, ResponseErrorConfig<PostAuthLoginStatus400>, PostAuthLoginOptions, TContext>({
    mutationFn: async({ body }) => {
      return postAuthLogin({ ...config, body: toValue<PostAuthLoginOptions['body']>(body), throwOnError: true }).unwrap()
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}
