/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { PostTenantsDeletionOptions, PostTenantsDeletionStatus200, PostTenantsDeletionStatus400, PostTenantsDeletionStatus401, PostTenantsDeletionStatus403 } from '../types/PostTenantsDeletion'
import type { MutationObserverOptions, QueryClient } from '@tanstack/vue-query'
import { postTenantsDeletion } from '../clients/postTenantsDeletion'
import { useMutation } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const postTenantsDeletionMutationKey = () => [{ url: '/Tenants/:slug/Deletion' }] as const

/**
 * {@link /Tenants/:slug/Deletion}
 */
export function usePostTenantsDeletion<TContext>(options: {
  mutation?: MutationObserverOptions<PostTenantsDeletionStatus200, ResponseErrorConfig<PostTenantsDeletionStatus400 | PostTenantsDeletionStatus401 | PostTenantsDeletionStatus403>, PostTenantsDeletionOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions?.mutationKey ?? postTenantsDeletionMutationKey()

  return useMutation<PostTenantsDeletionStatus200, ResponseErrorConfig<PostTenantsDeletionStatus400 | PostTenantsDeletionStatus401 | PostTenantsDeletionStatus403>, PostTenantsDeletionOptions, TContext>({
    mutationFn: async({ path, body }) => {
      return postTenantsDeletion({ ...config, path: toValue<PostTenantsDeletionOptions['path']>(path), body: toValue<PostTenantsDeletionOptions['body']>(body), throwOnError: true }).unwrap()
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}
