/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { PostMeTelegramLinkStatus200, PostMeTelegramLinkStatus401, PostMeTelegramLinkStatus403 } from '../types/PostMeTelegramLink'
import type { MutationObserverOptions, QueryClient } from '@tanstack/vue-query'
import { postMeTelegramLink } from '../clients/postMeTelegramLink'
import { useMutation } from '@tanstack/vue-query'

export const postMeTelegramLinkMutationKey = () => [{ url: '/Me/Telegram/Link' }] as const

/**
 * {@link /Me/Telegram/Link}
 */
export function usePostMeTelegramLink<TContext>(options: {
  mutation?: MutationObserverOptions<PostMeTelegramLinkStatus200, ResponseErrorConfig<PostMeTelegramLinkStatus401 | PostMeTelegramLinkStatus403>, undefined, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions?.mutationKey ?? postMeTelegramLinkMutationKey()

  return useMutation<PostMeTelegramLinkStatus200, ResponseErrorConfig<PostMeTelegramLinkStatus401 | PostMeTelegramLinkStatus403>, undefined, TContext>({
    mutationFn: async() => {
      return postMeTelegramLink({ ...config, throwOnError: true }).unwrap()
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}
