/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { PostInvitesByTokenAcceptOptions, PostInvitesByTokenAcceptStatus200, PostInvitesByTokenAcceptStatus400, PostInvitesByTokenAcceptStatus401, PostInvitesByTokenAcceptStatus403 } from '../types/PostInvitesByTokenAccept'
import type { MutationObserverOptions, QueryClient } from '@tanstack/vue-query'
import { postInvitesByTokenAccept } from '../clients/postInvitesByTokenAccept'
import { useMutation } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const postInvitesByTokenAcceptMutationKey = () => [{ url: '/Invites/:token/Accept' }] as const

/**
 * {@link /Invites/:token/Accept}
 */
export function usePostInvitesByTokenAccept<TContext>(options: {
  mutation?: MutationObserverOptions<PostInvitesByTokenAcceptStatus200, ResponseErrorConfig<PostInvitesByTokenAcceptStatus400 | PostInvitesByTokenAcceptStatus401 | PostInvitesByTokenAcceptStatus403>, PostInvitesByTokenAcceptOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions?.mutationKey ?? postInvitesByTokenAcceptMutationKey()

  return useMutation<PostInvitesByTokenAcceptStatus200, ResponseErrorConfig<PostInvitesByTokenAcceptStatus400 | PostInvitesByTokenAcceptStatus401 | PostInvitesByTokenAcceptStatus403>, PostInvitesByTokenAcceptOptions, TContext>({
    mutationFn: async({ path, body }) => {
      return postInvitesByTokenAccept({ ...config, path: toValue<PostInvitesByTokenAcceptOptions['path']>(path), body: toValue<PostInvitesByTokenAcceptOptions['body']>(body), throwOnError: true }).unwrap()
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}
