/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { PostAuthVerifyOptions, PostAuthVerifyStatus204 } from '../types/PostAuthVerify'
import type { MutationObserverOptions, QueryClient } from '@tanstack/vue-query'
import { postAuthVerify } from '../clients/postAuthVerify'
import { useMutation } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const postAuthVerifyMutationKey = () => [{ url: '/Auth/Verify' }] as const

/**
 * {@link /Auth/Verify}
 */
export function usePostAuthVerify<TContext>(options: {
  mutation?: MutationObserverOptions<PostAuthVerifyStatus204, ResponseErrorConfig<Error>, PostAuthVerifyOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions?.mutationKey ?? postAuthVerifyMutationKey()

  return useMutation<PostAuthVerifyStatus204, ResponseErrorConfig<Error>, PostAuthVerifyOptions, TContext>({
    mutationFn: async({ body }) => {
      return postAuthVerify({ ...config, body: toValue<PostAuthVerifyOptions['body']>(body), throwOnError: true }).unwrap()
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}
