/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { PutOrgBookingsByIdOptions, PutOrgBookingsByIdStatus200, PutOrgBookingsByIdStatus400, PutOrgBookingsByIdStatus401, PutOrgBookingsByIdStatus403 } from '../types/PutOrgBookingsById'
import type { MutationObserverOptions, QueryClient } from '@tanstack/vue-query'
import { putOrgBookingsById } from '../clients/putOrgBookingsById'
import { useMutation } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const putOrgBookingsByIdMutationKey = () => [{ url: '/t/:slug/Bookings/:id' }] as const

/**
 * {@link /t/:slug/Bookings/:id}
 */
export function usePutOrgBookingsById<TContext>(options: {
  mutation?: MutationObserverOptions<PutOrgBookingsByIdStatus200, ResponseErrorConfig<PutOrgBookingsByIdStatus400 | PutOrgBookingsByIdStatus401 | PutOrgBookingsByIdStatus403>, PutOrgBookingsByIdOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions?.mutationKey ?? putOrgBookingsByIdMutationKey()

  return useMutation<PutOrgBookingsByIdStatus200, ResponseErrorConfig<PutOrgBookingsByIdStatus400 | PutOrgBookingsByIdStatus401 | PutOrgBookingsByIdStatus403>, PutOrgBookingsByIdOptions, TContext>({
    mutationFn: async({ path, body }) => {
      return putOrgBookingsById({ ...config, path: toValue<PutOrgBookingsByIdOptions['path']>(path), body: toValue<PutOrgBookingsByIdOptions['body']>(body), throwOnError: true }).unwrap()
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}
