/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { PostOrgBookingsOptions, PostOrgBookingsStatus200, PostOrgBookingsStatus400, PostOrgBookingsStatus401, PostOrgBookingsStatus403 } from '../types/PostOrgBookings'
import type { MutationObserverOptions, QueryClient } from '@tanstack/vue-query'
import { postOrgBookings } from '../clients/postOrgBookings'
import { useMutation } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const postOrgBookingsMutationKey = () => [{ url: '/t/:slug/Bookings' }] as const

/**
 * {@link /t/:slug/Bookings}
 */
export function usePostOrgBookings<TContext>(options: {
  mutation?: MutationObserverOptions<PostOrgBookingsStatus200, ResponseErrorConfig<PostOrgBookingsStatus400 | PostOrgBookingsStatus401 | PostOrgBookingsStatus403>, PostOrgBookingsOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions?.mutationKey ?? postOrgBookingsMutationKey()

  return useMutation<PostOrgBookingsStatus200, ResponseErrorConfig<PostOrgBookingsStatus400 | PostOrgBookingsStatus401 | PostOrgBookingsStatus403>, PostOrgBookingsOptions, TContext>({
    mutationFn: async({ path, body }) => {
      return postOrgBookings({ ...config, path: toValue<PostOrgBookingsOptions['path']>(path), body: toValue<PostOrgBookingsOptions['body']>(body), throwOnError: true }).unwrap()
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}
