/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { PutAdminBookingsOptions, PutAdminBookingsStatus200 } from '../types/PutAdminBookings'
import type { MutationObserverOptions, QueryClient } from '@tanstack/vue-query'
import { putAdminBookings } from '../clients/putAdminBookings'
import { useMutation } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const putAdminBookingsMutationKey = () => [{ url: '/Admin/Bookings/:id' }] as const

/**
 * {@link /Admin/Bookings/:id}
 */
export function usePutAdminBookings<TContext>(options: {
  mutation?: MutationObserverOptions<PutAdminBookingsStatus200, ResponseErrorConfig<Error>, PutAdminBookingsOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions?.mutationKey ?? putAdminBookingsMutationKey()

  return useMutation<PutAdminBookingsStatus200, ResponseErrorConfig<Error>, PutAdminBookingsOptions, TContext>({
    mutationFn: async({ path, body }) => {
      return putAdminBookings({ ...config, path: toValue<PutAdminBookingsOptions['path']>(path), body: toValue<PutAdminBookingsOptions['body']>(body), throwOnError: true }).unwrap()
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}
