/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { PostAuthLogoutStatus204 } from '../types/PostAuthLogout'
import type { MutationObserverOptions, QueryClient } from '@tanstack/vue-query'
import { postAuthLogout } from '../clients/postAuthLogout'
import { useMutation } from '@tanstack/vue-query'

export const postAuthLogoutMutationKey = () => [{ url: '/Auth/Logout' }] as const

/**
 * {@link /Auth/Logout}
 */
export function usePostAuthLogout<TContext>(options: {
  mutation?: MutationObserverOptions<PostAuthLogoutStatus204, ResponseErrorConfig<Error>, undefined, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions?.mutationKey ?? postAuthLogoutMutationKey()

  return useMutation<PostAuthLogoutStatus204, ResponseErrorConfig<Error>, undefined, TContext>({
    mutationFn: async() => {
      return postAuthLogout({ ...config, throwOnError: true }).unwrap()
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}
