/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { PutOrgMembersByIdOptions, PutOrgMembersByIdStatus200, PutOrgMembersByIdStatus400, PutOrgMembersByIdStatus401, PutOrgMembersByIdStatus403 } from '../types/PutOrgMembersById'
import type { MutationObserverOptions, QueryClient } from '@tanstack/vue-query'
import { putOrgMembersById } from '../clients/putOrgMembersById'
import { useMutation } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const putOrgMembersByIdMutationKey = () => [{ url: '/t/:slug/Members/:id' }] as const

/**
 * {@link /t/:slug/Members/:id}
 */
export function usePutOrgMembersById<TContext>(options: {
  mutation?: MutationObserverOptions<PutOrgMembersByIdStatus200, ResponseErrorConfig<PutOrgMembersByIdStatus400 | PutOrgMembersByIdStatus401 | PutOrgMembersByIdStatus403>, PutOrgMembersByIdOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions?.mutationKey ?? putOrgMembersByIdMutationKey()

  return useMutation<PutOrgMembersByIdStatus200, ResponseErrorConfig<PutOrgMembersByIdStatus400 | PutOrgMembersByIdStatus401 | PutOrgMembersByIdStatus403>, PutOrgMembersByIdOptions, TContext>({
    mutationFn: async({ path, body }) => {
      return putOrgMembersById({ ...config, path: toValue<PutOrgMembersByIdOptions['path']>(path), body: toValue<PutOrgMembersByIdOptions['body']>(body), throwOnError: true }).unwrap()
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}
