/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { PutOrgFacilitiesByIdOptions, PutOrgFacilitiesByIdStatus200, PutOrgFacilitiesByIdStatus400, PutOrgFacilitiesByIdStatus401, PutOrgFacilitiesByIdStatus403 } from '../types/PutOrgFacilitiesById'
import type { MutationObserverOptions, QueryClient } from '@tanstack/vue-query'
import { putOrgFacilitiesById } from '../clients/putOrgFacilitiesById'
import { useMutation } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const putOrgFacilitiesByIdMutationKey = () => [{ url: '/t/:slug/Facilities/:id' }] as const

/**
 * {@link /t/:slug/Facilities/:id}
 */
export function usePutOrgFacilitiesById<TContext>(options: {
  mutation?: MutationObserverOptions<PutOrgFacilitiesByIdStatus200, ResponseErrorConfig<PutOrgFacilitiesByIdStatus400 | PutOrgFacilitiesByIdStatus401 | PutOrgFacilitiesByIdStatus403>, PutOrgFacilitiesByIdOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions?.mutationKey ?? putOrgFacilitiesByIdMutationKey()

  return useMutation<PutOrgFacilitiesByIdStatus200, ResponseErrorConfig<PutOrgFacilitiesByIdStatus400 | PutOrgFacilitiesByIdStatus401 | PutOrgFacilitiesByIdStatus403>, PutOrgFacilitiesByIdOptions, TContext>({
    mutationFn: async({ path, body }) => {
      return putOrgFacilitiesById({ ...config, path: toValue<PutOrgFacilitiesByIdOptions['path']>(path), body: toValue<PutOrgFacilitiesByIdOptions['body']>(body), throwOnError: true }).unwrap()
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}
