/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { PostBookingByIdOptions, PostBookingByIdStatus200, PostBookingByIdStatus400, PostBookingByIdStatus401, PostBookingByIdStatus403 } from '../types/PostBookingById'
import type { MutationObserverOptions, QueryClient } from '@tanstack/vue-query'
import { postBookingById } from '../clients/postBookingById'
import { useMutation } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const postBookingByIdMutationKey = () => [{ url: '/Booking/:id' }] as const

/**
 * {@link /Booking/:id}
 */
export function usePostBookingById<TContext>(options: {
  mutation?: MutationObserverOptions<PostBookingByIdStatus200, ResponseErrorConfig<PostBookingByIdStatus400 | PostBookingByIdStatus401 | PostBookingByIdStatus403>, PostBookingByIdOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions?.mutationKey ?? postBookingByIdMutationKey()

  return useMutation<PostBookingByIdStatus200, ResponseErrorConfig<PostBookingByIdStatus400 | PostBookingByIdStatus401 | PostBookingByIdStatus403>, PostBookingByIdOptions, TContext>({
    mutationFn: async({ path, body }) => {
      return postBookingById({ ...config, path: toValue<PostBookingByIdOptions['path']>(path), body: toValue<PostBookingByIdOptions['body']>(body), throwOnError: true }).unwrap()
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}
