/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig, ResponseErrorConfig } from '../.kubb/client'
import type { PostBookingOptions, PostBookingStatus200, PostBookingStatus400, PostBookingStatus401, PostBookingStatus403 } from '../types/PostBooking'
import type { MutationObserverOptions, QueryClient } from '@tanstack/vue-query'
import { postBooking } from '../clients/postBooking'
import { useMutation } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const postBookingMutationKey = () => [{ url: '/Booking' }] as const

/**
 * {@link /Booking}
 */
export function usePostBooking<TContext>(options: {
  mutation?: MutationObserverOptions<PostBookingStatus200, ResponseErrorConfig<PostBookingStatus400 | PostBookingStatus401 | PostBookingStatus403>, PostBookingOptions, TContext> & { client?: QueryClient },
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions?.mutationKey ?? postBookingMutationKey()

  return useMutation<PostBookingStatus200, ResponseErrorConfig<PostBookingStatus400 | PostBookingStatus401 | PostBookingStatus403>, PostBookingOptions, TContext>({
    mutationFn: async({ body }) => {
      return postBooking({ ...config, body: toValue<PostBookingOptions['body']>(body), throwOnError: true }).unwrap()
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}
