/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFbsWebApiEntitiesNominalRollFromDiscriminatorValue, type FbsWebApiEntitiesNominalRoll } from '../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /NominalRoll
 */
export interface NominalRollRequestBuilder extends BaseRequestBuilder<NominalRollRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FbsWebApiEntitiesNominalRoll[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<FbsWebApiEntitiesNominalRoll[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const NominalRollRequestBuilderUriTemplate = "{+baseurl}/NominalRoll";
/**
 * Metadata for all the requests in the request builder.
 */
export const NominalRollRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: NominalRollRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createFbsWebApiEntitiesNominalRollFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
