packages:
  - Fbs.WebApp
allowBuilds:
  '@parcel/watcher': true
  '@tailwindcss/oxide': true
  better-sqlite3: false
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - vue-demi
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
