/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFbsWebApiEntitiesUserFromDiscriminatorValue, type FbsWebApiEntitiesUser } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Auth/Me
 */
export interface MeRequestBuilder extends BaseRequestBuilder<MeRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FbsWebApiEntitiesUser>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<FbsWebApiEntitiesUser | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const MeRequestBuilderUriTemplate = "{+baseurl}/Auth/Me";
/**
 * Metadata for all the requests in the request builder.
 */
export const MeRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: MeRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createFbsWebApiEntitiesUserFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
