/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { type AdditionalDataHolder, type ApiError, type Parsable, type ParseNode, type SerializationWriter } from '@microsoft/kiota-abstractions';

/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FastEndpointsProblemDetails_Error}
 */
// @ts-ignore
export function createFastEndpointsProblemDetails_ErrorFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFastEndpointsProblemDetails_Error;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FastEndpointsProblemDetails}
 */
// @ts-ignore
export function createFastEndpointsProblemDetailsFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFastEndpointsProblemDetails;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FbsWebApiDtosBookingWithUser}
 */
// @ts-ignore
export function createFbsWebApiDtosBookingWithUserFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFbsWebApiDtosBookingWithUser;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FbsWebApiDtosFacility}
 */
// @ts-ignore
export function createFbsWebApiDtosFacilityFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFbsWebApiDtosFacility;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FbsWebApiDtosTimeSlot}
 */
// @ts-ignore
export function createFbsWebApiDtosTimeSlotFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFbsWebApiDtosTimeSlot;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FbsWebApiEndpointsAuthLoginPostRequest}
 */
// @ts-ignore
export function createFbsWebApiEndpointsAuthLoginPostRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFbsWebApiEndpointsAuthLoginPostRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FbsWebApiEndpointsAuthVerifyPostRequest}
 */
// @ts-ignore
export function createFbsWebApiEndpointsAuthVerifyPostRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFbsWebApiEndpointsAuthVerifyPostRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FbsWebApiEndpointsBookingByIdPostRequest}
 */
// @ts-ignore
export function createFbsWebApiEndpointsBookingByIdPostRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFbsWebApiEndpointsBookingByIdPostRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FbsWebApiEndpointsBookingPostRequest}
 */
// @ts-ignore
export function createFbsWebApiEndpointsBookingPostRequestFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFbsWebApiEndpointsBookingPostRequest;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FbsWebApiEntitiesBooking}
 */
// @ts-ignore
export function createFbsWebApiEntitiesBookingFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFbsWebApiEntitiesBooking;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FbsWebApiEntitiesNominalRoll}
 */
// @ts-ignore
export function createFbsWebApiEntitiesNominalRollFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFbsWebApiEntitiesNominalRoll;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FbsWebApiEntitiesUser}
 */
// @ts-ignore
export function createFbsWebApiEntitiesUserFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFbsWebApiEntitiesUser;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FbsWebApiRepositoryEntity}
 */
// @ts-ignore
export function createFbsWebApiRepositoryEntityFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFbsWebApiRepositoryEntity;
}
/**
 * Creates a new instance of the appropriate class based on discriminator value
 * @param parseNode The parse node to use to read the discriminator value and create the object
 * @returns {FbsWebApiRepositoryEntityOfGuid}
 */
// @ts-ignore
export function createFbsWebApiRepositoryEntityOfGuidFromDiscriminatorValue(parseNode: ParseNode | undefined) : ((instance?: Parsable) => Record<string, (node: ParseNode) => void>) {
    return deserializeIntoFbsWebApiRepositoryEntityOfGuid;
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFastEndpointsProblemDetails(fastEndpointsProblemDetails: Partial<FastEndpointsProblemDetails> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "detail": n => { fastEndpointsProblemDetails.detail = n.getStringValue(); },
        "errors": n => { fastEndpointsProblemDetails.errors = n.getCollectionOfObjectValues<FastEndpointsProblemDetails_Error>(createFastEndpointsProblemDetails_ErrorFromDiscriminatorValue); },
        "instance": n => { fastEndpointsProblemDetails.instance = n.getStringValue() ?? "/api/route"; },
        "status": n => { fastEndpointsProblemDetails.status = n.getNumberValue(); },
        "title": n => { fastEndpointsProblemDetails.title = n.getStringValue() ?? "One or more validation errors occurred."; },
        "traceId": n => { fastEndpointsProblemDetails.traceId = n.getStringValue() ?? "0HMPNHL0JHL76:00000001"; },
        "type": n => { fastEndpointsProblemDetails.type = n.getStringValue() ?? "https://www.rfc-editor.org/rfc/rfc7231#section-6.5.1"; },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFastEndpointsProblemDetails_Error(fastEndpointsProblemDetails_Error: Partial<FastEndpointsProblemDetails_Error> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { fastEndpointsProblemDetails_Error.code = n.getStringValue(); },
        "name": n => { fastEndpointsProblemDetails_Error.name = n.getStringValue() ?? "Error or field name"; },
        "reason": n => { fastEndpointsProblemDetails_Error.reason = n.getStringValue() ?? "Error reason"; },
        "severity": n => { fastEndpointsProblemDetails_Error.severity = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFbsWebApiDtosBookingWithUser(fbsWebApiDtosBookingWithUser: Partial<FbsWebApiDtosBookingWithUser> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "conduct": n => { fbsWebApiDtosBookingWithUser.conduct = n.getStringValue(); },
        "description": n => { fbsWebApiDtosBookingWithUser.description = n.getStringValue(); },
        "endDateTime": n => { fbsWebApiDtosBookingWithUser.endDateTime = n.getDateValue(); },
        "facilityName": n => { fbsWebApiDtosBookingWithUser.facilityName = n.getStringValue(); },
        "id": n => { fbsWebApiDtosBookingWithUser.id = n.getStringValue(); },
        "pocName": n => { fbsWebApiDtosBookingWithUser.pocName = n.getStringValue(); },
        "pocPhone": n => { fbsWebApiDtosBookingWithUser.pocPhone = n.getStringValue(); },
        "startDateTime": n => { fbsWebApiDtosBookingWithUser.startDateTime = n.getDateValue(); },
        "user": n => { fbsWebApiDtosBookingWithUser.user = n.getObjectValue<FbsWebApiEntitiesUser>(createFbsWebApiEntitiesUserFromDiscriminatorValue); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFbsWebApiDtosFacility(fbsWebApiDtosFacility: Partial<FbsWebApiDtosFacility> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "group": n => { fbsWebApiDtosFacility.group = n.getStringValue(); },
        "name": n => { fbsWebApiDtosFacility.name = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFbsWebApiDtosTimeSlot(fbsWebApiDtosTimeSlot: Partial<FbsWebApiDtosTimeSlot> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "booking": n => { fbsWebApiDtosTimeSlot.booking = n.getObjectValue<FbsWebApiDtosBookingWithUser>(createFbsWebApiDtosBookingWithUserFromDiscriminatorValue); },
        "endDateTime": n => { fbsWebApiDtosTimeSlot.endDateTime = n.getDateValue(); },
        "startDateTime": n => { fbsWebApiDtosTimeSlot.startDateTime = n.getDateValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFbsWebApiEndpointsAuthLoginPostRequest(fbsWebApiEndpointsAuthLoginPostRequest: Partial<FbsWebApiEndpointsAuthLoginPostRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "phone": n => { fbsWebApiEndpointsAuthLoginPostRequest.phone = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFbsWebApiEndpointsAuthVerifyPostRequest(fbsWebApiEndpointsAuthVerifyPostRequest: Partial<FbsWebApiEndpointsAuthVerifyPostRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "code": n => { fbsWebApiEndpointsAuthVerifyPostRequest.code = n.getStringValue(); },
        "phone": n => { fbsWebApiEndpointsAuthVerifyPostRequest.phone = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFbsWebApiEndpointsBookingByIdPostRequest(fbsWebApiEndpointsBookingByIdPostRequest: Partial<FbsWebApiEndpointsBookingByIdPostRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "conduct": n => { fbsWebApiEndpointsBookingByIdPostRequest.conduct = n.getStringValue(); },
        "description": n => { fbsWebApiEndpointsBookingByIdPostRequest.description = n.getStringValue(); },
        "pocName": n => { fbsWebApiEndpointsBookingByIdPostRequest.pocName = n.getStringValue(); },
        "pocPhone": n => { fbsWebApiEndpointsBookingByIdPostRequest.pocPhone = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFbsWebApiEndpointsBookingPostRequest(fbsWebApiEndpointsBookingPostRequest: Partial<FbsWebApiEndpointsBookingPostRequest> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "conduct": n => { fbsWebApiEndpointsBookingPostRequest.conduct = n.getStringValue(); },
        "description": n => { fbsWebApiEndpointsBookingPostRequest.description = n.getStringValue(); },
        "endDateTime": n => { fbsWebApiEndpointsBookingPostRequest.endDateTime = n.getDateValue(); },
        "facilityName": n => { fbsWebApiEndpointsBookingPostRequest.facilityName = n.getStringValue(); },
        "pocName": n => { fbsWebApiEndpointsBookingPostRequest.pocName = n.getStringValue(); },
        "pocPhone": n => { fbsWebApiEndpointsBookingPostRequest.pocPhone = n.getStringValue(); },
        "startDateTime": n => { fbsWebApiEndpointsBookingPostRequest.startDateTime = n.getDateValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFbsWebApiEntitiesBooking(fbsWebApiEntitiesBooking: Partial<FbsWebApiEntitiesBooking> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoFbsWebApiRepositoryEntityOfGuid(fbsWebApiEntitiesBooking),
        "conduct": n => { fbsWebApiEntitiesBooking.conduct = n.getStringValue(); },
        "description": n => { fbsWebApiEntitiesBooking.description = n.getStringValue(); },
        "endDateTime": n => { fbsWebApiEntitiesBooking.endDateTime = n.getDateValue(); },
        "facilityName": n => { fbsWebApiEntitiesBooking.facilityName = n.getStringValue(); },
        "pocName": n => { fbsWebApiEntitiesBooking.pocName = n.getStringValue(); },
        "pocPhone": n => { fbsWebApiEntitiesBooking.pocPhone = n.getStringValue(); },
        "startDateTime": n => { fbsWebApiEntitiesBooking.startDateTime = n.getDateValue(); },
        "userPhone": n => { fbsWebApiEntitiesBooking.userPhone = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFbsWebApiEntitiesNominalRoll(fbsWebApiEntitiesNominalRoll: Partial<FbsWebApiEntitiesNominalRoll> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoFbsWebApiRepositoryEntity(fbsWebApiEntitiesNominalRoll),
        "name": n => { fbsWebApiEntitiesNominalRoll.name = n.getStringValue(); },
        "phone": n => { fbsWebApiEntitiesNominalRoll.phone = n.getStringValue(); },
        "unit": n => { fbsWebApiEntitiesNominalRoll.unit = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFbsWebApiEntitiesUser(fbsWebApiEntitiesUser: Partial<FbsWebApiEntitiesUser> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoFbsWebApiRepositoryEntity(fbsWebApiEntitiesUser),
        "name": n => { fbsWebApiEntitiesUser.name = n.getStringValue(); },
        "notificationGroup": n => { fbsWebApiEntitiesUser.notificationGroup = n.getStringValue(); },
        "phone": n => { fbsWebApiEntitiesUser.phone = n.getStringValue(); },
        "telegramChatId": n => { fbsWebApiEntitiesUser.telegramChatId = n.getStringValue(); },
        "unit": n => { fbsWebApiEntitiesUser.unit = n.getStringValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFbsWebApiRepositoryEntity(fbsWebApiRepositoryEntity: Partial<FbsWebApiRepositoryEntity> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        "row": n => { fbsWebApiRepositoryEntity.row = n.getNumberValue(); },
    }
}
/**
 * The deserialization information for the current model
 * @returns {Record<string, (node: ParseNode) => void>}
 */
// @ts-ignore
export function deserializeIntoFbsWebApiRepositoryEntityOfGuid(fbsWebApiRepositoryEntityOfGuid: Partial<FbsWebApiRepositoryEntityOfGuid> | undefined = {}) : Record<string, (node: ParseNode) => void> {
    return {
        ...deserializeIntoFbsWebApiRepositoryEntity(fbsWebApiRepositoryEntityOfGuid),
        "id": n => { fbsWebApiRepositoryEntityOfGuid.id = n.getStringValue(); },
    }
}
/**
 * RFC7807 compatible problem details/ error response class. this can be used by configuring startup like so:app.UseFastEndpoints(c => c.Errors.UseProblemDetails())
 */
export interface FastEndpointsProblemDetails extends ApiError, Parsable {
    /**
     * the details of the error
     */
    detail?: string | null;
    /**
     * The errors property
     */
    errors?: FastEndpointsProblemDetails_Error[] | null;
    /**
     * The instance property
     */
    instance?: string | null;
    /**
     * The status property
     */
    status?: number | null;
    /**
     * The title property
     */
    title?: string | null;
    /**
     * The traceId property
     */
    traceId?: string | null;
    /**
     * The type property
     */
    type?: string | null;
}
/**
 * the error details object
 */
export interface FastEndpointsProblemDetails_Error extends Parsable {
    /**
     * the code of the error
     */
    code?: string | null;
    /**
     * the name of the error or property of the dto that caused the error
     */
    name?: string | null;
    /**
     * the reason for the error
     */
    reason?: string | null;
    /**
     * the severity of the error
     */
    severity?: string | null;
}
export interface FbsWebApiDtosBookingWithUser extends Parsable {
    /**
     * The conduct property
     */
    conduct?: string | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The endDateTime property
     */
    endDateTime?: Date | null;
    /**
     * The facilityName property
     */
    facilityName?: string | null;
    /**
     * The id property
     */
    id?: string | null;
    /**
     * The pocName property
     */
    pocName?: string | null;
    /**
     * The pocPhone property
     */
    pocPhone?: string | null;
    /**
     * The startDateTime property
     */
    startDateTime?: Date | null;
    /**
     * The user property
     */
    user?: FbsWebApiEntitiesUser | null;
}
export interface FbsWebApiDtosFacility extends Parsable {
    /**
     * The group property
     */
    group?: string | null;
    /**
     * The name property
     */
    name?: string | null;
}
export interface FbsWebApiDtosTimeSlot extends Parsable {
    /**
     * The booking property
     */
    booking?: FbsWebApiDtosBookingWithUser | null;
    /**
     * The endDateTime property
     */
    endDateTime?: Date | null;
    /**
     * The startDateTime property
     */
    startDateTime?: Date | null;
}
export interface FbsWebApiEndpointsAuthLoginPostRequest extends Parsable {
    /**
     * The phone property
     */
    phone?: string | null;
}
export interface FbsWebApiEndpointsAuthVerifyPostRequest extends Parsable {
    /**
     * The code property
     */
    code?: string | null;
    /**
     * The phone property
     */
    phone?: string | null;
}
export interface FbsWebApiEndpointsBookingByIdPostRequest extends Parsable {
    /**
     * The conduct property
     */
    conduct?: string | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The pocName property
     */
    pocName?: string | null;
    /**
     * The pocPhone property
     */
    pocPhone?: string | null;
}
export interface FbsWebApiEndpointsBookingPostRequest extends Parsable {
    /**
     * The conduct property
     */
    conduct?: string | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The endDateTime property
     */
    endDateTime?: Date | null;
    /**
     * The facilityName property
     */
    facilityName?: string | null;
    /**
     * The pocName property
     */
    pocName?: string | null;
    /**
     * The pocPhone property
     */
    pocPhone?: string | null;
    /**
     * The startDateTime property
     */
    startDateTime?: Date | null;
}
export interface FbsWebApiEntitiesBooking extends AdditionalDataHolder, FbsWebApiRepositoryEntityOfGuid, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The conduct property
     */
    conduct?: string | null;
    /**
     * The description property
     */
    description?: string | null;
    /**
     * The endDateTime property
     */
    endDateTime?: Date | null;
    /**
     * The facilityName property
     */
    facilityName?: string | null;
    /**
     * The pocName property
     */
    pocName?: string | null;
    /**
     * The pocPhone property
     */
    pocPhone?: string | null;
    /**
     * The startDateTime property
     */
    startDateTime?: Date | null;
    /**
     * The userPhone property
     */
    userPhone?: string | null;
}
export interface FbsWebApiEntitiesNominalRoll extends AdditionalDataHolder, FbsWebApiRepositoryEntity, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The phone property
     */
    phone?: string | null;
    /**
     * The unit property
     */
    unit?: string | null;
}
export interface FbsWebApiEntitiesUser extends AdditionalDataHolder, FbsWebApiRepositoryEntity, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The name property
     */
    name?: string | null;
    /**
     * The notificationGroup property
     */
    notificationGroup?: string | null;
    /**
     * The phone property
     */
    phone?: string | null;
    /**
     * The telegramChatId property
     */
    telegramChatId?: string | null;
    /**
     * The unit property
     */
    unit?: string | null;
}
export interface FbsWebApiRepositoryEntity extends Parsable {
    /**
     * The row property
     */
    row?: number | null;
}
export interface FbsWebApiRepositoryEntityOfGuid extends AdditionalDataHolder, FbsWebApiRepositoryEntity, Parsable {
    /**
     * Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.
     */
    additionalData?: Record<string, unknown>;
    /**
     * The id property
     */
    id?: string | null;
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFastEndpointsProblemDetails(writer: SerializationWriter, fastEndpointsProblemDetails: Partial<FastEndpointsProblemDetails> | undefined | null = {}) : void {
    if (fastEndpointsProblemDetails) {
        writer.writeStringValue("detail", fastEndpointsProblemDetails.detail);
        writer.writeCollectionOfObjectValues<FastEndpointsProblemDetails_Error>("errors", fastEndpointsProblemDetails.errors, serializeFastEndpointsProblemDetails_Error);
        writer.writeStringValue("instance", fastEndpointsProblemDetails.instance ?? "/api/route");
        writer.writeNumberValue("status", fastEndpointsProblemDetails.status);
        writer.writeStringValue("title", fastEndpointsProblemDetails.title ?? "One or more validation errors occurred.");
        writer.writeStringValue("traceId", fastEndpointsProblemDetails.traceId ?? "0HMPNHL0JHL76:00000001");
        writer.writeStringValue("type", fastEndpointsProblemDetails.type ?? "https://www.rfc-editor.org/rfc/rfc7231#section-6.5.1");
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFastEndpointsProblemDetails_Error(writer: SerializationWriter, fastEndpointsProblemDetails_Error: Partial<FastEndpointsProblemDetails_Error> | undefined | null = {}) : void {
    if (fastEndpointsProblemDetails_Error) {
        writer.writeStringValue("code", fastEndpointsProblemDetails_Error.code);
        writer.writeStringValue("name", fastEndpointsProblemDetails_Error.name ?? "Error or field name");
        writer.writeStringValue("reason", fastEndpointsProblemDetails_Error.reason ?? "Error reason");
        writer.writeStringValue("severity", fastEndpointsProblemDetails_Error.severity);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFbsWebApiDtosBookingWithUser(writer: SerializationWriter, fbsWebApiDtosBookingWithUser: Partial<FbsWebApiDtosBookingWithUser> | undefined | null = {}) : void {
    if (fbsWebApiDtosBookingWithUser) {
        writer.writeStringValue("conduct", fbsWebApiDtosBookingWithUser.conduct);
        writer.writeStringValue("description", fbsWebApiDtosBookingWithUser.description);
        writer.writeDateValue("endDateTime", fbsWebApiDtosBookingWithUser.endDateTime);
        writer.writeStringValue("facilityName", fbsWebApiDtosBookingWithUser.facilityName);
        writer.writeStringValue("id", fbsWebApiDtosBookingWithUser.id);
        writer.writeStringValue("pocName", fbsWebApiDtosBookingWithUser.pocName);
        writer.writeStringValue("pocPhone", fbsWebApiDtosBookingWithUser.pocPhone);
        writer.writeDateValue("startDateTime", fbsWebApiDtosBookingWithUser.startDateTime);
        writer.writeObjectValue<FbsWebApiEntitiesUser>("user", fbsWebApiDtosBookingWithUser.user, serializeFbsWebApiEntitiesUser);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFbsWebApiDtosFacility(writer: SerializationWriter, fbsWebApiDtosFacility: Partial<FbsWebApiDtosFacility> | undefined | null = {}) : void {
    if (fbsWebApiDtosFacility) {
        writer.writeStringValue("group", fbsWebApiDtosFacility.group);
        writer.writeStringValue("name", fbsWebApiDtosFacility.name);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFbsWebApiDtosTimeSlot(writer: SerializationWriter, fbsWebApiDtosTimeSlot: Partial<FbsWebApiDtosTimeSlot> | undefined | null = {}) : void {
    if (fbsWebApiDtosTimeSlot) {
        writer.writeObjectValue<FbsWebApiDtosBookingWithUser>("booking", fbsWebApiDtosTimeSlot.booking, serializeFbsWebApiDtosBookingWithUser);
        writer.writeDateValue("endDateTime", fbsWebApiDtosTimeSlot.endDateTime);
        writer.writeDateValue("startDateTime", fbsWebApiDtosTimeSlot.startDateTime);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFbsWebApiEndpointsAuthLoginPostRequest(writer: SerializationWriter, fbsWebApiEndpointsAuthLoginPostRequest: Partial<FbsWebApiEndpointsAuthLoginPostRequest> | undefined | null = {}) : void {
    if (fbsWebApiEndpointsAuthLoginPostRequest) {
        writer.writeStringValue("phone", fbsWebApiEndpointsAuthLoginPostRequest.phone);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFbsWebApiEndpointsAuthVerifyPostRequest(writer: SerializationWriter, fbsWebApiEndpointsAuthVerifyPostRequest: Partial<FbsWebApiEndpointsAuthVerifyPostRequest> | undefined | null = {}) : void {
    if (fbsWebApiEndpointsAuthVerifyPostRequest) {
        writer.writeStringValue("code", fbsWebApiEndpointsAuthVerifyPostRequest.code);
        writer.writeStringValue("phone", fbsWebApiEndpointsAuthVerifyPostRequest.phone);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFbsWebApiEndpointsBookingByIdPostRequest(writer: SerializationWriter, fbsWebApiEndpointsBookingByIdPostRequest: Partial<FbsWebApiEndpointsBookingByIdPostRequest> | undefined | null = {}) : void {
    if (fbsWebApiEndpointsBookingByIdPostRequest) {
        writer.writeStringValue("conduct", fbsWebApiEndpointsBookingByIdPostRequest.conduct);
        writer.writeStringValue("description", fbsWebApiEndpointsBookingByIdPostRequest.description);
        writer.writeStringValue("pocName", fbsWebApiEndpointsBookingByIdPostRequest.pocName);
        writer.writeStringValue("pocPhone", fbsWebApiEndpointsBookingByIdPostRequest.pocPhone);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFbsWebApiEndpointsBookingPostRequest(writer: SerializationWriter, fbsWebApiEndpointsBookingPostRequest: Partial<FbsWebApiEndpointsBookingPostRequest> | undefined | null = {}) : void {
    if (fbsWebApiEndpointsBookingPostRequest) {
        writer.writeStringValue("conduct", fbsWebApiEndpointsBookingPostRequest.conduct);
        writer.writeStringValue("description", fbsWebApiEndpointsBookingPostRequest.description);
        writer.writeDateValue("endDateTime", fbsWebApiEndpointsBookingPostRequest.endDateTime);
        writer.writeStringValue("facilityName", fbsWebApiEndpointsBookingPostRequest.facilityName);
        writer.writeStringValue("pocName", fbsWebApiEndpointsBookingPostRequest.pocName);
        writer.writeStringValue("pocPhone", fbsWebApiEndpointsBookingPostRequest.pocPhone);
        writer.writeDateValue("startDateTime", fbsWebApiEndpointsBookingPostRequest.startDateTime);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFbsWebApiEntitiesBooking(writer: SerializationWriter, fbsWebApiEntitiesBooking: Partial<FbsWebApiEntitiesBooking> | undefined | null = {}) : void {
    if (fbsWebApiEntitiesBooking) {
        serializeFbsWebApiRepositoryEntityOfGuid(writer, fbsWebApiEntitiesBooking)
        writer.writeStringValue("conduct", fbsWebApiEntitiesBooking.conduct);
        writer.writeStringValue("description", fbsWebApiEntitiesBooking.description);
        writer.writeDateValue("endDateTime", fbsWebApiEntitiesBooking.endDateTime);
        writer.writeStringValue("facilityName", fbsWebApiEntitiesBooking.facilityName);
        writer.writeStringValue("pocName", fbsWebApiEntitiesBooking.pocName);
        writer.writeStringValue("pocPhone", fbsWebApiEntitiesBooking.pocPhone);
        writer.writeDateValue("startDateTime", fbsWebApiEntitiesBooking.startDateTime);
        writer.writeStringValue("userPhone", fbsWebApiEntitiesBooking.userPhone);
        writer.writeAdditionalData(fbsWebApiEntitiesBooking.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFbsWebApiEntitiesNominalRoll(writer: SerializationWriter, fbsWebApiEntitiesNominalRoll: Partial<FbsWebApiEntitiesNominalRoll> | undefined | null = {}) : void {
    if (fbsWebApiEntitiesNominalRoll) {
        serializeFbsWebApiRepositoryEntity(writer, fbsWebApiEntitiesNominalRoll)
        writer.writeStringValue("name", fbsWebApiEntitiesNominalRoll.name);
        writer.writeStringValue("phone", fbsWebApiEntitiesNominalRoll.phone);
        writer.writeStringValue("unit", fbsWebApiEntitiesNominalRoll.unit);
        writer.writeAdditionalData(fbsWebApiEntitiesNominalRoll.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFbsWebApiEntitiesUser(writer: SerializationWriter, fbsWebApiEntitiesUser: Partial<FbsWebApiEntitiesUser> | undefined | null = {}) : void {
    if (fbsWebApiEntitiesUser) {
        serializeFbsWebApiRepositoryEntity(writer, fbsWebApiEntitiesUser)
        writer.writeStringValue("name", fbsWebApiEntitiesUser.name);
        writer.writeStringValue("notificationGroup", fbsWebApiEntitiesUser.notificationGroup);
        writer.writeStringValue("phone", fbsWebApiEntitiesUser.phone);
        writer.writeStringValue("telegramChatId", fbsWebApiEntitiesUser.telegramChatId);
        writer.writeStringValue("unit", fbsWebApiEntitiesUser.unit);
        writer.writeAdditionalData(fbsWebApiEntitiesUser.additionalData);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFbsWebApiRepositoryEntity(writer: SerializationWriter, fbsWebApiRepositoryEntity: Partial<FbsWebApiRepositoryEntity> | undefined | null = {}) : void {
    if (fbsWebApiRepositoryEntity) {
        writer.writeNumberValue("row", fbsWebApiRepositoryEntity.row);
    }
}
/**
 * Serializes information the current object
 * @param writer Serialization writer to use to serialize this model
 */
// @ts-ignore
export function serializeFbsWebApiRepositoryEntityOfGuid(writer: SerializationWriter, fbsWebApiRepositoryEntityOfGuid: Partial<FbsWebApiRepositoryEntityOfGuid> | undefined | null = {}) : void {
    if (fbsWebApiRepositoryEntityOfGuid) {
        serializeFbsWebApiRepositoryEntity(writer, fbsWebApiRepositoryEntityOfGuid)
        writer.writeStringValue("id", fbsWebApiRepositoryEntityOfGuid.id);
        writer.writeAdditionalData(fbsWebApiRepositoryEntityOfGuid.additionalData);
    }
}
/* tslint:enable */
/* eslint-enable */
