/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFbsWebApiEntitiesUserFromDiscriminatorValue, type FbsWebApiEntitiesUser } from '../../models/index.js';
// @ts-ignore
import { type WithPhoneItemRequestBuilder, WithPhoneItemRequestBuilderNavigationMetadata } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Admin/Users
 */
export interface UsersRequestBuilder extends BaseRequestBuilder<UsersRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.Admin.Users.item collection
     * @param phone Unique identifier of the item
     * @returns {WithPhoneItemRequestBuilder}
     */
     byPhone(phone: string) : WithPhoneItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FbsWebApiEntitiesUser[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<FbsWebApiEntitiesUser[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const UsersRequestBuilderUriTemplate = "{+baseurl}/Admin/Users";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const UsersRequestBuilderNavigationMetadata: Record<Exclude<keyof UsersRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byPhone: {
        navigationMetadata: WithPhoneItemRequestBuilderNavigationMetadata,
        pathParametersMappings: ["phone"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const UsersRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: UsersRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createFbsWebApiEntitiesUserFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
