/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFastEndpointsProblemDetailsFromDiscriminatorValue, createFbsWebApiEntitiesBookingFromDiscriminatorValue, serializeFbsWebApiEndpointsBookingBatchPostRequest, serializeFbsWebApiEntitiesBooking, type FastEndpointsProblemDetails, type FbsWebApiEndpointsBookingBatchPostRequest, type FbsWebApiEntitiesBooking } from '../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Booking/Batch
 */
export interface BatchRequestBuilder extends BaseRequestBuilder<BatchRequestBuilder> {
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FbsWebApiEntitiesBooking[]>}
     * @throws {FastEndpointsProblemDetails} error when the service returns a 400 status code
     */
     post(body: FbsWebApiEndpointsBookingBatchPostRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<FbsWebApiEntitiesBooking[] | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPostRequestInformation(body: FbsWebApiEndpointsBookingBatchPostRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const BatchRequestBuilderUriTemplate = "{+baseurl}/Booking/Batch";
/**
 * Metadata for all the requests in the request builder.
 */
export const BatchRequestBuilderRequestsMetadata: RequestsMetadata = {
    post: {
        uriTemplate: BatchRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        errorMappings: {
            400: createFastEndpointsProblemDetailsFromDiscriminatorValue as ParsableFactory<Parsable>,
        },
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createFbsWebApiEntitiesBookingFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeFbsWebApiEndpointsBookingBatchPostRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
