/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type DeleteOrgBookingsByIdPath = {
    slug: string;
    /**
     * @description
     * Format: `guid`
     * @type string
    */
    id: string;
};

export type DeleteOrgBookingsByIdStatus204 = unknown;

export type DeleteOrgBookingsByIdStatus401 = unknown;

export type DeleteOrgBookingsByIdStatus403 = unknown;

export type DeleteOrgBookingsByIdOptions = {
    body?: never;
    path: DeleteOrgBookingsByIdPath;
    query?: never;
    headers?: never;
};

export type DeleteOrgBookingsByIdResponses = {
    "204": DeleteOrgBookingsByIdStatus204;
    "401": DeleteOrgBookingsByIdStatus401;
    "403": DeleteOrgBookingsByIdStatus403;
};

/**
 * @description Union of all possible responses
*/
export type DeleteOrgBookingsByIdResponse = (DeleteOrgBookingsByIdStatus204 | DeleteOrgBookingsByIdStatus401 | DeleteOrgBookingsByIdStatus403);
