/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type DeleteMeTelegramStatus204 = unknown;

export type DeleteMeTelegramStatus401 = unknown;

export type DeleteMeTelegramStatus403 = unknown;

export type DeleteMeTelegramOptions = {
    body?: never;
    path?: never;
    query?: never;
    headers?: never;
};

export type DeleteMeTelegramResponses = {
    "204": DeleteMeTelegramStatus204;
    "401": DeleteMeTelegramStatus401;
    "403": DeleteMeTelegramStatus403;
};

/**
 * @description Union of all possible responses
*/
export type DeleteMeTelegramResponse = (DeleteMeTelegramStatus204 | DeleteMeTelegramStatus401 | DeleteMeTelegramStatus403);
