/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type DeleteBookingByIdPath = {
    /**
     * @description
     * Format: `guid`
     * @type string
    */
    id: string;
};

export type DeleteBookingByIdStatus204 = unknown;

export type DeleteBookingByIdStatus401 = unknown;

export type DeleteBookingByIdStatus403 = unknown;

export type DeleteBookingByIdOptions = {
    body?: never;
    path: DeleteBookingByIdPath;
    query?: never;
    headers?: never;
};

export type DeleteBookingByIdResponses = {
    "204": DeleteBookingByIdStatus204;
    "401": DeleteBookingByIdStatus401;
    "403": DeleteBookingByIdStatus403;
};

/**
 * @description Union of all possible responses
*/
export type DeleteBookingByIdResponse = (DeleteBookingByIdStatus204 | DeleteBookingByIdStatus401 | DeleteBookingByIdStatus403);
