/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type DeleteAdminBookingsPath = {
    /**
     * @description
     * Format: `guid`
     * @type string
    */
    id: string;
};

export type DeleteAdminBookingsStatus204 = unknown;

export type DeleteAdminBookingsOptions = {
    body?: never;
    path: DeleteAdminBookingsPath;
    query?: never;
    headers?: never;
};

export type DeleteAdminBookingsResponses = {
    "204": DeleteAdminBookingsStatus204;
};

/**
 * @description Union of all possible responses
*/
export type DeleteAdminBookingsResponse = DeleteAdminBookingsStatus204;
