/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type DeleteOrgInvitesByIdPath = {
    slug: string;
    /**
     * @description
     * Format: `guid`
     * @type string
    */
    id: string;
};

export type DeleteOrgInvitesByIdStatus204 = unknown;

export type DeleteOrgInvitesByIdStatus401 = unknown;

export type DeleteOrgInvitesByIdStatus403 = unknown;

export type DeleteOrgInvitesByIdOptions = {
    body?: never;
    path: DeleteOrgInvitesByIdPath;
    query?: never;
    headers?: never;
};

export type DeleteOrgInvitesByIdResponses = {
    "204": DeleteOrgInvitesByIdStatus204;
    "401": DeleteOrgInvitesByIdStatus401;
    "403": DeleteOrgInvitesByIdStatus403;
};

/**
 * @description Union of all possible responses
*/
export type DeleteOrgInvitesByIdResponse = (DeleteOrgInvitesByIdStatus204 | DeleteOrgInvitesByIdStatus401 | DeleteOrgInvitesByIdStatus403);
