/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type DeleteOrgFacilitiesByIdPath = {
    slug: string;
    /**
     * @description
     * Format: `guid`
     * @type string
    */
    id: string;
};

export type DeleteOrgFacilitiesByIdStatus204 = unknown;

export type DeleteOrgFacilitiesByIdStatus401 = unknown;

export type DeleteOrgFacilitiesByIdStatus403 = unknown;

export type DeleteOrgFacilitiesByIdOptions = {
    body?: never;
    path: DeleteOrgFacilitiesByIdPath;
    query?: never;
    headers?: never;
};

export type DeleteOrgFacilitiesByIdResponses = {
    "204": DeleteOrgFacilitiesByIdStatus204;
    "401": DeleteOrgFacilitiesByIdStatus401;
    "403": DeleteOrgFacilitiesByIdStatus403;
};

/**
 * @description Union of all possible responses
*/
export type DeleteOrgFacilitiesByIdResponse = (DeleteOrgFacilitiesByIdStatus204 | DeleteOrgFacilitiesByIdStatus401 | DeleteOrgFacilitiesByIdStatus403);
