/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type DeleteTenantsDeletionPath = {
    slug: string;
};

export type DeleteTenantsDeletionStatus204 = unknown;

export type DeleteTenantsDeletionStatus401 = unknown;

export type DeleteTenantsDeletionStatus403 = unknown;

export type DeleteTenantsDeletionOptions = {
    body?: never;
    path: DeleteTenantsDeletionPath;
    query?: never;
    headers?: never;
};

export type DeleteTenantsDeletionResponses = {
    "204": DeleteTenantsDeletionStatus204;
    "401": DeleteTenantsDeletionStatus401;
    "403": DeleteTenantsDeletionStatus403;
};

/**
 * @description Union of all possible responses
*/
export type DeleteTenantsDeletionResponse = (DeleteTenantsDeletionStatus204 | DeleteTenantsDeletionStatus401 | DeleteTenantsDeletionStatus403);
