/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type DeleteOrgUnitsByIdPath = {
    slug: string;
    /**
     * @description
     * Format: `guid`
     * @type string
    */
    id: string;
};

export type DeleteOrgUnitsByIdStatus204 = unknown;

export type DeleteOrgUnitsByIdStatus401 = unknown;

export type DeleteOrgUnitsByIdStatus403 = unknown;

export type DeleteOrgUnitsByIdOptions = {
    body?: never;
    path: DeleteOrgUnitsByIdPath;
    query?: never;
    headers?: never;
};

export type DeleteOrgUnitsByIdResponses = {
    "204": DeleteOrgUnitsByIdStatus204;
    "401": DeleteOrgUnitsByIdStatus401;
    "403": DeleteOrgUnitsByIdStatus403;
};

/**
 * @description Union of all possible responses
*/
export type DeleteOrgUnitsByIdResponse = (DeleteOrgUnitsByIdStatus204 | DeleteOrgUnitsByIdStatus401 | DeleteOrgUnitsByIdStatus403);
