/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FastEndpointsProblemDetailsError } from './FastEndpointsProblemDetailsError'

/**
 * @description RFC9457 compatible problem details/ error response class. this can be used by configuring startup like so:\napp.UseFastEndpoints(c => c.Errors.UseProblemDetails())
 * @type object
*/
export type FastEndpointsProblemDetails = {
    /**
     * @default 'https://www.rfc-editor.org/rfc/rfc7231#section-6.5.1'
     * @type string | undefined
    */
    type?: string;
    /**
     * @default 'One or more validation errors occurred.'
     * @type string | undefined
    */
    title?: string;
    /**
     * @description
     * Format: `int32`
     * @default 400
     * @type integer | undefined
    */
    status?: number;
    /**
     * @default '/api/route'
     * @type string | undefined
    */
    instance?: string;
    /**
     * @default '0HMPNHL0JHL76:00000001'
     * @type string | undefined
    */
    traceId?: string;
    /**
     * @description the details of the error
     * @type string | undefined
    */
    detail?: string | null;
    errors?: FastEndpointsProblemDetailsError[];
};
