/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

/**
 * @description the error details object
 * @type object
*/
export type FastEndpointsProblemDetailsError = {
    /**
     * @description the name of the error or property of the dto that caused the error
     * @default 'Error or field name'
     * @type string | undefined
    */
    name?: string;
    /**
     * @description the reason for the error
     * @default 'Error reason'
     * @type string | undefined
    */
    reason?: string;
    /**
     * @description the code of the error
     * @type string | undefined
    */
    code?: string | null;
    /**
     * @description the severity of the error
     * @type string | undefined
    */
    severity?: string | null;
};
