/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEndpointsOrgInvitesInviteResponse } from './FbsWebApiEndpointsOrgInvitesInviteResponse'

export type FbsWebApiEndpointsOrgInvitesPostResponse = (FbsWebApiEndpointsOrgInvitesInviteResponse & {
    token: string;
});
