/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEndpointsOrgFacilitiesFacilityBody } from './FbsWebApiEndpointsOrgFacilitiesFacilityBody'

export type FbsWebApiEndpointsOrgFacilitiesByIdPutRequest = (FbsWebApiEndpointsOrgFacilitiesFacilityBody & object);
