/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type FbsWebApiEndpointsOrgBookingsPostSlot = {
    /**
     * @description
     * Format: `guid`
     * @type string | undefined
    */
    facilityId?: string;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    startDateTime?: Date;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    endDateTime?: Date;
};
