/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEndpointsMeExportGetAccountData } from './FbsWebApiEndpointsMeExportGetAccountData'
import type { FbsWebApiEndpointsMeExportGetBookingData } from './FbsWebApiEndpointsMeExportGetBookingData'
import type { FbsWebApiEndpointsMeExportGetChangeData } from './FbsWebApiEndpointsMeExportGetChangeData'
import type { FbsWebApiEndpointsMeExportGetMembershipData } from './FbsWebApiEndpointsMeExportGetMembershipData'
import type { FbsWebApiEndpointsMeExportGetTelegramData } from './FbsWebApiEndpointsMeExportGetTelegramData'

export type FbsWebApiEndpointsMeExportGetResponse = {
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    generatedAt: Date;
    account: FbsWebApiEndpointsMeExportGetAccountData;
    telegram: FbsWebApiEndpointsMeExportGetTelegramData;
    memberships: FbsWebApiEndpointsMeExportGetMembershipData[];
    bookings: FbsWebApiEndpointsMeExportGetBookingData[];
    othersBookingsTheyChanged: FbsWebApiEndpointsMeExportGetChangeData[];
};
