/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type FbsWebApiEndpointsMeExportGetBookingData = {
    organizationSlug: string;
    /**
     * @description
     * Format: `guid`
     * @type string
    */
    id: string;
    facility?: string | null;
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    start: Date;
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    end: Date;
    conduct: string;
    description?: string | null;
    pocName?: string | null;
    pocPhone?: string | null;
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    madeAt: Date;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    cancelledAt?: Date | null;
};
