/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export const fbsWebApiDataEntitiesTenantStatus = {
    Active: "Active",
    Suspended: "Suspended",
    PendingDeletion: "PendingDeletion"
} as const;

export type FbsWebApiDataEntitiesTenantStatusKey = (typeof fbsWebApiDataEntitiesTenantStatus)[keyof typeof fbsWebApiDataEntitiesTenantStatus];
