/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type FbsWebApiEndpointsOrgBookingsPerson = {
    /**
     * @description
     * Format: `guid`
     * @type string
    */
    memberId: string;
    displayName: string;
    /**
     * @description
     * Format: `guid`
     * @type string | undefined
    */
    unitId?: string | null;
};
