/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type FbsWebApiEndpointsOrgSettingsGetResponse = {
    name: string;
    timeZone: string;
    defaultCountryCode: string;
    /**
     * @description
     * Format: `int32`
     * @type integer
    */
    slotMinutes: number;
    requireApproval: boolean;
    legacyClaimEnabled: boolean;
};
