/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type FbsWebApiEndpointsOrgExportGetAuditData = {
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    at: Date;
    /**
     * @description
     * Format: `guid`
     * @type string | undefined
    */
    actorMemberId?: string | null;
    action: string;
    summary: string;
    targetType?: string | null;
    /**
     * @description
     * Format: `guid`
     * @type string | undefined
    */
    targetId?: string | null;
};
