/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type FbsWebApiEndpointsTenantsPostRequest = {
    name?: string;
    slug?: string;
    timeZone?: string | null;
    /**
     * @pattern ^[0-9]{1,4}$
     * @type string | undefined
    */
    defaultCountryCode?: string | null;
};
