/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEndpointsOrgMembersMemberBody } from './FbsWebApiEndpointsOrgMembersMemberBody'

export type FbsWebApiEndpointsOrgMembersPostRequest = (FbsWebApiEndpointsOrgMembersMemberBody & object);
