/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type FbsWebApiEndpointsTenantsDeletionPostResponse = {
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    deleteAfter?: Date;
};
