/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type FbsWebApiEndpointsOrgExportGetOrganizationData = {
    slug: string;
    name: string;
    timeZone: string;
    defaultCountryCode: string;
    /**
     * @description
     * Format: `int32`
     * @type integer
    */
    slotMinutes: number;
    requireApproval: boolean;
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    createdAt: Date;
};
