/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEndpointsOrgGetMe } from './FbsWebApiEndpointsOrgGetMe'

export type FbsWebApiEndpointsOrgGetResponse = {
    slug: string;
    name: string;
    timeZone: string;
    defaultCountryCode: string;
    /**
     * @description
     * Format: `int32`
     * @type integer
    */
    slotMinutes: number;
    me: FbsWebApiEndpointsOrgGetMe;
};
