/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiDataEntitiesMemberRoleKey } from './FbsWebApiDataEntitiesMemberRole'
import type { FbsWebApiDataEntitiesMemberStatusKey } from './FbsWebApiDataEntitiesMemberStatus'
import type { FbsWebApiDataEntitiesNotificationScopeKey } from './FbsWebApiDataEntitiesNotificationScope'

export type FbsWebApiEndpointsOrgMembersMemberResponse = {
    /**
     * @description
     * Format: `guid`
     * @type string
    */
    id: string;
    displayName: string;
    phone?: string | null;
    /**
     * @description
     * Format: `guid`
     * @type string | undefined
    */
    unitId?: string | null;
    role: FbsWebApiDataEntitiesMemberRoleKey;
    notificationScope: FbsWebApiDataEntitiesNotificationScopeKey;
    status: FbsWebApiDataEntitiesMemberStatusKey;
    hasAccount: boolean;
};
