/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiDataEntitiesMemberRoleKey } from './FbsWebApiDataEntitiesMemberRole'
import type { FbsWebApiDataEntitiesMemberStatusKey } from './FbsWebApiDataEntitiesMemberStatus'

export type FbsWebApiEndpointsMeGetMembership = {
    tenantSlug: string;
    tenantName: string;
    role: FbsWebApiDataEntitiesMemberRoleKey;
    status: FbsWebApiDataEntitiesMemberStatusKey;
    displayName: string;
};
