/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type FbsWebApiEndpointsInvitesByTokenAcceptPostRequest = {
    /**
     * @minLength 0
     * @maxLength 200
     * @type string | undefined
    */
    displayName?: string | null;
};
