/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEntitiesUser } from './FbsWebApiEntitiesUser'

export type FbsWebApiDtosBookingWithUser = {
    /**
     * @description
     * Format: `guid`
     * @type string | undefined
    */
    id?: string;
    facilityName?: string | null;
    conduct?: string | null;
    description?: string | null;
    pocName?: string | null;
    pocPhone?: string | null;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    startDateTime?: Date | null;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    endDateTime?: Date | null;
    user?: FbsWebApiEntitiesUser | null;
};
