/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type FbsWebApiEndpointsOrgExportGetBookingData = {
    /**
     * @description
     * Format: `guid`
     * @type string
    */
    id: string;
    /**
     * @description
     * Format: `guid`
     * @type string
    */
    facilityId: string;
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    start: Date;
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    end: Date;
    conduct: string;
    description?: string | null;
    pocName?: string | null;
    pocPhone?: string | null;
    /**
     * @description
     * Format: `guid`
     * @type string
    */
    bookedByMemberId: string;
    /**
     * @description
     * Format: `guid`
     * @type string | undefined
    */
    updatedByMemberId?: string | null;
    /**
     * @description
     * Format: `guid`
     * @type string | undefined
    */
    unitId?: string | null;
    /**
     * @description
     * Format: `guid`
     * @type string | undefined
    */
    batchId?: string | null;
    /**
     * @description
     * Format: `int32`
     * @type integer
    */
    revision: number;
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    createdAt: Date;
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    updatedAt: Date;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    cancelledAt?: Date | null;
    /**
     * @description
     * Format: `guid`
     * @type string | undefined
    */
    cancelledByMemberId?: string | null;
};
