/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiDataEntitiesMemberRoleKey } from './FbsWebApiDataEntitiesMemberRole'
import type { FbsWebApiDataEntitiesNotificationScopeKey } from './FbsWebApiDataEntitiesNotificationScope'

export type FbsWebApiEndpointsOrgMembersMemberBody = {
    displayName?: string;
    /**
     * @minLength 1
     * @type string
    */
    phone: string;
    /**
     * @description
     * Format: `guid`
     * @type string | undefined
    */
    unitId?: string | null;
    role?: FbsWebApiDataEntitiesMemberRoleKey;
    notificationScope?: FbsWebApiDataEntitiesNotificationScopeKey;
};
