/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEndpointsOrgExportGetAuditData } from './FbsWebApiEndpointsOrgExportGetAuditData'
import type { FbsWebApiEndpointsOrgExportGetBookingData } from './FbsWebApiEndpointsOrgExportGetBookingData'
import type { FbsWebApiEndpointsOrgExportGetFacilityData } from './FbsWebApiEndpointsOrgExportGetFacilityData'
import type { FbsWebApiEndpointsOrgExportGetInviteData } from './FbsWebApiEndpointsOrgExportGetInviteData'
import type { FbsWebApiEndpointsOrgExportGetMemberData } from './FbsWebApiEndpointsOrgExportGetMemberData'
import type { FbsWebApiEndpointsOrgExportGetOrganizationData } from './FbsWebApiEndpointsOrgExportGetOrganizationData'
import type { FbsWebApiEndpointsOrgExportGetUnitData } from './FbsWebApiEndpointsOrgExportGetUnitData'

export type FbsWebApiEndpointsOrgExportGetResponse = {
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    generatedAt: Date;
    organization: FbsWebApiEndpointsOrgExportGetOrganizationData;
    units: FbsWebApiEndpointsOrgExportGetUnitData[];
    facilities: FbsWebApiEndpointsOrgExportGetFacilityData[];
    members: FbsWebApiEndpointsOrgExportGetMemberData[];
    bookings: FbsWebApiEndpointsOrgExportGetBookingData[];
    invites: FbsWebApiEndpointsOrgExportGetInviteData[];
    history: FbsWebApiEndpointsOrgExportGetAuditData[];
};
