/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type FbsWebApiEndpointsAdminBookingsPutRequest = {
    conduct?: string | null;
    description?: string | null;
    pocName?: string | null;
    pocPhone?: string | null;
};
