/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export const fbsWebApiDataEntitiesMemberRole = {
    Member: "Member",
    Admin: "Admin"
} as const;

export type FbsWebApiDataEntitiesMemberRoleKey = (typeof fbsWebApiDataEntitiesMemberRole)[keyof typeof fbsWebApiDataEntitiesMemberRole];
