/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type FbsWebApiRepositoryEntity = {
    /**
     * @description
     * Format: `int32`
     * @type integer | undefined
    */
    row?: number;
};
