/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type FbsWebApiEndpointsOrgAuditGetPerson = {
    /**
     * @description
     * Format: `guid`
     * @type string | undefined
    */
    memberId?: string;
    displayName: string;
};
