/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export const fbsWebApiDataEntitiesNotificationScope = {
    None: "None",
    Unit: "Unit",
    All: "All"
} as const;

export type FbsWebApiDataEntitiesNotificationScopeKey = (typeof fbsWebApiDataEntitiesNotificationScope)[keyof typeof fbsWebApiDataEntitiesNotificationScope];
