/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type FbsWebApiEndpointsMeExportGetChangeData = {
    organizationSlug: string;
    /**
     * @description
     * Format: `guid`
     * @type string
    */
    id: string;
    facility?: string | null;
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    start: Date;
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    end: Date;
    what: string;
};
