/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiRepositoryEntity } from './FbsWebApiRepositoryEntity'

export type FbsWebApiEntitiesUser = (FbsWebApiRepositoryEntity & {
    unit?: string | null;
    name?: string | null;
    phone?: string | null;
    telegramChatId?: string | null;
    notificationGroup?: string | null;
    isAdmin?: boolean;
});
