/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export const fbsWebApiEndpointsOrgInvitesInviteStatus = {
    Active: "Active",
    Expired: "Expired",
    Revoked: "Revoked",
    UsedUp: "UsedUp"
} as const;

export type FbsWebApiEndpointsOrgInvitesInviteStatusKey = (typeof fbsWebApiEndpointsOrgInvitesInviteStatus)[keyof typeof fbsWebApiEndpointsOrgInvitesInviteStatus];
