/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiDataEntitiesMemberRoleKey } from './FbsWebApiDataEntitiesMemberRole'

export type FbsWebApiEndpointsOrgExportGetInviteData = {
    /**
     * @description
     * Format: `guid`
     * @type string
    */
    id: string;
    role: FbsWebApiDataEntitiesMemberRoleKey;
    /**
     * @description
     * Format: `guid`
     * @type string | undefined
    */
    unitId?: string | null;
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    expiresAt: Date;
    /**
     * @description
     * Format: `int32`
     * @type integer
    */
    maxUses: number;
    /**
     * @description
     * Format: `int32`
     * @type integer
    */
    uses: number;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    revokedAt?: Date | null;
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    createdAt: Date;
};
