/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type FbsWebApiEndpointsOrgUnitsUnitResponse = {
    /**
     * @description
     * Format: `guid`
     * @type string
    */
    id: string;
    name: string;
};
