/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiDataEntitiesMemberStatusKey } from './FbsWebApiDataEntitiesMemberStatus'

export type FbsWebApiEndpointsInvitesByTokenAcceptPostResponse = {
    slug: string;
    organizationName: string;
    status: FbsWebApiDataEntitiesMemberStatusKey;
};
