/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiRepositoryEntity } from './FbsWebApiRepositoryEntity'

export type FbsWebApiRepositoryEntityOfGuid = (FbsWebApiRepositoryEntity & {
    /**
     * @description
     * Format: `guid`
     * @type string | undefined
    */
    id?: string;
});
