/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiDataEntitiesMemberRoleKey } from './FbsWebApiDataEntitiesMemberRole'
import type { FbsWebApiDataEntitiesMemberStatusKey } from './FbsWebApiDataEntitiesMemberStatus'
import type { FbsWebApiDataEntitiesTenantStatusKey } from './FbsWebApiDataEntitiesTenantStatus'

export type FbsWebApiEndpointsMeGetMembership = {
    tenantSlug: string;
    tenantName: string;
    role: FbsWebApiDataEntitiesMemberRoleKey;
    status: FbsWebApiDataEntitiesMemberStatusKey;
    displayName: string;
    tenantStatus: FbsWebApiDataEntitiesTenantStatusKey;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    deleteAfter?: Date | null;
};
