/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type FbsWebApiEndpointsOrgSettingsPutRequest = {
    name?: string;
    timeZone?: string;
    /**
     * @pattern ^[0-9]{1,4}$
     * @type string | undefined
    */
    defaultCountryCode?: string;
    /**
     * @description
     * Format: `int32`
     * @type integer | undefined
    */
    slotMinutes?: number;
    requireApproval?: boolean;
    legacyClaimEnabled?: boolean | null;
};
