/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type FbsWebApiEndpointsMeExportGetAccountData = {
    /**
     * @description
     * Format: `guid`
     * @type string
    */
    id: string;
    name?: string | null;
    email?: string | null;
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    createdAt: Date;
};
