/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type FbsWebApiEndpointsMeTelegramGetResponse = {
    linked: boolean;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    linkedAt?: Date | null;
};
