/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export const fbsWebApiDataEntitiesMemberStatus = {
    Active: "Active",
    Pending: "Pending",
    Unclaimed: "Unclaimed",
    Removed: "Removed"
} as const;

export type FbsWebApiDataEntitiesMemberStatusKey = (typeof fbsWebApiDataEntitiesMemberStatus)[keyof typeof fbsWebApiDataEntitiesMemberStatus];
