/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEndpointsMeGetMembership } from './FbsWebApiEndpointsMeGetMembership'

export type FbsWebApiEndpointsMeGetResponse = {
    /**
     * @description
     * Format: `guid`
     * @type string
    */
    id: string;
    name?: string | null;
    email?: string | null;
    memberships: FbsWebApiEndpointsMeGetMembership[];
};
