/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEndpointsOrgBookingsPostSlot } from './FbsWebApiEndpointsOrgBookingsPostSlot'

export type FbsWebApiEndpointsOrgBookingsPostRequest = {
    /**
     * @minLength 0
     * @maxLength 100
     * @type string
    */
    conduct: string;
    /**
     * @minLength 0
     * @maxLength 2000
     * @type string | undefined
    */
    description?: string | null;
    /**
     * @minLength 0
     * @maxLength 200
     * @type string | undefined
    */
    pocName?: string | null;
    /**
     * @minLength 0
     * @maxLength 32
     * @type string | undefined
    */
    pocPhone?: string | null;
    slots: FbsWebApiEndpointsOrgBookingsPostSlot[];
};
