/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export const fbsWebApiEndpointsOrgMembersByIdPutMembershipState = {
    In: "In",
    Removed: "Removed"
} as const;

export type FbsWebApiEndpointsOrgMembersByIdPutMembershipStateKey = (typeof fbsWebApiEndpointsOrgMembersByIdPutMembershipState)[keyof typeof fbsWebApiEndpointsOrgMembersByIdPutMembershipState];
