/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type FbsWebApiEndpointsOrgFacilitiesBookableGetResponse = {
    /**
     * @description
     * Format: `guid`
     * @type string
    */
    id: string;
    name: string;
    group?: string | null;
};
