/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiRepositoryEntityOfGuid } from './FbsWebApiRepositoryEntityOfGuid'

export type FbsWebApiEntitiesBooking = (FbsWebApiRepositoryEntityOfGuid & {
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    startDateTime?: Date | null;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    endDateTime?: Date | null;
    conduct?: string | null;
    description?: string | null;
    pocName?: string | null;
    pocPhone?: string | null;
    facilityName?: string | null;
    userPhone?: string | null;
});
