/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEndpointsOrgMembersByIdPutMembershipStateKey } from './FbsWebApiEndpointsOrgMembersByIdPutMembershipState'
import type { FbsWebApiEndpointsOrgMembersMemberBody } from './FbsWebApiEndpointsOrgMembersMemberBody'

export type FbsWebApiEndpointsOrgMembersByIdPutRequest = (FbsWebApiEndpointsOrgMembersMemberBody & {
    membership?: FbsWebApiEndpointsOrgMembersByIdPutMembershipStateKey;
});
