/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiDataEntitiesMemberRoleKey } from './FbsWebApiDataEntitiesMemberRole'
import type { FbsWebApiDataEntitiesNotificationScopeKey } from './FbsWebApiDataEntitiesNotificationScope'

export type FbsWebApiEndpointsOrgGetMe = {
    /**
     * @description
     * Format: `guid`
     * @type string
    */
    memberId: string;
    displayName: string;
    role: FbsWebApiDataEntitiesMemberRoleKey;
    notificationScope: FbsWebApiDataEntitiesNotificationScopeKey;
    phone?: string | null;
};
