/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type FbsWebApiEndpointsClaimsBySlugStartPostResponse = {
    url: string;
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    expiresAt: Date;
};
