/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEndpointsOrgBookingsPerson } from './FbsWebApiEndpointsOrgBookingsPerson'

export type FbsWebApiEndpointsOrgBookingsBookingResponse = {
    /**
     * @description
     * Format: `guid`
     * @type string
    */
    id: string;
    /**
     * @description
     * Format: `guid`
     * @type string
    */
    facilityId: string;
    facilityName?: string | null;
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    startDateTime: Date;
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    endDateTime: Date;
    conduct: string;
    description?: string | null;
    pocName?: string | null;
    pocPhone?: string | null;
    bookedBy: FbsWebApiEndpointsOrgBookingsPerson;
    updatedBy?: FbsWebApiEndpointsOrgBookingsPerson | null;
    canManage: boolean;
};
