/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiDtosBookingSlot } from './FbsWebApiDtosBookingSlot'

export type FbsWebApiEndpointsBookingBatchPostRequest = {
    /**
     * @minLength 0
     * @maxLength 100
     * @type string
    */
    conduct: string;
    description?: string | null;
    pocName?: string | null;
    pocPhone?: string | null;
    slots: FbsWebApiDtosBookingSlot[];
};
