/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type FbsWebApiEndpointsOrgFacilitiesFacilityBody = {
    name?: string;
    group?: string | null;
    availableToAll?: boolean;
    unitIds?: string[];
};
