/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiDataEntitiesMemberRoleKey } from './FbsWebApiDataEntitiesMemberRole'
import type { FbsWebApiDataEntitiesMemberStatusKey } from './FbsWebApiDataEntitiesMemberStatus'
import type { FbsWebApiDataEntitiesNotificationScopeKey } from './FbsWebApiDataEntitiesNotificationScope'

export type FbsWebApiEndpointsMeExportGetMembershipData = {
    organizationSlug: string;
    organizationName: string;
    /**
     * @description
     * Format: `guid`
     * @type string
    */
    memberId: string;
    displayName: string;
    phone?: string | null;
    unit?: string | null;
    role: FbsWebApiDataEntitiesMemberRoleKey;
    status: FbsWebApiDataEntitiesMemberStatusKey;
    notificationScope: FbsWebApiDataEntitiesNotificationScopeKey;
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    joinedAt: Date;
};
