/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type FbsWebApiDtosBookingSlot = {
    facilityName?: string | null;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    startDateTime?: Date;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    endDateTime?: Date;
};
