/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiDataEntitiesMemberRoleKey } from './FbsWebApiDataEntitiesMemberRole'

export type FbsWebApiEndpointsOrgInvitesPostRequest = {
    role?: FbsWebApiDataEntitiesMemberRoleKey;
    /**
     * @description
     * Format: `guid`
     * @type string | undefined
    */
    unitId?: string | null;
    /**
     * @description
     * Format: `int32`
     * @type integer | undefined
    */
    expiresInDays?: number;
    /**
     * @description
     * Format: `int32`
     * @type integer | undefined
    */
    maxUses?: number;
};
