/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type FbsWebApiEndpointsOrgBookingsByIdPutRequest = {
    /**
     * @minLength 0
     * @maxLength 100
     * @type string
    */
    conduct: string;
    /**
     * @minLength 0
     * @maxLength 2000
     * @type string | undefined
    */
    description?: string | null;
    /**
     * @minLength 0
     * @maxLength 200
     * @type string | undefined
    */
    pocName?: string | null;
    /**
     * @minLength 0
     * @maxLength 32
     * @type string | undefined
    */
    pocPhone?: string | null;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    startDateTime?: Date | null;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    endDateTime?: Date | null;
};
