/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEndpointsOrgAuditGetPerson } from './FbsWebApiEndpointsOrgAuditGetPerson'

export type FbsWebApiEndpointsOrgAuditGetResponse = {
    /**
     * @description
     * Format: `guid`
     * @type string | undefined
    */
    id?: string;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    at?: Date;
    actor?: FbsWebApiEndpointsOrgAuditGetPerson | null;
    action: string;
    summary: string;
    targetType?: string | null;
    /**
     * @description
     * Format: `guid`
     * @type string | undefined
    */
    targetId?: string | null;
    target?: FbsWebApiEndpointsOrgAuditGetPerson | null;
};
