/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiRepositoryEntity } from './FbsWebApiRepositoryEntity'

export type FbsWebApiEntitiesNominalRoll = (FbsWebApiRepositoryEntity & {
    name?: string | null;
    unit?: string | null;
    phone?: string | null;
});
