/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiDtosBookingWithUser } from './FbsWebApiDtosBookingWithUser'

export type FbsWebApiDtosTimeSlot = {
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    startDateTime?: Date;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    endDateTime?: Date;
    booking?: FbsWebApiDtosBookingWithUser | null;
};
