/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEntitiesUser } from './FbsWebApiEntitiesUser'

export type GetAuthMeStatus200 = FbsWebApiEntitiesUser;

export type GetAuthMeStatus401 = unknown;

export type GetAuthMeOptions = {
    body?: never;
    path?: never;
    query?: never;
    headers?: never;
};

export type GetAuthMeResponses = {
    "200": GetAuthMeStatus200;
    "401": GetAuthMeStatus401;
};

/**
 * @description Union of all possible responses
*/
export type GetAuthMeResponse = (GetAuthMeStatus200 | GetAuthMeStatus401);
