/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEntitiesUser } from './FbsWebApiEntitiesUser'

export type GetAdminUsersStatus200 = FbsWebApiEntitiesUser[];

export type GetAdminUsersOptions = {
    body?: never;
    path?: never;
    query?: never;
    headers?: never;
};

export type GetAdminUsersResponses = {
    "200": GetAdminUsersStatus200;
};

/**
 * @description Union of all possible responses
*/
export type GetAdminUsersResponse = GetAdminUsersStatus200;
