/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiDtosBookingWithUser } from './FbsWebApiDtosBookingWithUser'

export type GetAdminBookingsStatus200 = FbsWebApiDtosBookingWithUser[];

export type GetAdminBookingsOptions = {
    body?: never;
    path?: never;
    query?: never;
    headers?: never;
};

export type GetAdminBookingsResponses = {
    "200": GetAdminBookingsStatus200;
};

/**
 * @description Union of all possible responses
*/
export type GetAdminBookingsResponse = GetAdminBookingsStatus200;
