/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiDtosBookingWithUser } from './FbsWebApiDtosBookingWithUser'

export type GetAdminBookingsByIdPath = {
    /**
     * @description
     * Format: `guid`
     * @type string
    */
    id: string;
};

export type GetAdminBookingsByIdStatus200 = FbsWebApiDtosBookingWithUser;

export type GetAdminBookingsByIdOptions = {
    body?: never;
    path: GetAdminBookingsByIdPath;
    query?: never;
    headers?: never;
};

export type GetAdminBookingsByIdResponses = {
    "200": GetAdminBookingsByIdStatus200;
};

/**
 * @description Union of all possible responses
*/
export type GetAdminBookingsByIdResponse = GetAdminBookingsByIdStatus200;
