/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiDtosBookingWithUser } from './FbsWebApiDtosBookingWithUser'

export type GetBookingByIdPath = {
    /**
     * @description
     * Format: `guid`
     * @type string
    */
    id: string;
};

export type GetBookingByIdStatus200 = FbsWebApiDtosBookingWithUser;

export type GetBookingByIdStatus401 = unknown;

export type GetBookingByIdOptions = {
    body?: never;
    path: GetBookingByIdPath;
    query?: never;
    headers?: never;
};

export type GetBookingByIdResponses = {
    "200": GetBookingByIdStatus200;
    "401": GetBookingByIdStatus401;
};

/**
 * @description Union of all possible responses
*/
export type GetBookingByIdResponse = (GetBookingByIdStatus200 | GetBookingByIdStatus401);
