/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiDtosBookingWithUser } from './FbsWebApiDtosBookingWithUser'

export type GetBookingStatus200 = FbsWebApiDtosBookingWithUser[];

export type GetBookingStatus401 = unknown;

export type GetBookingOptions = {
    body?: never;
    path?: never;
    query?: never;
    headers?: never;
};

export type GetBookingResponses = {
    "200": GetBookingStatus200;
    "401": GetBookingStatus401;
};

/**
 * @description Union of all possible responses
*/
export type GetBookingResponse = (GetBookingStatus200 | GetBookingStatus401);
