/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type GetCachePurgeStatus204 = unknown;

export type GetCachePurgeOptions = {
    body?: never;
    path?: never;
    query?: never;
    headers?: never;
};

export type GetCachePurgeResponses = {
    "204": GetCachePurgeStatus204;
};

/**
 * @description Union of all possible responses
*/
export type GetCachePurgeResponse = GetCachePurgeStatus204;
