/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type GetCachePurgeStatus204 = unknown;

export type GetCachePurgeStatus401 = unknown;

export type GetCachePurgeStatus403 = unknown;

export type GetCachePurgeOptions = {
    body?: never;
    path?: never;
    query?: never;
    headers?: never;
};

export type GetCachePurgeResponses = {
    "204": GetCachePurgeStatus204;
    "401": GetCachePurgeStatus401;
    "403": GetCachePurgeStatus403;
};

/**
 * @description Union of all possible responses
*/
export type GetCachePurgeResponse = (GetCachePurgeStatus204 | GetCachePurgeStatus401 | GetCachePurgeStatus403);
