/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEndpointsClaimsBySlugGetResponse } from './FbsWebApiEndpointsClaimsBySlugGetResponse'

export type GetClaimsBySlugPath = {
    slug: string;
};

export type GetClaimsBySlugStatus200 = FbsWebApiEndpointsClaimsBySlugGetResponse;

export type GetClaimsBySlugStatus401 = unknown;

export type GetClaimsBySlugStatus403 = unknown;

export type GetClaimsBySlugOptions = {
    body?: never;
    path: GetClaimsBySlugPath;
    query?: never;
    headers?: never;
};

export type GetClaimsBySlugResponses = {
    "200": GetClaimsBySlugStatus200;
    "401": GetClaimsBySlugStatus401;
    "403": GetClaimsBySlugStatus403;
};

/**
 * @description Union of all possible responses
*/
export type GetClaimsBySlugResponse = (GetClaimsBySlugStatus200 | GetClaimsBySlugStatus401 | GetClaimsBySlugStatus403);
