/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiDtosFacility } from './FbsWebApiDtosFacility'

export type GetFacilityStatus200 = FbsWebApiDtosFacility[];

export type GetFacilityStatus401 = unknown;

export type GetFacilityOptions = {
    body?: never;
    path?: never;
    query?: never;
    headers?: never;
};

export type GetFacilityResponses = {
    "200": GetFacilityStatus200;
    "401": GetFacilityStatus401;
};

/**
 * @description Union of all possible responses
*/
export type GetFacilityResponse = (GetFacilityStatus200 | GetFacilityStatus401);
