/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiDtosTimeSlot } from './FbsWebApiDtosTimeSlot'

export type GetFacilityTimeSlotsPath = {
    name: string;
};

export type GetFacilityTimeSlotsQuery = {
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    startTime: Date;
    /**
     * @description
     * Format: `date-time`
     * @type string
    */
    endTime: Date;
};

export type GetFacilityTimeSlotsStatus200 = FbsWebApiDtosTimeSlot[];

export type GetFacilityTimeSlotsStatus401 = unknown;

export type GetFacilityTimeSlotsOptions = {
    body?: never;
    path: GetFacilityTimeSlotsPath;
    query: GetFacilityTimeSlotsQuery;
    headers?: never;
};

export type GetFacilityTimeSlotsResponses = {
    "200": GetFacilityTimeSlotsStatus200;
    "401": GetFacilityTimeSlotsStatus401;
};

/**
 * @description Union of all possible responses
*/
export type GetFacilityTimeSlotsResponse = (GetFacilityTimeSlotsStatus200 | GetFacilityTimeSlotsStatus401);
