/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEndpointsInvitesByTokenGetResponse } from './FbsWebApiEndpointsInvitesByTokenGetResponse'

export type GetInvitesByTokenPath = {
    token: string;
};

export type GetInvitesByTokenStatus200 = FbsWebApiEndpointsInvitesByTokenGetResponse;

export type GetInvitesByTokenStatus401 = unknown;

export type GetInvitesByTokenStatus403 = unknown;

export type GetInvitesByTokenOptions = {
    body?: never;
    path: GetInvitesByTokenPath;
    query?: never;
    headers?: never;
};

export type GetInvitesByTokenResponses = {
    "200": GetInvitesByTokenStatus200;
    "401": GetInvitesByTokenStatus401;
    "403": GetInvitesByTokenStatus403;
};

/**
 * @description Union of all possible responses
*/
export type GetInvitesByTokenResponse = (GetInvitesByTokenStatus200 | GetInvitesByTokenStatus401 | GetInvitesByTokenStatus403);
