/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEndpointsMeExportGetResponse } from './FbsWebApiEndpointsMeExportGetResponse'

export type GetMeExportStatus200 = FbsWebApiEndpointsMeExportGetResponse;

export type GetMeExportStatus401 = unknown;

export type GetMeExportStatus403 = unknown;

export type GetMeExportOptions = {
    body?: never;
    path?: never;
    query?: never;
    headers?: never;
};

export type GetMeExportResponses = {
    "200": GetMeExportStatus200;
    "401": GetMeExportStatus401;
    "403": GetMeExportStatus403;
};

/**
 * @description Union of all possible responses
*/
export type GetMeExportResponse = (GetMeExportStatus200 | GetMeExportStatus401 | GetMeExportStatus403);
