/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEndpointsMeTelegramGetResponse } from './FbsWebApiEndpointsMeTelegramGetResponse'

export type GetMeTelegramStatus200 = FbsWebApiEndpointsMeTelegramGetResponse;

export type GetMeTelegramStatus401 = unknown;

export type GetMeTelegramStatus403 = unknown;

export type GetMeTelegramOptions = {
    body?: never;
    path?: never;
    query?: never;
    headers?: never;
};

export type GetMeTelegramResponses = {
    "200": GetMeTelegramStatus200;
    "401": GetMeTelegramStatus401;
    "403": GetMeTelegramStatus403;
};

/**
 * @description Union of all possible responses
*/
export type GetMeTelegramResponse = (GetMeTelegramStatus200 | GetMeTelegramStatus401 | GetMeTelegramStatus403);
