/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEndpointsMeGetResponse } from './FbsWebApiEndpointsMeGetResponse'

export type GetMeStatus200 = FbsWebApiEndpointsMeGetResponse;

export type GetMeStatus401 = unknown;

export type GetMeStatus403 = unknown;

export type GetMeOptions = {
    body?: never;
    path?: never;
    query?: never;
    headers?: never;
};

export type GetMeResponses = {
    "200": GetMeStatus200;
    "401": GetMeStatus401;
    "403": GetMeStatus403;
};

/**
 * @description Union of all possible responses
*/
export type GetMeResponse = (GetMeStatus200 | GetMeStatus401 | GetMeStatus403);
