/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEntitiesNominalRoll } from './FbsWebApiEntitiesNominalRoll'

export type GetNominalRollStatus200 = FbsWebApiEntitiesNominalRoll[];

export type GetNominalRollStatus401 = unknown;

export type GetNominalRollOptions = {
    body?: never;
    path?: never;
    query?: never;
    headers?: never;
};

export type GetNominalRollResponses = {
    "200": GetNominalRollStatus200;
    "401": GetNominalRollStatus401;
};

/**
 * @description Union of all possible responses
*/
export type GetNominalRollResponse = (GetNominalRollStatus200 | GetNominalRollStatus401);
