/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEndpointsOrgMembersMemberResponse } from './FbsWebApiEndpointsOrgMembersMemberResponse'

export type GetOrgMembersPath = {
    slug: string;
};

export type GetOrgMembersQuery = {
    includeRemoved: boolean;
};

export type GetOrgMembersStatus200 = FbsWebApiEndpointsOrgMembersMemberResponse[];

export type GetOrgMembersStatus401 = unknown;

export type GetOrgMembersStatus403 = unknown;

export type GetOrgMembersOptions = {
    body?: never;
    path: GetOrgMembersPath;
    query: GetOrgMembersQuery;
    headers?: never;
};

export type GetOrgMembersResponses = {
    "200": GetOrgMembersStatus200;
    "401": GetOrgMembersStatus401;
    "403": GetOrgMembersStatus403;
};

/**
 * @description Union of all possible responses
*/
export type GetOrgMembersResponse = (GetOrgMembersStatus200 | GetOrgMembersStatus401 | GetOrgMembersStatus403);
