/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEndpointsOrgUnitsUnitResponse } from './FbsWebApiEndpointsOrgUnitsUnitResponse'

export type GetOrgUnitsPath = {
    slug: string;
};

export type GetOrgUnitsStatus200 = FbsWebApiEndpointsOrgUnitsUnitResponse[];

export type GetOrgUnitsStatus401 = unknown;

export type GetOrgUnitsStatus403 = unknown;

export type GetOrgUnitsOptions = {
    body?: never;
    path: GetOrgUnitsPath;
    query?: never;
    headers?: never;
};

export type GetOrgUnitsResponses = {
    "200": GetOrgUnitsStatus200;
    "401": GetOrgUnitsStatus401;
    "403": GetOrgUnitsStatus403;
};

/**
 * @description Union of all possible responses
*/
export type GetOrgUnitsResponse = (GetOrgUnitsStatus200 | GetOrgUnitsStatus401 | GetOrgUnitsStatus403);
