/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEndpointsOrgFacilitiesBookableGetResponse } from './FbsWebApiEndpointsOrgFacilitiesBookableGetResponse'

export type GetOrgFacilitiesBookablePath = {
    slug: string;
};

export type GetOrgFacilitiesBookableStatus200 = FbsWebApiEndpointsOrgFacilitiesBookableGetResponse[];

export type GetOrgFacilitiesBookableStatus401 = unknown;

export type GetOrgFacilitiesBookableStatus403 = unknown;

export type GetOrgFacilitiesBookableOptions = {
    body?: never;
    path: GetOrgFacilitiesBookablePath;
    query?: never;
    headers?: never;
};

export type GetOrgFacilitiesBookableResponses = {
    "200": GetOrgFacilitiesBookableStatus200;
    "401": GetOrgFacilitiesBookableStatus401;
    "403": GetOrgFacilitiesBookableStatus403;
};

/**
 * @description Union of all possible responses
*/
export type GetOrgFacilitiesBookableResponse = (GetOrgFacilitiesBookableStatus200 | GetOrgFacilitiesBookableStatus401 | GetOrgFacilitiesBookableStatus403);
