/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEndpointsOrgBookingsBookingResponse } from './FbsWebApiEndpointsOrgBookingsBookingResponse'

export type GetOrgBookingsPath = {
    slug: string;
};

export type GetOrgBookingsQuery = {
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    from?: Date | null;
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    to?: Date | null;
    /**
     * @description
     * Format: `guid`
     * @type string | undefined
    */
    facilityId?: string | null;
    /**
     * @description
     * Format: `guid`
     * @type string | undefined
    */
    bookedBy?: string | null;
    mine: boolean;
};

export type GetOrgBookingsStatus200 = FbsWebApiEndpointsOrgBookingsBookingResponse[];

export type GetOrgBookingsStatus401 = unknown;

export type GetOrgBookingsStatus403 = unknown;

export type GetOrgBookingsOptions = {
    body?: never;
    path: GetOrgBookingsPath;
    query: GetOrgBookingsQuery;
    headers?: never;
};

export type GetOrgBookingsResponses = {
    "200": GetOrgBookingsStatus200;
    "401": GetOrgBookingsStatus401;
    "403": GetOrgBookingsStatus403;
};

/**
 * @description Union of all possible responses
*/
export type GetOrgBookingsResponse = (GetOrgBookingsStatus200 | GetOrgBookingsStatus401 | GetOrgBookingsStatus403);
