/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEndpointsOrgFacilitiesFacilityResponse } from './FbsWebApiEndpointsOrgFacilitiesFacilityResponse'

export type GetOrgFacilitiesPath = {
    slug: string;
};

export type GetOrgFacilitiesStatus200 = FbsWebApiEndpointsOrgFacilitiesFacilityResponse[];

export type GetOrgFacilitiesStatus401 = unknown;

export type GetOrgFacilitiesStatus403 = unknown;

export type GetOrgFacilitiesOptions = {
    body?: never;
    path: GetOrgFacilitiesPath;
    query?: never;
    headers?: never;
};

export type GetOrgFacilitiesResponses = {
    "200": GetOrgFacilitiesStatus200;
    "401": GetOrgFacilitiesStatus401;
    "403": GetOrgFacilitiesStatus403;
};

/**
 * @description Union of all possible responses
*/
export type GetOrgFacilitiesResponse = (GetOrgFacilitiesStatus200 | GetOrgFacilitiesStatus401 | GetOrgFacilitiesStatus403);
