/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEndpointsOrgInvitesInviteResponse } from './FbsWebApiEndpointsOrgInvitesInviteResponse'

export type GetOrgInvitesPath = {
    slug: string;
};

export type GetOrgInvitesStatus200 = FbsWebApiEndpointsOrgInvitesInviteResponse[];

export type GetOrgInvitesStatus401 = unknown;

export type GetOrgInvitesStatus403 = unknown;

export type GetOrgInvitesOptions = {
    body?: never;
    path: GetOrgInvitesPath;
    query?: never;
    headers?: never;
};

export type GetOrgInvitesResponses = {
    "200": GetOrgInvitesStatus200;
    "401": GetOrgInvitesStatus401;
    "403": GetOrgInvitesStatus403;
};

/**
 * @description Union of all possible responses
*/
export type GetOrgInvitesResponse = (GetOrgInvitesStatus200 | GetOrgInvitesStatus401 | GetOrgInvitesStatus403);
