/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEndpointsOrgSettingsGetResponse } from './FbsWebApiEndpointsOrgSettingsGetResponse'

export type GetOrgSettingsPath = {
    slug: string;
};

export type GetOrgSettingsStatus200 = FbsWebApiEndpointsOrgSettingsGetResponse;

export type GetOrgSettingsStatus401 = unknown;

export type GetOrgSettingsStatus403 = unknown;

export type GetOrgSettingsOptions = {
    body?: never;
    path: GetOrgSettingsPath;
    query?: never;
    headers?: never;
};

export type GetOrgSettingsResponses = {
    "200": GetOrgSettingsStatus200;
    "401": GetOrgSettingsStatus401;
    "403": GetOrgSettingsStatus403;
};

/**
 * @description Union of all possible responses
*/
export type GetOrgSettingsResponse = (GetOrgSettingsStatus200 | GetOrgSettingsStatus401 | GetOrgSettingsStatus403);
