/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEndpointsOrgBookingsBookingResponse } from './FbsWebApiEndpointsOrgBookingsBookingResponse'

export type GetOrgBookingsByIdPath = {
    slug: string;
    /**
     * @description
     * Format: `guid`
     * @type string
    */
    id: string;
};

export type GetOrgBookingsByIdStatus200 = FbsWebApiEndpointsOrgBookingsBookingResponse;

export type GetOrgBookingsByIdStatus401 = unknown;

export type GetOrgBookingsByIdStatus403 = unknown;

export type GetOrgBookingsByIdOptions = {
    body?: never;
    path: GetOrgBookingsByIdPath;
    query?: never;
    headers?: never;
};

export type GetOrgBookingsByIdResponses = {
    "200": GetOrgBookingsByIdStatus200;
    "401": GetOrgBookingsByIdStatus401;
    "403": GetOrgBookingsByIdStatus403;
};

/**
 * @description Union of all possible responses
*/
export type GetOrgBookingsByIdResponse = (GetOrgBookingsByIdStatus200 | GetOrgBookingsByIdStatus401 | GetOrgBookingsByIdStatus403);
