/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEndpointsOrgAuditGetResponse } from './FbsWebApiEndpointsOrgAuditGetResponse'

export type GetOrgAuditPath = {
    slug: string;
};

export type GetOrgAuditQuery = {
    /**
     * @description
     * Format: `date-time`
     * @type string | undefined
    */
    before?: Date | null;
    /**
     * @description
     * Format: `int32`
     * @type integer | undefined
    */
    limit?: number | null;
};

export type GetOrgAuditStatus200 = FbsWebApiEndpointsOrgAuditGetResponse[];

export type GetOrgAuditStatus401 = unknown;

export type GetOrgAuditStatus403 = unknown;

export type GetOrgAuditOptions = {
    body?: never;
    path: GetOrgAuditPath;
    query?: GetOrgAuditQuery;
    headers?: never;
};

export type GetOrgAuditResponses = {
    "200": GetOrgAuditStatus200;
    "401": GetOrgAuditStatus401;
    "403": GetOrgAuditStatus403;
};

/**
 * @description Union of all possible responses
*/
export type GetOrgAuditResponse = (GetOrgAuditStatus200 | GetOrgAuditStatus401 | GetOrgAuditStatus403);
