/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEndpointsOrgGetResponse } from './FbsWebApiEndpointsOrgGetResponse'

export type GetOrgPath = {
    slug: string;
};

export type GetOrgStatus200 = FbsWebApiEndpointsOrgGetResponse;

export type GetOrgStatus401 = unknown;

export type GetOrgStatus403 = unknown;

export type GetOrgOptions = {
    body?: never;
    path: GetOrgPath;
    query?: never;
    headers?: never;
};

export type GetOrgResponses = {
    "200": GetOrgStatus200;
    "401": GetOrgStatus401;
    "403": GetOrgStatus403;
};

/**
 * @description Union of all possible responses
*/
export type GetOrgResponse = (GetOrgStatus200 | GetOrgStatus401 | GetOrgStatus403);
