/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEndpointsOrgExportGetResponse } from './FbsWebApiEndpointsOrgExportGetResponse'

export type GetOrgExportPath = {
    slug: string;
};

export type GetOrgExportStatus200 = FbsWebApiEndpointsOrgExportGetResponse;

export type GetOrgExportStatus401 = unknown;

export type GetOrgExportStatus403 = unknown;

export type GetOrgExportOptions = {
    body?: never;
    path: GetOrgExportPath;
    query?: never;
    headers?: never;
};

export type GetOrgExportResponses = {
    "200": GetOrgExportStatus200;
    "401": GetOrgExportStatus401;
    "403": GetOrgExportStatus403;
};

/**
 * @description Union of all possible responses
*/
export type GetOrgExportResponse = (GetOrgExportStatus200 | GetOrgExportStatus401 | GetOrgExportStatus403);
