/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FastEndpointsProblemDetails } from './FastEndpointsProblemDetails'
import type { FbsWebApiEndpointsOrgUnitsPostRequest } from './FbsWebApiEndpointsOrgUnitsPostRequest'
import type { FbsWebApiEndpointsOrgUnitsUnitResponse } from './FbsWebApiEndpointsOrgUnitsUnitResponse'

export type PostOrgUnitsPath = {
    slug: string;
};

export type PostOrgUnitsStatus200 = FbsWebApiEndpointsOrgUnitsUnitResponse;

/**
 * @description RFC9457 compatible problem details/ error response class. this can be used by configuring startup like so:\napp.UseFastEndpoints(c => c.Errors.UseProblemDetails())
 * @type object
*/
export type PostOrgUnitsStatus400 = FastEndpointsProblemDetails;

export type PostOrgUnitsStatus401 = unknown;

export type PostOrgUnitsStatus403 = unknown;

export type PostOrgUnitsBody = FbsWebApiEndpointsOrgUnitsPostRequest;

export type PostOrgUnitsOptions = {
    body: PostOrgUnitsBody;
    path: PostOrgUnitsPath;
    query?: never;
    headers?: never;
};

export type PostOrgUnitsResponses = {
    "200": PostOrgUnitsStatus200;
    "400": PostOrgUnitsStatus400;
    "401": PostOrgUnitsStatus401;
    "403": PostOrgUnitsStatus403;
};

/**
 * @description Union of all possible responses
*/
export type PostOrgUnitsResponse = (PostOrgUnitsStatus200 | PostOrgUnitsStatus400 | PostOrgUnitsStatus401 | PostOrgUnitsStatus403);
