/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEndpointsClaimsBySlugStartPostResponse } from './FbsWebApiEndpointsClaimsBySlugStartPostResponse'

export type PostClaimsBySlugStartPath = {
    slug: string;
};

export type PostClaimsBySlugStartStatus200 = FbsWebApiEndpointsClaimsBySlugStartPostResponse;

export type PostClaimsBySlugStartStatus401 = unknown;

export type PostClaimsBySlugStartStatus403 = unknown;

export type PostClaimsBySlugStartOptions = {
    body?: never;
    path: PostClaimsBySlugStartPath;
    query?: never;
    headers?: never;
};

export type PostClaimsBySlugStartResponses = {
    "200": PostClaimsBySlugStartStatus200;
    "401": PostClaimsBySlugStartStatus401;
    "403": PostClaimsBySlugStartStatus403;
};

/**
 * @description Union of all possible responses
*/
export type PostClaimsBySlugStartResponse = (PostClaimsBySlugStartStatus200 | PostClaimsBySlugStartStatus401 | PostClaimsBySlugStartStatus403);
