/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEndpointsMeTelegramLinkPostResponse } from './FbsWebApiEndpointsMeTelegramLinkPostResponse'

export type PostMeTelegramLinkStatus200 = FbsWebApiEndpointsMeTelegramLinkPostResponse;

export type PostMeTelegramLinkStatus401 = unknown;

export type PostMeTelegramLinkStatus403 = unknown;

export type PostMeTelegramLinkOptions = {
    body?: never;
    path?: never;
    query?: never;
    headers?: never;
};

export type PostMeTelegramLinkResponses = {
    "200": PostMeTelegramLinkStatus200;
    "401": PostMeTelegramLinkStatus401;
    "403": PostMeTelegramLinkStatus403;
};

/**
 * @description Union of all possible responses
*/
export type PostMeTelegramLinkResponse = (PostMeTelegramLinkStatus200 | PostMeTelegramLinkStatus401 | PostMeTelegramLinkStatus403);
