/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FastEndpointsProblemDetails } from './FastEndpointsProblemDetails'
import type { FbsWebApiEndpointsOrgBookingsBookingResponse } from './FbsWebApiEndpointsOrgBookingsBookingResponse'
import type { FbsWebApiEndpointsOrgBookingsPostRequest } from './FbsWebApiEndpointsOrgBookingsPostRequest'

export type PostOrgBookingsPath = {
    slug: string;
};

export type PostOrgBookingsStatus200 = FbsWebApiEndpointsOrgBookingsBookingResponse[];

/**
 * @description RFC9457 compatible problem details/ error response class. this can be used by configuring startup like so:\napp.UseFastEndpoints(c => c.Errors.UseProblemDetails())
 * @type object
*/
export type PostOrgBookingsStatus400 = FastEndpointsProblemDetails;

export type PostOrgBookingsStatus401 = unknown;

export type PostOrgBookingsStatus403 = unknown;

export type PostOrgBookingsBody = FbsWebApiEndpointsOrgBookingsPostRequest;

export type PostOrgBookingsOptions = {
    body: PostOrgBookingsBody;
    path: PostOrgBookingsPath;
    query?: never;
    headers?: never;
};

export type PostOrgBookingsResponses = {
    "200": PostOrgBookingsStatus200;
    "400": PostOrgBookingsStatus400;
    "401": PostOrgBookingsStatus401;
    "403": PostOrgBookingsStatus403;
};

/**
 * @description Union of all possible responses
*/
export type PostOrgBookingsResponse = (PostOrgBookingsStatus200 | PostOrgBookingsStatus400 | PostOrgBookingsStatus401 | PostOrgBookingsStatus403);
