/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FastEndpointsProblemDetails } from './FastEndpointsProblemDetails'
import type { FbsWebApiEndpointsBookingByIdPostRequest } from './FbsWebApiEndpointsBookingByIdPostRequest'
import type { FbsWebApiEntitiesBooking } from './FbsWebApiEntitiesBooking'

export type PostBookingByIdPath = {
    /**
     * @description
     * Format: `guid`
     * @type string
    */
    id: string;
};

export type PostBookingByIdStatus200 = FbsWebApiEntitiesBooking;

/**
 * @description RFC9457 compatible problem details/ error response class. this can be used by configuring startup like so:\napp.UseFastEndpoints(c => c.Errors.UseProblemDetails())
 * @type object
*/
export type PostBookingByIdStatus400 = FastEndpointsProblemDetails;

export type PostBookingByIdStatus401 = unknown;

export type PostBookingByIdStatus403 = unknown;

export type PostBookingByIdBody = FbsWebApiEndpointsBookingByIdPostRequest;

export type PostBookingByIdOptions = {
    body: PostBookingByIdBody;
    path: PostBookingByIdPath;
    query?: never;
    headers?: never;
};

export type PostBookingByIdResponses = {
    "200": PostBookingByIdStatus200;
    "400": PostBookingByIdStatus400;
    "401": PostBookingByIdStatus401;
    "403": PostBookingByIdStatus403;
};

/**
 * @description Union of all possible responses
*/
export type PostBookingByIdResponse = (PostBookingByIdStatus200 | PostBookingByIdStatus400 | PostBookingByIdStatus401 | PostBookingByIdStatus403);
