/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FastEndpointsProblemDetails } from './FastEndpointsProblemDetails'
import type { FbsWebApiEndpointsOrgMembersMemberResponse } from './FbsWebApiEndpointsOrgMembersMemberResponse'
import type { FbsWebApiEndpointsOrgMembersPostRequest } from './FbsWebApiEndpointsOrgMembersPostRequest'

export type PostOrgMembersPath = {
    slug: string;
};

export type PostOrgMembersStatus200 = FbsWebApiEndpointsOrgMembersMemberResponse;

/**
 * @description RFC9457 compatible problem details/ error response class. this can be used by configuring startup like so:\napp.UseFastEndpoints(c => c.Errors.UseProblemDetails())
 * @type object
*/
export type PostOrgMembersStatus400 = FastEndpointsProblemDetails;

export type PostOrgMembersStatus401 = unknown;

export type PostOrgMembersStatus403 = unknown;

export type PostOrgMembersBody = FbsWebApiEndpointsOrgMembersPostRequest;

export type PostOrgMembersOptions = {
    body: PostOrgMembersBody;
    path: PostOrgMembersPath;
    query?: never;
    headers?: never;
};

export type PostOrgMembersResponses = {
    "200": PostOrgMembersStatus200;
    "400": PostOrgMembersStatus400;
    "401": PostOrgMembersStatus401;
    "403": PostOrgMembersStatus403;
};

/**
 * @description Union of all possible responses
*/
export type PostOrgMembersResponse = (PostOrgMembersStatus200 | PostOrgMembersStatus400 | PostOrgMembersStatus401 | PostOrgMembersStatus403);
