/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FastEndpointsProblemDetails } from './FastEndpointsProblemDetails'
import type { FbsWebApiEndpointsBookingBatchPostRequest } from './FbsWebApiEndpointsBookingBatchPostRequest'
import type { FbsWebApiEntitiesBooking } from './FbsWebApiEntitiesBooking'

export type PostBookingBatchStatus200 = FbsWebApiEntitiesBooking[];

/**
 * @description RFC9457 compatible problem details/ error response class. this can be used by configuring startup like so:\napp.UseFastEndpoints(c => c.Errors.UseProblemDetails())
 * @type object
*/
export type PostBookingBatchStatus400 = FastEndpointsProblemDetails;

export type PostBookingBatchStatus401 = unknown;

export type PostBookingBatchStatus403 = unknown;

export type PostBookingBatchBody = FbsWebApiEndpointsBookingBatchPostRequest;

export type PostBookingBatchOptions = {
    body: PostBookingBatchBody;
    path?: never;
    query?: never;
    headers?: never;
};

export type PostBookingBatchResponses = {
    "200": PostBookingBatchStatus200;
    "400": PostBookingBatchStatus400;
    "401": PostBookingBatchStatus401;
    "403": PostBookingBatchStatus403;
};

/**
 * @description Union of all possible responses
*/
export type PostBookingBatchResponse = (PostBookingBatchStatus200 | PostBookingBatchStatus400 | PostBookingBatchStatus401 | PostBookingBatchStatus403);
