/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FastEndpointsProblemDetails } from './FastEndpointsProblemDetails'
import type { FbsWebApiEndpointsInvitesByTokenAcceptPostRequest } from './FbsWebApiEndpointsInvitesByTokenAcceptPostRequest'
import type { FbsWebApiEndpointsInvitesByTokenAcceptPostResponse } from './FbsWebApiEndpointsInvitesByTokenAcceptPostResponse'

export type PostInvitesByTokenAcceptPath = {
    token: string;
};

export type PostInvitesByTokenAcceptStatus200 = FbsWebApiEndpointsInvitesByTokenAcceptPostResponse;

/**
 * @description RFC9457 compatible problem details/ error response class. this can be used by configuring startup like so:\napp.UseFastEndpoints(c => c.Errors.UseProblemDetails())
 * @type object
*/
export type PostInvitesByTokenAcceptStatus400 = FastEndpointsProblemDetails;

export type PostInvitesByTokenAcceptStatus401 = unknown;

export type PostInvitesByTokenAcceptStatus403 = unknown;

export type PostInvitesByTokenAcceptBody = FbsWebApiEndpointsInvitesByTokenAcceptPostRequest;

export type PostInvitesByTokenAcceptOptions = {
    body: PostInvitesByTokenAcceptBody;
    path: PostInvitesByTokenAcceptPath;
    query?: never;
    headers?: never;
};

export type PostInvitesByTokenAcceptResponses = {
    "200": PostInvitesByTokenAcceptStatus200;
    "400": PostInvitesByTokenAcceptStatus400;
    "401": PostInvitesByTokenAcceptStatus401;
    "403": PostInvitesByTokenAcceptStatus403;
};

/**
 * @description Union of all possible responses
*/
export type PostInvitesByTokenAcceptResponse = (PostInvitesByTokenAcceptStatus200 | PostInvitesByTokenAcceptStatus400 | PostInvitesByTokenAcceptStatus401 | PostInvitesByTokenAcceptStatus403);
