/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEndpointsAuthVerifyPostRequest } from './FbsWebApiEndpointsAuthVerifyPostRequest'

export type PostAuthVerifyStatus204 = unknown;

export type PostAuthVerifyBody = FbsWebApiEndpointsAuthVerifyPostRequest;

export type PostAuthVerifyOptions = {
    body: PostAuthVerifyBody;
    path?: never;
    query?: never;
    headers?: never;
};

export type PostAuthVerifyResponses = {
    "204": PostAuthVerifyStatus204;
};

/**
 * @description Union of all possible responses
*/
export type PostAuthVerifyResponse = PostAuthVerifyStatus204;
