/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FastEndpointsProblemDetails } from './FastEndpointsProblemDetails'
import type { FbsWebApiEndpointsOrgInvitesPostRequest } from './FbsWebApiEndpointsOrgInvitesPostRequest'
import type { FbsWebApiEndpointsOrgInvitesPostResponse } from './FbsWebApiEndpointsOrgInvitesPostResponse'

export type PostOrgInvitesPath = {
    slug: string;
};

export type PostOrgInvitesStatus200 = FbsWebApiEndpointsOrgInvitesPostResponse;

/**
 * @description RFC9457 compatible problem details/ error response class. this can be used by configuring startup like so:\napp.UseFastEndpoints(c => c.Errors.UseProblemDetails())
 * @type object
*/
export type PostOrgInvitesStatus400 = FastEndpointsProblemDetails;

export type PostOrgInvitesStatus401 = unknown;

export type PostOrgInvitesStatus403 = unknown;

export type PostOrgInvitesBody = FbsWebApiEndpointsOrgInvitesPostRequest;

export type PostOrgInvitesOptions = {
    body: PostOrgInvitesBody;
    path: PostOrgInvitesPath;
    query?: never;
    headers?: never;
};

export type PostOrgInvitesResponses = {
    "200": PostOrgInvitesStatus200;
    "400": PostOrgInvitesStatus400;
    "401": PostOrgInvitesStatus401;
    "403": PostOrgInvitesStatus403;
};

/**
 * @description Union of all possible responses
*/
export type PostOrgInvitesResponse = (PostOrgInvitesStatus200 | PostOrgInvitesStatus400 | PostOrgInvitesStatus401 | PostOrgInvitesStatus403);
