/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FastEndpointsProblemDetails } from './FastEndpointsProblemDetails'
import type { FbsWebApiEndpointsTenantsPostRequest } from './FbsWebApiEndpointsTenantsPostRequest'
import type { FbsWebApiEndpointsTenantsPostResponse } from './FbsWebApiEndpointsTenantsPostResponse'

export type PostTenantsStatus200 = FbsWebApiEndpointsTenantsPostResponse;

/**
 * @description RFC9457 compatible problem details/ error response class. this can be used by configuring startup like so:\napp.UseFastEndpoints(c => c.Errors.UseProblemDetails())
 * @type object
*/
export type PostTenantsStatus400 = FastEndpointsProblemDetails;

export type PostTenantsStatus401 = unknown;

export type PostTenantsStatus403 = unknown;

export type PostTenantsBody = FbsWebApiEndpointsTenantsPostRequest;

export type PostTenantsOptions = {
    body: PostTenantsBody;
    path?: never;
    query?: never;
    headers?: never;
};

export type PostTenantsResponses = {
    "200": PostTenantsStatus200;
    "400": PostTenantsStatus400;
    "401": PostTenantsStatus401;
    "403": PostTenantsStatus403;
};

/**
 * @description Union of all possible responses
*/
export type PostTenantsResponse = (PostTenantsStatus200 | PostTenantsStatus400 | PostTenantsStatus401 | PostTenantsStatus403);
