/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEntitiesUser } from './FbsWebApiEntitiesUser'

export type PostAdminUsersPath = {
    phone: string;
};

export type PostAdminUsersStatus200 = FbsWebApiEntitiesUser;

export type PostAdminUsersOptions = {
    body?: never;
    path: PostAdminUsersPath;
    query?: never;
    headers?: never;
};

export type PostAdminUsersResponses = {
    "200": PostAdminUsersStatus200;
};

/**
 * @description Union of all possible responses
*/
export type PostAdminUsersResponse = PostAdminUsersStatus200;
