/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FastEndpointsProblemDetails } from './FastEndpointsProblemDetails'
import type { FbsWebApiEndpointsAuthLoginPostRequest } from './FbsWebApiEndpointsAuthLoginPostRequest'

export type PostAuthLoginStatus204 = unknown;

/**
 * @description RFC9457 compatible problem details/ error response class. this can be used by configuring startup like so:\napp.UseFastEndpoints(c => c.Errors.UseProblemDetails())
 * @type object
*/
export type PostAuthLoginStatus400 = FastEndpointsProblemDetails;

export type PostAuthLoginBody = FbsWebApiEndpointsAuthLoginPostRequest;

export type PostAuthLoginOptions = {
    body: PostAuthLoginBody;
    path?: never;
    query?: never;
    headers?: never;
};

export type PostAuthLoginResponses = {
    "204": PostAuthLoginStatus204;
    "400": PostAuthLoginStatus400;
};

/**
 * @description Union of all possible responses
*/
export type PostAuthLoginResponse = (PostAuthLoginStatus204 | PostAuthLoginStatus400);
