/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export type PostAuthLogoutStatus204 = unknown;

export type PostAuthLogoutOptions = {
    body?: never;
    path?: never;
    query?: never;
    headers?: never;
};

export type PostAuthLogoutResponses = {
    "204": PostAuthLogoutStatus204;
};

/**
 * @description Union of all possible responses
*/
export type PostAuthLogoutResponse = PostAuthLogoutStatus204;
