/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FastEndpointsProblemDetails } from './FastEndpointsProblemDetails'
import type { FbsWebApiEndpointsTenantsDeletionPostRequest } from './FbsWebApiEndpointsTenantsDeletionPostRequest'
import type { FbsWebApiEndpointsTenantsDeletionPostResponse } from './FbsWebApiEndpointsTenantsDeletionPostResponse'

export type PostTenantsDeletionPath = {
    slug: string;
};

export type PostTenantsDeletionStatus200 = FbsWebApiEndpointsTenantsDeletionPostResponse;

/**
 * @description RFC9457 compatible problem details/ error response class. this can be used by configuring startup like so:\napp.UseFastEndpoints(c => c.Errors.UseProblemDetails())
 * @type object
*/
export type PostTenantsDeletionStatus400 = FastEndpointsProblemDetails;

export type PostTenantsDeletionStatus401 = unknown;

export type PostTenantsDeletionStatus403 = unknown;

export type PostTenantsDeletionBody = FbsWebApiEndpointsTenantsDeletionPostRequest;

export type PostTenantsDeletionOptions = {
    body: PostTenantsDeletionBody;
    path: PostTenantsDeletionPath;
    query?: never;
    headers?: never;
};

export type PostTenantsDeletionResponses = {
    "200": PostTenantsDeletionStatus200;
    "400": PostTenantsDeletionStatus400;
    "401": PostTenantsDeletionStatus401;
    "403": PostTenantsDeletionStatus403;
};

/**
 * @description Union of all possible responses
*/
export type PostTenantsDeletionResponse = (PostTenantsDeletionStatus200 | PostTenantsDeletionStatus400 | PostTenantsDeletionStatus401 | PostTenantsDeletionStatus403);
