/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FastEndpointsProblemDetails } from './FastEndpointsProblemDetails'
import type { FbsWebApiEndpointsOrgFacilitiesFacilityResponse } from './FbsWebApiEndpointsOrgFacilitiesFacilityResponse'
import type { FbsWebApiEndpointsOrgFacilitiesPostRequest } from './FbsWebApiEndpointsOrgFacilitiesPostRequest'

export type PostOrgFacilitiesPath = {
    slug: string;
};

export type PostOrgFacilitiesStatus200 = FbsWebApiEndpointsOrgFacilitiesFacilityResponse;

/**
 * @description RFC9457 compatible problem details/ error response class. this can be used by configuring startup like so:\napp.UseFastEndpoints(c => c.Errors.UseProblemDetails())
 * @type object
*/
export type PostOrgFacilitiesStatus400 = FastEndpointsProblemDetails;

export type PostOrgFacilitiesStatus401 = unknown;

export type PostOrgFacilitiesStatus403 = unknown;

export type PostOrgFacilitiesBody = FbsWebApiEndpointsOrgFacilitiesPostRequest;

export type PostOrgFacilitiesOptions = {
    body: PostOrgFacilitiesBody;
    path: PostOrgFacilitiesPath;
    query?: never;
    headers?: never;
};

export type PostOrgFacilitiesResponses = {
    "200": PostOrgFacilitiesStatus200;
    "400": PostOrgFacilitiesStatus400;
    "401": PostOrgFacilitiesStatus401;
    "403": PostOrgFacilitiesStatus403;
};

/**
 * @description Union of all possible responses
*/
export type PostOrgFacilitiesResponse = (PostOrgFacilitiesStatus200 | PostOrgFacilitiesStatus400 | PostOrgFacilitiesStatus401 | PostOrgFacilitiesStatus403);
