/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FastEndpointsProblemDetails } from './FastEndpointsProblemDetails'
import type { FbsWebApiEndpointsBookingPostRequest } from './FbsWebApiEndpointsBookingPostRequest'
import type { FbsWebApiEntitiesBooking } from './FbsWebApiEntitiesBooking'

export type PostBookingStatus200 = FbsWebApiEntitiesBooking;

/**
 * @description RFC9457 compatible problem details/ error response class. this can be used by configuring startup like so:\napp.UseFastEndpoints(c => c.Errors.UseProblemDetails())
 * @type object
*/
export type PostBookingStatus400 = FastEndpointsProblemDetails;

export type PostBookingStatus401 = unknown;

export type PostBookingStatus403 = unknown;

export type PostBookingBody = FbsWebApiEndpointsBookingPostRequest;

export type PostBookingOptions = {
    body: PostBookingBody;
    path?: never;
    query?: never;
    headers?: never;
};

export type PostBookingResponses = {
    "200": PostBookingStatus200;
    "400": PostBookingStatus400;
    "401": PostBookingStatus401;
    "403": PostBookingStatus403;
};

/**
 * @description Union of all possible responses
*/
export type PostBookingResponse = (PostBookingStatus200 | PostBookingStatus400 | PostBookingStatus401 | PostBookingStatus403);
