/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FbsWebApiEndpointsAdminBookingsPutRequest } from './FbsWebApiEndpointsAdminBookingsPutRequest'
import type { FbsWebApiEntitiesBooking } from './FbsWebApiEntitiesBooking'

export type PutAdminBookingsPath = {
    /**
     * @description
     * Format: `guid`
     * @type string
    */
    id: string;
};

export type PutAdminBookingsStatus200 = FbsWebApiEntitiesBooking;

export type PutAdminBookingsBody = FbsWebApiEndpointsAdminBookingsPutRequest;

export type PutAdminBookingsOptions = {
    body: PutAdminBookingsBody;
    path: PutAdminBookingsPath;
    query?: never;
    headers?: never;
};

export type PutAdminBookingsResponses = {
    "200": PutAdminBookingsStatus200;
};

/**
 * @description Union of all possible responses
*/
export type PutAdminBookingsResponse = PutAdminBookingsStatus200;
