/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FastEndpointsProblemDetails } from './FastEndpointsProblemDetails'
import type { FbsWebApiEndpointsOrgUnitsByIdPutRequest } from './FbsWebApiEndpointsOrgUnitsByIdPutRequest'
import type { FbsWebApiEndpointsOrgUnitsUnitResponse } from './FbsWebApiEndpointsOrgUnitsUnitResponse'

export type PutOrgUnitsByIdPath = {
    slug: string;
    /**
     * @description
     * Format: `guid`
     * @type string
    */
    id: string;
};

export type PutOrgUnitsByIdStatus200 = FbsWebApiEndpointsOrgUnitsUnitResponse;

/**
 * @description RFC9457 compatible problem details/ error response class. this can be used by configuring startup like so:\napp.UseFastEndpoints(c => c.Errors.UseProblemDetails())
 * @type object
*/
export type PutOrgUnitsByIdStatus400 = FastEndpointsProblemDetails;

export type PutOrgUnitsByIdStatus401 = unknown;

export type PutOrgUnitsByIdStatus403 = unknown;

export type PutOrgUnitsByIdBody = FbsWebApiEndpointsOrgUnitsByIdPutRequest;

export type PutOrgUnitsByIdOptions = {
    body: PutOrgUnitsByIdBody;
    path: PutOrgUnitsByIdPath;
    query?: never;
    headers?: never;
};

export type PutOrgUnitsByIdResponses = {
    "200": PutOrgUnitsByIdStatus200;
    "400": PutOrgUnitsByIdStatus400;
    "401": PutOrgUnitsByIdStatus401;
    "403": PutOrgUnitsByIdStatus403;
};

/**
 * @description Union of all possible responses
*/
export type PutOrgUnitsByIdResponse = (PutOrgUnitsByIdStatus200 | PutOrgUnitsByIdStatus400 | PutOrgUnitsByIdStatus401 | PutOrgUnitsByIdStatus403);
