/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FastEndpointsProblemDetails } from './FastEndpointsProblemDetails'
import type { FbsWebApiEndpointsOrgBookingsBookingResponse } from './FbsWebApiEndpointsOrgBookingsBookingResponse'
import type { FbsWebApiEndpointsOrgBookingsByIdPutRequest } from './FbsWebApiEndpointsOrgBookingsByIdPutRequest'

export type PutOrgBookingsByIdPath = {
    slug: string;
    /**
     * @description
     * Format: `guid`
     * @type string
    */
    id: string;
};

export type PutOrgBookingsByIdStatus200 = FbsWebApiEndpointsOrgBookingsBookingResponse;

/**
 * @description RFC9457 compatible problem details/ error response class. this can be used by configuring startup like so:\napp.UseFastEndpoints(c => c.Errors.UseProblemDetails())
 * @type object
*/
export type PutOrgBookingsByIdStatus400 = FastEndpointsProblemDetails;

export type PutOrgBookingsByIdStatus401 = unknown;

export type PutOrgBookingsByIdStatus403 = unknown;

export type PutOrgBookingsByIdBody = FbsWebApiEndpointsOrgBookingsByIdPutRequest;

export type PutOrgBookingsByIdOptions = {
    body: PutOrgBookingsByIdBody;
    path: PutOrgBookingsByIdPath;
    query?: never;
    headers?: never;
};

export type PutOrgBookingsByIdResponses = {
    "200": PutOrgBookingsByIdStatus200;
    "400": PutOrgBookingsByIdStatus400;
    "401": PutOrgBookingsByIdStatus401;
    "403": PutOrgBookingsByIdStatus403;
};

/**
 * @description Union of all possible responses
*/
export type PutOrgBookingsByIdResponse = (PutOrgBookingsByIdStatus200 | PutOrgBookingsByIdStatus400 | PutOrgBookingsByIdStatus401 | PutOrgBookingsByIdStatus403);
