/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FastEndpointsProblemDetails } from './FastEndpointsProblemDetails'
import type { FbsWebApiEndpointsOrgMembersByIdPutRequest } from './FbsWebApiEndpointsOrgMembersByIdPutRequest'
import type { FbsWebApiEndpointsOrgMembersMemberResponse } from './FbsWebApiEndpointsOrgMembersMemberResponse'

export type PutOrgMembersByIdPath = {
    slug: string;
    /**
     * @description
     * Format: `guid`
     * @type string
    */
    id: string;
};

export type PutOrgMembersByIdStatus200 = FbsWebApiEndpointsOrgMembersMemberResponse;

/**
 * @description RFC9457 compatible problem details/ error response class. this can be used by configuring startup like so:\napp.UseFastEndpoints(c => c.Errors.UseProblemDetails())
 * @type object
*/
export type PutOrgMembersByIdStatus400 = FastEndpointsProblemDetails;

export type PutOrgMembersByIdStatus401 = unknown;

export type PutOrgMembersByIdStatus403 = unknown;

export type PutOrgMembersByIdBody = FbsWebApiEndpointsOrgMembersByIdPutRequest;

export type PutOrgMembersByIdOptions = {
    body: PutOrgMembersByIdBody;
    path: PutOrgMembersByIdPath;
    query?: never;
    headers?: never;
};

export type PutOrgMembersByIdResponses = {
    "200": PutOrgMembersByIdStatus200;
    "400": PutOrgMembersByIdStatus400;
    "401": PutOrgMembersByIdStatus401;
    "403": PutOrgMembersByIdStatus403;
};

/**
 * @description Union of all possible responses
*/
export type PutOrgMembersByIdResponse = (PutOrgMembersByIdStatus200 | PutOrgMembersByIdStatus400 | PutOrgMembersByIdStatus401 | PutOrgMembersByIdStatus403);
