/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FastEndpointsProblemDetails } from './FastEndpointsProblemDetails'
import type { FbsWebApiEndpointsOrgFacilitiesByIdPutRequest } from './FbsWebApiEndpointsOrgFacilitiesByIdPutRequest'
import type { FbsWebApiEndpointsOrgFacilitiesFacilityResponse } from './FbsWebApiEndpointsOrgFacilitiesFacilityResponse'

export type PutOrgFacilitiesByIdPath = {
    slug: string;
    /**
     * @description
     * Format: `guid`
     * @type string
    */
    id: string;
};

export type PutOrgFacilitiesByIdStatus200 = FbsWebApiEndpointsOrgFacilitiesFacilityResponse;

/**
 * @description RFC9457 compatible problem details/ error response class. this can be used by configuring startup like so:\napp.UseFastEndpoints(c => c.Errors.UseProblemDetails())
 * @type object
*/
export type PutOrgFacilitiesByIdStatus400 = FastEndpointsProblemDetails;

export type PutOrgFacilitiesByIdStatus401 = unknown;

export type PutOrgFacilitiesByIdStatus403 = unknown;

export type PutOrgFacilitiesByIdBody = FbsWebApiEndpointsOrgFacilitiesByIdPutRequest;

export type PutOrgFacilitiesByIdOptions = {
    body: PutOrgFacilitiesByIdBody;
    path: PutOrgFacilitiesByIdPath;
    query?: never;
    headers?: never;
};

export type PutOrgFacilitiesByIdResponses = {
    "200": PutOrgFacilitiesByIdStatus200;
    "400": PutOrgFacilitiesByIdStatus400;
    "401": PutOrgFacilitiesByIdStatus401;
    "403": PutOrgFacilitiesByIdStatus403;
};

/**
 * @description Union of all possible responses
*/
export type PutOrgFacilitiesByIdResponse = (PutOrgFacilitiesByIdStatus200 | PutOrgFacilitiesByIdStatus400 | PutOrgFacilitiesByIdStatus401 | PutOrgFacilitiesByIdStatus403);
