/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FastEndpointsProblemDetails } from './FastEndpointsProblemDetails'
import type { FbsWebApiEndpointsOrgSettingsGetResponse } from './FbsWebApiEndpointsOrgSettingsGetResponse'
import type { FbsWebApiEndpointsOrgSettingsPutRequest } from './FbsWebApiEndpointsOrgSettingsPutRequest'

export type PutOrgSettingsPath = {
    slug: string;
};

export type PutOrgSettingsStatus200 = FbsWebApiEndpointsOrgSettingsGetResponse;

/**
 * @description RFC9457 compatible problem details/ error response class. this can be used by configuring startup like so:\napp.UseFastEndpoints(c => c.Errors.UseProblemDetails())
 * @type object
*/
export type PutOrgSettingsStatus400 = FastEndpointsProblemDetails;

export type PutOrgSettingsStatus401 = unknown;

export type PutOrgSettingsStatus403 = unknown;

export type PutOrgSettingsBody = FbsWebApiEndpointsOrgSettingsPutRequest;

export type PutOrgSettingsOptions = {
    body: PutOrgSettingsBody;
    path: PutOrgSettingsPath;
    query?: never;
    headers?: never;
};

export type PutOrgSettingsResponses = {
    "200": PutOrgSettingsStatus200;
    "400": PutOrgSettingsStatus400;
    "401": PutOrgSettingsStatus401;
    "403": PutOrgSettingsStatus403;
};

/**
 * @description Union of all possible responses
*/
export type PutOrgSettingsResponse = (PutOrgSettingsStatus200 | PutOrgSettingsStatus400 | PutOrgSettingsStatus401 | PutOrgSettingsStatus403);
