/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFbsWebApiDtosTimeSlotFromDiscriminatorValue, type FbsWebApiDtosTimeSlot } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Facility/{name}/TimeSlots
 */
export interface TimeSlotsRequestBuilder extends BaseRequestBuilder<TimeSlotsRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FbsWebApiDtosTimeSlot[]>}
     */
     get(requestConfiguration?: RequestConfiguration<TimeSlotsRequestBuilderGetQueryParameters> | undefined) : Promise<FbsWebApiDtosTimeSlot[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<TimeSlotsRequestBuilderGetQueryParameters> | undefined) : RequestInformation;
}
export interface TimeSlotsRequestBuilderGetQueryParameters {
    endTime?: Date;
    startTime?: Date;
}
/**
 * Uri template for the request builder.
 */
export const TimeSlotsRequestBuilderUriTemplate = "{+baseurl}/Facility/{name}/TimeSlots?endTime={endTime}&startTime={startTime}";
/**
 * Metadata for all the requests in the request builder.
 */
export const TimeSlotsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: TimeSlotsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createFbsWebApiDtosTimeSlotFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
