/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { DeleteTenantsDeletionOptions, DeleteTenantsDeletionResponses } from '../types/DeleteTenantsDeletion'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /Tenants/:slug/Deletion}
 */
export function deleteTenantsDeletion<ThrowOnError extends boolean = true>(options: Options<DeleteTenantsDeletionOptions, ThrowOnError>): Unwrappable<RequestResult<DeleteTenantsDeletionResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'DELETE', url: '/Tenants/{slug}/Deletion', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<DeleteTenantsDeletionResponses, ThrowOnError>>)
}
