/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { DeleteOrgBookingsByIdOptions, DeleteOrgBookingsByIdResponses } from '../types/DeleteOrgBookingsById'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /t/:slug/Bookings/:id}
 */
export function deleteOrgBookingsById<ThrowOnError extends boolean = true>(options: Options<DeleteOrgBookingsByIdOptions, ThrowOnError>): Unwrappable<RequestResult<DeleteOrgBookingsByIdResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'DELETE', url: '/t/{slug}/Bookings/{id}', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<DeleteOrgBookingsByIdResponses, ThrowOnError>>)
}
