/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { DeleteMeTelegramOptions, DeleteMeTelegramResponses } from '../types/DeleteMeTelegram'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /Me/Telegram}
 */
export function deleteMeTelegram<ThrowOnError extends boolean = true>(options: Options<DeleteMeTelegramOptions, ThrowOnError> = {}): Unwrappable<RequestResult<DeleteMeTelegramResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'DELETE', url: '/Me/Telegram', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<DeleteMeTelegramResponses, ThrowOnError>>)
}
