/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { DeleteOrgFacilitiesByIdOptions, DeleteOrgFacilitiesByIdResponses } from '../types/DeleteOrgFacilitiesById'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /t/:slug/Facilities/:id}
 */
export function deleteOrgFacilitiesById<ThrowOnError extends boolean = true>(options: Options<DeleteOrgFacilitiesByIdOptions, ThrowOnError>): Unwrappable<RequestResult<DeleteOrgFacilitiesByIdResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'DELETE', url: '/t/{slug}/Facilities/{id}', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<DeleteOrgFacilitiesByIdResponses, ThrowOnError>>)
}
