/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { DeleteOrgUnitsByIdOptions, DeleteOrgUnitsByIdResponses } from '../types/DeleteOrgUnitsById'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /t/:slug/Units/:id}
 */
export function deleteOrgUnitsById<ThrowOnError extends boolean = true>(options: Options<DeleteOrgUnitsByIdOptions, ThrowOnError>): Unwrappable<RequestResult<DeleteOrgUnitsByIdResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'DELETE', url: '/t/{slug}/Units/{id}', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<DeleteOrgUnitsByIdResponses, ThrowOnError>>)
}
