/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { DeleteOrgInvitesByIdOptions, DeleteOrgInvitesByIdResponses } from '../types/DeleteOrgInvitesById'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /t/:slug/Invites/:id}
 */
export function deleteOrgInvitesById<ThrowOnError extends boolean = true>(options: Options<DeleteOrgInvitesByIdOptions, ThrowOnError>): Unwrappable<RequestResult<DeleteOrgInvitesByIdResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'DELETE', url: '/t/{slug}/Invites/{id}', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<DeleteOrgInvitesByIdResponses, ThrowOnError>>)
}
