/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { DeleteAdminBookingsOptions, DeleteAdminBookingsResponses } from '../types/DeleteAdminBookings'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /Admin/Bookings/:id}
 */
export function deleteAdminBookings<ThrowOnError extends boolean = true>(options: Options<DeleteAdminBookingsOptions, ThrowOnError>): Unwrappable<RequestResult<DeleteAdminBookingsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'DELETE', url: '/Admin/Bookings/{id}', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<DeleteAdminBookingsResponses, ThrowOnError>>)
}
