/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { DeleteBookingByIdOptions, DeleteBookingByIdResponses } from '../types/DeleteBookingById'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /Booking/:id}
 */
export function deleteBookingById<ThrowOnError extends boolean = true>(options: Options<DeleteBookingByIdOptions, ThrowOnError>): Unwrappable<RequestResult<DeleteBookingByIdResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'DELETE', url: '/Booking/{id}', security: [{ type: 'http', scheme: 'bearer' }], ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<DeleteBookingByIdResponses, ThrowOnError>>)
}
