/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { GetAdminBookingsOptions, GetAdminBookingsResponses } from '../types/GetAdminBookings'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /Admin/Bookings}
 */
export function getAdminBookings<ThrowOnError extends boolean = true>(options: Options<GetAdminBookingsOptions, ThrowOnError> = {}): Unwrappable<RequestResult<GetAdminBookingsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'GET', url: '/Admin/Bookings', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<GetAdminBookingsResponses, ThrowOnError>>)
}
