/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { GetAdminUsersOptions, GetAdminUsersResponses } from '../types/GetAdminUsers'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /Admin/Users}
 */
export function getAdminUsers<ThrowOnError extends boolean = true>(options: Options<GetAdminUsersOptions, ThrowOnError> = {}): Unwrappable<RequestResult<GetAdminUsersResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'GET', url: '/Admin/Users', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<GetAdminUsersResponses, ThrowOnError>>)
}
