/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { GetAuthMeOptions, GetAuthMeResponses } from '../types/GetAuthMe'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /Auth/Me}
 */
export function getAuthMe<ThrowOnError extends boolean = true>(options: Options<GetAuthMeOptions, ThrowOnError> = {}): Unwrappable<RequestResult<GetAuthMeResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'GET', url: '/Auth/Me', security: [{ type: 'http', scheme: 'bearer' }], ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<GetAuthMeResponses, ThrowOnError>>)
}
