/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { GetAdminBookingsByIdOptions, GetAdminBookingsByIdResponses } from '../types/GetAdminBookingsById'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /Admin/Bookings/:id}
 */
export function getAdminBookingsById<ThrowOnError extends boolean = true>(options: Options<GetAdminBookingsByIdOptions, ThrowOnError>): Unwrappable<RequestResult<GetAdminBookingsByIdResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'GET', url: '/Admin/Bookings/{id}', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<GetAdminBookingsByIdResponses, ThrowOnError>>)
}
