/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { GetBookingByIdOptions, GetBookingByIdResponses } from '../types/GetBookingById'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /Booking/:id}
 */
export function getBookingById<ThrowOnError extends boolean = true>(options: Options<GetBookingByIdOptions, ThrowOnError>): Unwrappable<RequestResult<GetBookingByIdResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'GET', url: '/Booking/{id}', security: [{ type: 'http', scheme: 'bearer' }], ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<GetBookingByIdResponses, ThrowOnError>>)
}
