/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { GetBookingOptions, GetBookingResponses } from '../types/GetBooking'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /Booking}
 */
export function getBooking<ThrowOnError extends boolean = true>(options: Options<GetBookingOptions, ThrowOnError> = {}): Unwrappable<RequestResult<GetBookingResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'GET', url: '/Booking', security: [{ type: 'http', scheme: 'bearer' }], ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<GetBookingResponses, ThrowOnError>>)
}
