/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { GetCachePurgeOptions, GetCachePurgeResponses } from '../types/GetCachePurge'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /Cache/Purge}
 */
export function getCachePurge<ThrowOnError extends boolean = true>(options: Options<GetCachePurgeOptions, ThrowOnError> = {}): Unwrappable<RequestResult<GetCachePurgeResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'GET', url: '/Cache/Purge', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<GetCachePurgeResponses, ThrowOnError>>)
}
