/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { GetClaimsBySlugOptions, GetClaimsBySlugResponses } from '../types/GetClaimsBySlug'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /Claims/:slug}
 */
export function getClaimsBySlug<ThrowOnError extends boolean = true>(options: Options<GetClaimsBySlugOptions, ThrowOnError>): Unwrappable<RequestResult<GetClaimsBySlugResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'GET', url: '/Claims/{slug}', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<GetClaimsBySlugResponses, ThrowOnError>>)
}
