/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { GetFacilityOptions, GetFacilityResponses } from '../types/GetFacility'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /Facility}
 */
export function getFacility<ThrowOnError extends boolean = true>(options: Options<GetFacilityOptions, ThrowOnError> = {}): Unwrappable<RequestResult<GetFacilityResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'GET', url: '/Facility', security: [{ type: 'http', scheme: 'bearer' }], ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<GetFacilityResponses, ThrowOnError>>)
}
