/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { GetFacilityTimeSlotsOptions, GetFacilityTimeSlotsResponses } from '../types/GetFacilityTimeSlots'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /Facility/:name/TimeSlots}
 */
export function getFacilityTimeSlots<ThrowOnError extends boolean = true>(options: Options<GetFacilityTimeSlotsOptions, ThrowOnError>): Unwrappable<RequestResult<GetFacilityTimeSlotsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'GET', url: '/Facility/{name}/TimeSlots', security: [{ type: 'http', scheme: 'bearer' }], ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<GetFacilityTimeSlotsResponses, ThrowOnError>>)
}
