/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { GetInvitesByTokenOptions, GetInvitesByTokenResponses } from '../types/GetInvitesByToken'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /Invites/:token}
 */
export function getInvitesByToken<ThrowOnError extends boolean = true>(options: Options<GetInvitesByTokenOptions, ThrowOnError>): Unwrappable<RequestResult<GetInvitesByTokenResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'GET', url: '/Invites/{token}', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<GetInvitesByTokenResponses, ThrowOnError>>)
}
