/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { GetMeExportOptions, GetMeExportResponses } from '../types/GetMeExport'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /Me/Export}
 */
export function getMeExport<ThrowOnError extends boolean = true>(options: Options<GetMeExportOptions, ThrowOnError> = {}): Unwrappable<RequestResult<GetMeExportResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'GET', url: '/Me/Export', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<GetMeExportResponses, ThrowOnError>>)
}
