/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { GetMeOptions, GetMeResponses } from '../types/GetMe'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /Me}
 */
export function getMe<ThrowOnError extends boolean = true>(options: Options<GetMeOptions, ThrowOnError> = {}): Unwrappable<RequestResult<GetMeResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'GET', url: '/Me', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<GetMeResponses, ThrowOnError>>)
}
