/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { GetMeTelegramOptions, GetMeTelegramResponses } from '../types/GetMeTelegram'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /Me/Telegram}
 */
export function getMeTelegram<ThrowOnError extends boolean = true>(options: Options<GetMeTelegramOptions, ThrowOnError> = {}): Unwrappable<RequestResult<GetMeTelegramResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'GET', url: '/Me/Telegram', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<GetMeTelegramResponses, ThrowOnError>>)
}
