/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { GetNominalRollOptions, GetNominalRollResponses } from '../types/GetNominalRoll'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /NominalRoll}
 */
export function getNominalRoll<ThrowOnError extends boolean = true>(options: Options<GetNominalRollOptions, ThrowOnError> = {}): Unwrappable<RequestResult<GetNominalRollResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'GET', url: '/NominalRoll', security: [{ type: 'http', scheme: 'bearer' }], ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<GetNominalRollResponses, ThrowOnError>>)
}
