/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { GetOrgSettingsOptions, GetOrgSettingsResponses } from '../types/GetOrgSettings'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /t/:slug/Settings}
 */
export function getOrgSettings<ThrowOnError extends boolean = true>(options: Options<GetOrgSettingsOptions, ThrowOnError>): Unwrappable<RequestResult<GetOrgSettingsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'GET', url: '/t/{slug}/Settings', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<GetOrgSettingsResponses, ThrowOnError>>)
}
