/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { GetOrgAuditOptions, GetOrgAuditResponses } from '../types/GetOrgAudit'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /t/:slug/Audit}
 */
export function getOrgAudit<ThrowOnError extends boolean = true>(options: Options<GetOrgAuditOptions, ThrowOnError>): Unwrappable<RequestResult<GetOrgAuditResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'GET', url: '/t/{slug}/Audit', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<GetOrgAuditResponses, ThrowOnError>>)
}
