/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { GetOrgBookingsOptions, GetOrgBookingsResponses } from '../types/GetOrgBookings'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /t/:slug/Bookings}
 */
export function getOrgBookings<ThrowOnError extends boolean = true>(options: Options<GetOrgBookingsOptions, ThrowOnError>): Unwrappable<RequestResult<GetOrgBookingsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'GET', url: '/t/{slug}/Bookings', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<GetOrgBookingsResponses, ThrowOnError>>)
}
