/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { GetOrgBookingsByIdOptions, GetOrgBookingsByIdResponses } from '../types/GetOrgBookingsById'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /t/:slug/Bookings/:id}
 */
export function getOrgBookingsById<ThrowOnError extends boolean = true>(options: Options<GetOrgBookingsByIdOptions, ThrowOnError>): Unwrappable<RequestResult<GetOrgBookingsByIdResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'GET', url: '/t/{slug}/Bookings/{id}', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<GetOrgBookingsByIdResponses, ThrowOnError>>)
}
