/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { GetOrgUnitsOptions, GetOrgUnitsResponses } from '../types/GetOrgUnits'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /t/:slug/Units}
 */
export function getOrgUnits<ThrowOnError extends boolean = true>(options: Options<GetOrgUnitsOptions, ThrowOnError>): Unwrappable<RequestResult<GetOrgUnitsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'GET', url: '/t/{slug}/Units', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<GetOrgUnitsResponses, ThrowOnError>>)
}
