/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { GetOrgFacilitiesOptions, GetOrgFacilitiesResponses } from '../types/GetOrgFacilities'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /t/:slug/Facilities}
 */
export function getOrgFacilities<ThrowOnError extends boolean = true>(options: Options<GetOrgFacilitiesOptions, ThrowOnError>): Unwrappable<RequestResult<GetOrgFacilitiesResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'GET', url: '/t/{slug}/Facilities', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<GetOrgFacilitiesResponses, ThrowOnError>>)
}
