/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { GetOrgMembersOptions, GetOrgMembersResponses } from '../types/GetOrgMembers'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /t/:slug/Members}
 */
export function getOrgMembers<ThrowOnError extends boolean = true>(options: Options<GetOrgMembersOptions, ThrowOnError>): Unwrappable<RequestResult<GetOrgMembersResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'GET', url: '/t/{slug}/Members', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<GetOrgMembersResponses, ThrowOnError>>)
}
