/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { GetOrgExportOptions, GetOrgExportResponses } from '../types/GetOrgExport'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /t/:slug/Export}
 */
export function getOrgExport<ThrowOnError extends boolean = true>(options: Options<GetOrgExportOptions, ThrowOnError>): Unwrappable<RequestResult<GetOrgExportResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'GET', url: '/t/{slug}/Export', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<GetOrgExportResponses, ThrowOnError>>)
}
