/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { GetOrgInvitesOptions, GetOrgInvitesResponses } from '../types/GetOrgInvites'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /t/:slug/Invites}
 */
export function getOrgInvites<ThrowOnError extends boolean = true>(options: Options<GetOrgInvitesOptions, ThrowOnError>): Unwrappable<RequestResult<GetOrgInvitesResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'GET', url: '/t/{slug}/Invites', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<GetOrgInvitesResponses, ThrowOnError>>)
}
