/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { GetOrgOptions, GetOrgResponses } from '../types/GetOrg'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /t/:slug}
 */
export function getOrg<ThrowOnError extends boolean = true>(options: Options<GetOrgOptions, ThrowOnError>): Unwrappable<RequestResult<GetOrgResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'GET', url: '/t/{slug}', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<GetOrgResponses, ThrowOnError>>)
}
