/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { GetOrgFacilitiesBookableOptions, GetOrgFacilitiesBookableResponses } from '../types/GetOrgFacilitiesBookable'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /t/:slug/Facilities/Bookable}
 */
export function getOrgFacilitiesBookable<ThrowOnError extends boolean = true>(options: Options<GetOrgFacilitiesBookableOptions, ThrowOnError>): Unwrappable<RequestResult<GetOrgFacilitiesBookableResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'GET', url: '/t/{slug}/Facilities/Bookable', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<GetOrgFacilitiesBookableResponses, ThrowOnError>>)
}
