/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { PostTenantsOptions, PostTenantsResponses } from '../types/PostTenants'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /Tenants}
 */
export function postTenants<ThrowOnError extends boolean = true>(options: Options<PostTenantsOptions, ThrowOnError>): Unwrappable<RequestResult<PostTenantsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'POST', url: '/Tenants', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<PostTenantsResponses, ThrowOnError>>)
}
