/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { PostBookingByIdOptions, PostBookingByIdResponses } from '../types/PostBookingById'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /Booking/:id}
 */
export function postBookingById<ThrowOnError extends boolean = true>(options: Options<PostBookingByIdOptions, ThrowOnError>): Unwrappable<RequestResult<PostBookingByIdResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'POST', url: '/Booking/{id}', security: [{ type: 'http', scheme: 'bearer' }], ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<PostBookingByIdResponses, ThrowOnError>>)
}
