/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { PostOrgBookingsOptions, PostOrgBookingsResponses } from '../types/PostOrgBookings'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /t/:slug/Bookings}
 */
export function postOrgBookings<ThrowOnError extends boolean = true>(options: Options<PostOrgBookingsOptions, ThrowOnError>): Unwrappable<RequestResult<PostOrgBookingsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'POST', url: '/t/{slug}/Bookings', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<PostOrgBookingsResponses, ThrowOnError>>)
}
