/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { PostOrgInvitesOptions, PostOrgInvitesResponses } from '../types/PostOrgInvites'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /t/:slug/Invites}
 */
export function postOrgInvites<ThrowOnError extends boolean = true>(options: Options<PostOrgInvitesOptions, ThrowOnError>): Unwrappable<RequestResult<PostOrgInvitesResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'POST', url: '/t/{slug}/Invites', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<PostOrgInvitesResponses, ThrowOnError>>)
}
