/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { PostInvitesByTokenAcceptOptions, PostInvitesByTokenAcceptResponses } from '../types/PostInvitesByTokenAccept'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /Invites/:token/Accept}
 */
export function postInvitesByTokenAccept<ThrowOnError extends boolean = true>(options: Options<PostInvitesByTokenAcceptOptions, ThrowOnError>): Unwrappable<RequestResult<PostInvitesByTokenAcceptResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'POST', url: '/Invites/{token}/Accept', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<PostInvitesByTokenAcceptResponses, ThrowOnError>>)
}
