/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { PostBookingBatchOptions, PostBookingBatchResponses } from '../types/PostBookingBatch'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /Booking/Batch}
 */
export function postBookingBatch<ThrowOnError extends boolean = true>(options: Options<PostBookingBatchOptions, ThrowOnError>): Unwrappable<RequestResult<PostBookingBatchResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'POST', url: '/Booking/Batch', security: [{ type: 'http', scheme: 'bearer' }], ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<PostBookingBatchResponses, ThrowOnError>>)
}
