/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { PostOrgUnitsOptions, PostOrgUnitsResponses } from '../types/PostOrgUnits'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /t/:slug/Units}
 */
export function postOrgUnits<ThrowOnError extends boolean = true>(options: Options<PostOrgUnitsOptions, ThrowOnError>): Unwrappable<RequestResult<PostOrgUnitsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'POST', url: '/t/{slug}/Units', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<PostOrgUnitsResponses, ThrowOnError>>)
}
