/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { PostAuthVerifyOptions, PostAuthVerifyResponses } from '../types/PostAuthVerify'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /Auth/Verify}
 */
export function postAuthVerify<ThrowOnError extends boolean = true>(options: Options<PostAuthVerifyOptions, ThrowOnError>): Unwrappable<RequestResult<PostAuthVerifyResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'POST', url: '/Auth/Verify', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<PostAuthVerifyResponses, ThrowOnError>>)
}
