/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { PostOrgFacilitiesOptions, PostOrgFacilitiesResponses } from '../types/PostOrgFacilities'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /t/:slug/Facilities}
 */
export function postOrgFacilities<ThrowOnError extends boolean = true>(options: Options<PostOrgFacilitiesOptions, ThrowOnError>): Unwrappable<RequestResult<PostOrgFacilitiesResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'POST', url: '/t/{slug}/Facilities', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<PostOrgFacilitiesResponses, ThrowOnError>>)
}
