/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { PostClaimsBySlugStartOptions, PostClaimsBySlugStartResponses } from '../types/PostClaimsBySlugStart'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /Claims/:slug/Start}
 */
export function postClaimsBySlugStart<ThrowOnError extends boolean = true>(options: Options<PostClaimsBySlugStartOptions, ThrowOnError>): Unwrappable<RequestResult<PostClaimsBySlugStartResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'POST', url: '/Claims/{slug}/Start', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<PostClaimsBySlugStartResponses, ThrowOnError>>)
}
