/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { PostMeTelegramLinkOptions, PostMeTelegramLinkResponses } from '../types/PostMeTelegramLink'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /Me/Telegram/Link}
 */
export function postMeTelegramLink<ThrowOnError extends boolean = true>(options: Options<PostMeTelegramLinkOptions, ThrowOnError> = {}): Unwrappable<RequestResult<PostMeTelegramLinkResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'POST', url: '/Me/Telegram/Link', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<PostMeTelegramLinkResponses, ThrowOnError>>)
}
