/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { PostTenantsDeletionOptions, PostTenantsDeletionResponses } from '../types/PostTenantsDeletion'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /Tenants/:slug/Deletion}
 */
export function postTenantsDeletion<ThrowOnError extends boolean = true>(options: Options<PostTenantsDeletionOptions, ThrowOnError>): Unwrappable<RequestResult<PostTenantsDeletionResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'POST', url: '/Tenants/{slug}/Deletion', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<PostTenantsDeletionResponses, ThrowOnError>>)
}
