/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { PostAuthLoginOptions, PostAuthLoginResponses } from '../types/PostAuthLogin'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /Auth/Login}
 */
export function postAuthLogin<ThrowOnError extends boolean = true>(options: Options<PostAuthLoginOptions, ThrowOnError>): Unwrappable<RequestResult<PostAuthLoginResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'POST', url: '/Auth/Login', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<PostAuthLoginResponses, ThrowOnError>>)
}
