/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { PostAuthLogoutOptions, PostAuthLogoutResponses } from '../types/PostAuthLogout'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /Auth/Logout}
 */
export function postAuthLogout<ThrowOnError extends boolean = true>(options: Options<PostAuthLogoutOptions, ThrowOnError> = {}): Unwrappable<RequestResult<PostAuthLogoutResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'POST', url: '/Auth/Logout', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<PostAuthLogoutResponses, ThrowOnError>>)
}
