/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { PostAdminUsersOptions, PostAdminUsersResponses } from '../types/PostAdminUsers'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /Admin/Users/:phone/Admin}
 */
export function postAdminUsers<ThrowOnError extends boolean = true>(options: Options<PostAdminUsersOptions, ThrowOnError>): Unwrappable<RequestResult<PostAdminUsersResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'POST', url: '/Admin/Users/{phone}/Admin', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<PostAdminUsersResponses, ThrowOnError>>)
}
