/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { PostBookingOptions, PostBookingResponses } from '../types/PostBooking'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /Booking}
 */
export function postBooking<ThrowOnError extends boolean = true>(options: Options<PostBookingOptions, ThrowOnError>): Unwrappable<RequestResult<PostBookingResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'POST', url: '/Booking', security: [{ type: 'http', scheme: 'bearer' }], ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<PostBookingResponses, ThrowOnError>>)
}
