/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { PostOrgMembersOptions, PostOrgMembersResponses } from '../types/PostOrgMembers'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /t/:slug/Members}
 */
export function postOrgMembers<ThrowOnError extends boolean = true>(options: Options<PostOrgMembersOptions, ThrowOnError>): Unwrappable<RequestResult<PostOrgMembersResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'POST', url: '/t/{slug}/Members', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<PostOrgMembersResponses, ThrowOnError>>)
}
