/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { PutAdminBookingsOptions, PutAdminBookingsResponses } from '../types/PutAdminBookings'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /Admin/Bookings/:id}
 */
export function putAdminBookings<ThrowOnError extends boolean = true>(options: Options<PutAdminBookingsOptions, ThrowOnError>): Unwrappable<RequestResult<PutAdminBookingsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'PUT', url: '/Admin/Bookings/{id}', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<PutAdminBookingsResponses, ThrowOnError>>)
}
