/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { PutOrgUnitsByIdOptions, PutOrgUnitsByIdResponses } from '../types/PutOrgUnitsById'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /t/:slug/Units/:id}
 */
export function putOrgUnitsById<ThrowOnError extends boolean = true>(options: Options<PutOrgUnitsByIdOptions, ThrowOnError>): Unwrappable<RequestResult<PutOrgUnitsByIdResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'PUT', url: '/t/{slug}/Units/{id}', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<PutOrgUnitsByIdResponses, ThrowOnError>>)
}
