/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { PutOrgMembersByIdOptions, PutOrgMembersByIdResponses } from '../types/PutOrgMembersById'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /t/:slug/Members/:id}
 */
export function putOrgMembersById<ThrowOnError extends boolean = true>(options: Options<PutOrgMembersByIdOptions, ThrowOnError>): Unwrappable<RequestResult<PutOrgMembersByIdResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'PUT', url: '/t/{slug}/Members/{id}', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<PutOrgMembersByIdResponses, ThrowOnError>>)
}
