/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { PutOrgFacilitiesByIdOptions, PutOrgFacilitiesByIdResponses } from '../types/PutOrgFacilitiesById'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /t/:slug/Facilities/:id}
 */
export function putOrgFacilitiesById<ThrowOnError extends boolean = true>(options: Options<PutOrgFacilitiesByIdOptions, ThrowOnError>): Unwrappable<RequestResult<PutOrgFacilitiesByIdResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'PUT', url: '/t/{slug}/Facilities/{id}', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<PutOrgFacilitiesByIdResponses, ThrowOnError>>)
}
