/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { PutOrgSettingsOptions, PutOrgSettingsResponses } from '../types/PutOrgSettings'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /t/:slug/Settings}
 */
export function putOrgSettings<ThrowOnError extends boolean = true>(options: Options<PutOrgSettingsOptions, ThrowOnError>): Unwrappable<RequestResult<PutOrgSettingsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'PUT', url: '/t/{slug}/Settings', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<PutOrgSettingsResponses, ThrowOnError>>)
}
