/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { PutOrgBookingsByIdOptions, PutOrgBookingsByIdResponses } from '../types/PutOrgBookingsById'
import { client, withUnwrap } from '../.kubb/client'

/**
 * {@link /t/:slug/Bookings/:id}
 */
export function putOrgBookingsById<ThrowOnError extends boolean = true>(options: Options<PutOrgBookingsByIdOptions, ThrowOnError>): Unwrappable<RequestResult<PutOrgBookingsByIdResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return withUnwrap(request({ method: 'PUT', url: '/t/{slug}/Bookings/{id}', ...config, throwOnError: config.throwOnError ?? true }) as Promise<RequestResult<PutOrgBookingsByIdResponses, ThrowOnError>>)
}
