/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFbsWebApiDtosBookingWithUserFromDiscriminatorValue, createFbsWebApiEntitiesBookingFromDiscriminatorValue, serializeFbsWebApiEndpointsAdminBookingsPutRequest, serializeFbsWebApiEntitiesBooking, type FbsWebApiDtosBookingWithUser, type FbsWebApiEndpointsAdminBookingsPutRequest, type FbsWebApiEntitiesBooking } from '../../../models/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Admin/Bookings/{id}
 */
export interface BookingsItemRequestBuilder extends BaseRequestBuilder<BookingsItemRequestBuilder> {
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     */
     delete(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<void>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FbsWebApiDtosBookingWithUser>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<FbsWebApiDtosBookingWithUser | undefined>;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FbsWebApiEntitiesBooking>}
     */
     put(body: FbsWebApiEndpointsAdminBookingsPutRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<FbsWebApiEntitiesBooking | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toDeleteRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
    /**
     * @param body The request body
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toPutRequestInformation(body: FbsWebApiEndpointsAdminBookingsPutRequest, requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const BookingsItemRequestBuilderUriTemplate = "{+baseurl}/Admin/Bookings/{id}";
/**
 * Metadata for all the requests in the request builder.
 */
export const BookingsItemRequestBuilderRequestsMetadata: RequestsMetadata = {
    delete: {
        uriTemplate: BookingsItemRequestBuilderUriTemplate,
        adapterMethodName: "sendNoResponseContent",
    },
    get: {
        uriTemplate: BookingsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createFbsWebApiDtosBookingWithUserFromDiscriminatorValue,
    },
    put: {
        uriTemplate: BookingsItemRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "send",
        responseBodyFactory:  createFbsWebApiEntitiesBookingFromDiscriminatorValue,
        requestBodyContentType: "application/json",
        requestBodySerializer: serializeFbsWebApiEndpointsAdminBookingsPutRequest,
        requestInformationContentSetMethod: "setContentFromParsable",
    },
};
/* tslint:enable */
/* eslint-enable */
