/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { AdminRequestBuilderRequestsMetadata, type AdminRequestBuilder } from './admin/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Admin/Users/{phone}
 */
export interface WithPhoneItemRequestBuilder extends BaseRequestBuilder<WithPhoneItemRequestBuilder> {
    /**
     * The Admin property
     */
    get admin(): AdminRequestBuilder;
}
/**
 * Uri template for the request builder.
 */
export const WithPhoneItemRequestBuilderUriTemplate = "{+baseurl}/Admin/Users/{phone}";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const WithPhoneItemRequestBuilderNavigationMetadata: Record<Exclude<keyof WithPhoneItemRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    admin: {
        requestsMetadata: AdminRequestBuilderRequestsMetadata,
    },
};
/* tslint:enable */
/* eslint-enable */
