/* tslint:disable */
/* eslint-disable */
// Generated by Microsoft Kiota
// @ts-ignore
import { createFbsWebApiDtosBookingWithUserFromDiscriminatorValue, type FbsWebApiDtosBookingWithUser } from '../../models/index.js';
// @ts-ignore
import { BookingsItemRequestBuilderRequestsMetadata, type BookingsItemRequestBuilder } from './item/index.js';
// @ts-ignore
import { type BaseRequestBuilder, type KeysToExcludeForNavigationMetadata, type NavigationMetadata, type Parsable, type ParsableFactory, type RequestConfiguration, type RequestInformation, type RequestsMetadata } from '@microsoft/kiota-abstractions';

/**
 * Builds and executes requests for operations under /Admin/Bookings
 */
export interface BookingsRequestBuilder extends BaseRequestBuilder<BookingsRequestBuilder> {
    /**
     * Gets an item from the ApiSdk.Admin.Bookings.item collection
     * @param id Unique identifier of the item
     * @returns {BookingsItemRequestBuilder}
     */
     byId(id: string) : BookingsItemRequestBuilder;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {Promise<FbsWebApiDtosBookingWithUser[]>}
     */
     get(requestConfiguration?: RequestConfiguration<object> | undefined) : Promise<FbsWebApiDtosBookingWithUser[] | undefined>;
    /**
     * @param requestConfiguration Configuration for the request such as headers, query parameters, and middleware options.
     * @returns {RequestInformation}
     */
     toGetRequestInformation(requestConfiguration?: RequestConfiguration<object> | undefined) : RequestInformation;
}
/**
 * Uri template for the request builder.
 */
export const BookingsRequestBuilderUriTemplate = "{+baseurl}/Admin/Bookings";
/**
 * Metadata for all the navigation properties in the request builder.
 */
export const BookingsRequestBuilderNavigationMetadata: Record<Exclude<keyof BookingsRequestBuilder, KeysToExcludeForNavigationMetadata>, NavigationMetadata> = {
    byId: {
        requestsMetadata: BookingsItemRequestBuilderRequestsMetadata,
        pathParametersMappings: ["id"],
    },
};
/**
 * Metadata for all the requests in the request builder.
 */
export const BookingsRequestBuilderRequestsMetadata: RequestsMetadata = {
    get: {
        uriTemplate: BookingsRequestBuilderUriTemplate,
        responseBodyContentType: "application/json",
        adapterMethodName: "sendCollection",
        responseBodyFactory:  createFbsWebApiDtosBookingWithUserFromDiscriminatorValue,
    },
};
/* tslint:enable */
/* eslint-enable */
