name: Deploy

on:
  push:
  workflow_dispatch: { }

env:
  UKC_TOKEN: ${{ secrets.UKC_TOKEN }}
  UKC_METRO: sin0

jobs:
  deploy:
    concurrency: deploy
    permissions:
      packages: write
      contents: read
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Docker meta
        uses: docker/metadata-action@v5

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to OCI registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - uses: unikraft/kraftkit@stable
        with:
          run: |
            kraft cloud deploy \
              --rollout remove \
              -g 3sib-fbs \
              -M 1024 \
              -e TZ="Asia/Singapore" \
              -e DOTNET_URLS="http://0.0.0.0:5000" \
              -e Telegram__WebhookUrl="https://3sib-fbs-api.from.sg/Bot" \
              -e Telegram__Token="${{ secrets.TELEGRAM_TOKEN }}" \
              -e Google__SpreadsheetId="1CBKV1aWpR5axdWL7AJZt6K4SKL8SOOO3IomMtY8EQKU" \
              -e Google__ServiceAccountJsonCredential='${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON_CREDENTIAL }}' \
              -e Google__CalendarId="497fc5c8633621812414b1f4e88f7d7147a6fd39bb58a2591bdb68bca0b38ece@group.calendar.google.com" \
              -e Google__CarbonCopyCalendarId="6f6816ecfc3ad2aad3cde8eb6afcf5d51639a42b4b3a9c3e97c576b09ba78cd6@group.calendar.google.com" \
              -e OTEL_ATTRIBUTE_COUNT_LIMIT=64 \
              -e OTEL_ATTRIBUTE_VALUE_LENGTH_LIMIT=4095 \
              -e OTEL_EXPORTER_OTLP_ENDPOINT=https://otlp.eu01.nr-data.net \
              -e OTEL_EXPORTER_OTLP_HEADERS='${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}' \
              -e OTEL_SERVICE_NAME="Fbs";